package Gistl01h;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                            CA Gen r8
//
//           Copyright (c) 2012 CA. All rights reserved.
//
//    Name: GISTL01S_IA                      Date: 2012/05/15
//    User: Tanderw                          Time: 13:57:43
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen80.vwrt.*;
import com.ca.gen80.vwrt.types.*;
import com.ca.gen80.vwrt.vdf.*;
import com.ca.gen80.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: GISTL01S_IA
 **/
public class GISTL01S_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN
  //        Type: STAFF
  /**
   * Attribute missing flag for: InStaffPersno
   **/
  public char InStaffPersno_AS;
  /**
   * Attribute for: InStaffPersno
   **/
  public int InStaffPersno;
  /**
   * Attribute missing flag for: InStaffSurname
   **/
  public char InStaffSurname_AS;
  /**
   * Attribute for: InStaffSurname
   **/
  public String InStaffSurname;
  /**
   * Attribute missing flag for: InStaffInitials
   **/
  public char InStaffInitials_AS;
  /**
   * Attribute for: InStaffInitials
   **/
  public String InStaffInitials;
  /**
   * Attribute missing flag for: InStaffTitle
   **/
  public char InStaffTitle_AS;
  /**
   * Attribute for: InStaffTitle
   **/
  public String InStaffTitle;
  /**
   * Attribute missing flag for: InStaffName
   **/
  public char InStaffName_AS;
  /**
   * Attribute for: InStaffName
   **/
  public String InStaffName;
  /**
   * Attribute missing flag for: InStaffLanguageCode
   **/
  public char InStaffLanguageCode_AS;
  /**
   * Attribute for: InStaffLanguageCode
   **/
  public String InStaffLanguageCode;
  /**
   * Attribute missing flag for: InStaffMkDeptCode
   **/
  public char InStaffMkDeptCode_AS;
  /**
   * Attribute for: InStaffMkDeptCode
   **/
  public short InStaffMkDeptCode;
  /**
   * Attribute missing flag for: InStaffResignDate
   **/
  public char InStaffResignDate_AS;
  /**
   * Attribute for: InStaffResignDate
   **/
  public int InStaffResignDate;
  /**
   * Attribute missing flag for: InStaffEmailAddress
   **/
  public char InStaffEmailAddress_AS;
  /**
   * Attribute for: InStaffEmailAddress
   **/
  public String InStaffEmailAddress;
  /**
   * Attribute missing flag for: InStaffContactTelno
   **/
  public char InStaffContactTelno_AS;
  /**
   * Attribute for: InStaffContactTelno
   **/
  public String InStaffContactTelno;
  /**
   * Attribute missing flag for: InStaffOfficeNo
   **/
  public char InStaffOfficeNo_AS;
  /**
   * Attribute for: InStaffOfficeNo
   **/
  public String InStaffOfficeNo;
  /**
   * Attribute missing flag for: InStaffMkSubdeptCode
   **/
  public char InStaffMkSubdeptCode_AS;
  /**
   * Attribute for: InStaffMkSubdeptCode
   **/
  public short InStaffMkSubdeptCode;
  /**
   * Attribute missing flag for: InStaffOldStaffNr
   **/
  public char InStaffOldStaffNr_AS;
  /**
   * Attribute for: InStaffOldStaffNr
   **/
  public int InStaffOldStaffNr;
  /**
   * Attribute missing flag for: InStaffOldInstitution
   **/
  public char InStaffOldInstitution_AS;
  /**
   * Attribute for: InStaffOldInstitution
   **/
  public String InStaffOldInstitution;
  /**
   * Attribute missing flag for: InStaffMkRcCode
   **/
  public char InStaffMkRcCode_AS;
  /**
   * Attribute for: InStaffMkRcCode
   **/
  public String InStaffMkRcCode;
  /**
   * Attribute missing flag for: InStaffFirstNames
   **/
  public char InStaffFirstNames_AS;
  /**
   * Attribute for: InStaffFirstNames
   **/
  public String InStaffFirstNames;
  /**
   * Attribute missing flag for: InStaffDateOfBirth
   **/
  public char InStaffDateOfBirth_AS;
  /**
   * Attribute for: InStaffDateOfBirth
   **/
  public int InStaffDateOfBirth;
  /**
   * Attribute missing flag for: InStaffIdNr
   **/
  public char InStaffIdNr_AS;
  /**
   * Attribute for: InStaffIdNr
   **/
  public double InStaffIdNr;
  /**
   * Attribute missing flag for: InStaffPassportNr
   **/
  public char InStaffPassportNr_AS;
  /**
   * Attribute for: InStaffPassportNr
   **/
  public String InStaffPassportNr;
  /**
   * Attribute missing flag for: InStaffTaxNr
   **/
  public char InStaffTaxNr_AS;
  /**
   * Attribute for: InStaffTaxNr
   **/
  public String InStaffTaxNr;
  /**
   * Attribute missing flag for: InStaffTaxDirectiveNr
   **/
  public char InStaffTaxDirectiveNr_AS;
  /**
   * Attribute for: InStaffTaxDirectiveNr
   **/
  public String InStaffTaxDirectiveNr;
  /**
   * Attribute missing flag for: InStaffGender
   **/
  public char InStaffGender_AS;
  /**
   * Attribute for: InStaffGender
   **/
  public String InStaffGender;
  /**
   * Attribute missing flag for: InStaffMkRaceCode
   **/
  public char InStaffMkRaceCode_AS;
  /**
   * Attribute for: InStaffMkRaceCode
   **/
  public String InStaffMkRaceCode;
  /**
   * Attribute missing flag for: InStaffNovellUserId
   **/
  public char InStaffNovellUserId_AS;
  /**
   * Attribute for: InStaffNovellUserId
   **/
  public String InStaffNovellUserId;
  /**
   * Attribute missing flag for: InStaffBuilding
   **/
  public char InStaffBuilding_AS;
  /**
   * Attribute for: InStaffBuilding
   **/
  public String InStaffBuilding;
  /**
   * Attribute missing flag for: InStaffCellNumber
   **/
  public char InStaffCellNumber_AS;
  /**
   * Attribute for: InStaffCellNumber
   **/
  public String InStaffCellNumber;
  /**
   * Default Constructor
   **/
  
  public GISTL01S_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public GISTL01S_IA(GISTL01S_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static GISTL01S_IA getInstance()
  {
    return new GISTL01S_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new GISTL01S_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InStaffPersno_AS = ' ';
    InStaffPersno = 0;
    InStaffSurname_AS = ' ';
    InStaffSurname = "                            ";
    InStaffInitials_AS = ' ';
    InStaffInitials = "          ";
    InStaffTitle_AS = ' ';
    InStaffTitle = "          ";
    InStaffName_AS = ' ';
    InStaffName = "                            ";
    InStaffLanguageCode_AS = ' ';
    InStaffLanguageCode = "  ";
    InStaffMkDeptCode_AS = ' ';
    InStaffMkDeptCode = 0;
    InStaffResignDate_AS = ' ';
    InStaffResignDate = 00000000;
    InStaffEmailAddress_AS = ' ';
    InStaffEmailAddress = 
      "                                                            ";
    InStaffContactTelno_AS = ' ';
    InStaffContactTelno = "                            ";
    InStaffOfficeNo_AS = ' ';
    InStaffOfficeNo = "       ";
    InStaffMkSubdeptCode_AS = ' ';
    InStaffMkSubdeptCode = 0;
    InStaffOldStaffNr_AS = ' ';
    InStaffOldStaffNr = 0;
    InStaffOldInstitution_AS = ' ';
    InStaffOldInstitution = " ";
    InStaffMkRcCode_AS = ' ';
    InStaffMkRcCode = "";
    InStaffFirstNames_AS = ' ';
    InStaffFirstNames = "";
    InStaffDateOfBirth_AS = ' ';
    InStaffDateOfBirth = 00000000;
    InStaffIdNr_AS = ' ';
    InStaffIdNr = 0.0;
    InStaffPassportNr_AS = ' ';
    InStaffPassportNr = "";
    InStaffTaxNr_AS = ' ';
    InStaffTaxNr = "";
    InStaffTaxDirectiveNr_AS = ' ';
    InStaffTaxDirectiveNr = "";
    InStaffGender_AS = ' ';
    InStaffGender = "";
    InStaffMkRaceCode_AS = ' ';
    InStaffMkRaceCode = "";
    InStaffNovellUserId_AS = ' ';
    InStaffNovellUserId = "";
    InStaffBuilding_AS = ' ';
    InStaffBuilding = "";
    InStaffCellNumber_AS = ' ';
    InStaffCellNumber = "";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InStaff", "Staff", "Persno", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)2, "", "InStaff", "Staff", "Surname", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)3, "", "InStaff", "Staff", "Initials", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)4, "", "InStaff", "Staff", "Title", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)5, "", "InStaff", "Staff", "Name", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)6, "", "InStaff", "Staff", "LanguageCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)7, "", "InStaff", "Staff", "MkDeptCode", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)8, "", "InStaff", "Staff", "ResignDate", 
          VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)9, "", "InStaff", "Staff", "EmailAddress", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 60, (short)0, null), 
        new VDFEntry((int)10, "", "InStaff", "Staff", "ContactTelno", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)11, "", "InStaff", "Staff", "OfficeNo", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 7, (short)0, null), 
        new VDFEntry((int)12, "", "InStaff", "Staff", "MkSubdeptCode", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)13, "", "InStaff", "Staff", "OldStaffNr", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)14, "", "InStaff", "Staff", "OldInstitution", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)15, "", "InStaff", "Staff", "MkRcCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 6, (short)0, null), 
        new VDFEntry((int)16, "", "InStaff", "Staff", "FirstNames", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 240, (short)0, null), 
        new VDFEntry((int)17, "", "InStaff", "Staff", "DateOfBirth", 
          VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)18, "", "InStaff", "Staff", "IdNr", 
          VDFEntry.TYPE_DOUBLE, (short)1, (short)0, 13, (short)0, null), 
        new VDFEntry((int)19, "", "InStaff", "Staff", "PassportNr", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 13, (short)0, null), 
        new VDFEntry((int)20, "", "InStaff", "Staff", "TaxNr", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 15, (short)0, null), 
        new VDFEntry((int)21, "", "InStaff", "Staff", "TaxDirectiveNr", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 13, (short)0, null), 
        new VDFEntry((int)22, "", "InStaff", "Staff", "Gender", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)23, "", "InStaff", "Staff", "MkRaceCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 3, (short)0, null), 
        new VDFEntry((int)24, "", "InStaff", "Staff", "NovellUserId", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)25, "", "InStaff", "Staff", "Building", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)26, "", "InStaff", "Staff", "CellNumber", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 20, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(new Integer(InStaffPersno));
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InStaffSurname);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InStaffInitials);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(InStaffTitle);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(InStaffName);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(InStaffLanguageCode);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(new Short(InStaffMkDeptCode));
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(new Integer(InStaffResignDate))
      ;
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(InStaffEmailAddress);
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(InStaffContactTelno);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(InStaffOfficeNo);
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(new Short(
      InStaffMkSubdeptCode));
    // predicate view item
    vdf.getEntries()[12].getDataValue().setObject(new Integer(InStaffOldStaffNr)
      );
    // predicate view item
    vdf.getEntries()[13].getDataValue().setObject(InStaffOldInstitution);
    // predicate view item
    vdf.getEntries()[14].getDataValue().setObject(InStaffMkRcCode);
    // predicate view item
    vdf.getEntries()[15].getDataValue().setObject(InStaffFirstNames);
    // predicate view item
    vdf.getEntries()[16].getDataValue().setObject(new Integer(
      InStaffDateOfBirth));
    // predicate view item
    vdf.getEntries()[17].getDataValue().setObject(new Double(InStaffIdNr));
    // predicate view item
    vdf.getEntries()[18].getDataValue().setObject(InStaffPassportNr);
    // predicate view item
    vdf.getEntries()[19].getDataValue().setObject(InStaffTaxNr);
    // predicate view item
    vdf.getEntries()[20].getDataValue().setObject(InStaffTaxDirectiveNr);
    // predicate view item
    vdf.getEntries()[21].getDataValue().setObject(InStaffGender);
    // predicate view item
    vdf.getEntries()[22].getDataValue().setObject(InStaffMkRaceCode);
    // predicate view item
    vdf.getEntries()[23].getDataValue().setObject(InStaffNovellUserId);
    // predicate view item
    vdf.getEntries()[24].getDataValue().setObject(InStaffBuilding);
    // predicate view item
    vdf.getEntries()[25].getDataValue().setObject(InStaffCellNumber);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InStaffPersno = ((Integer)vdf.getEntries()[0].getDataValue().getObject())
        .intValue();
    }
    else 
    {
      InStaffPersno = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InStaffSurname = ((String)vdf.getEntries()[1].getDataValue().getObject())
        ;
    }
    else 
    {
      InStaffSurname = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InStaffInitials = ((String)vdf.getEntries()[2].getDataValue().getObject())
        ;
    }
    else 
    {
      InStaffInitials = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InStaffTitle = ((String)vdf.getEntries()[3].getDataValue().getObject());
    }
    else 
    {
      InStaffTitle = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      InStaffName = ((String)vdf.getEntries()[4].getDataValue().getObject());
    }
    else 
    {
      InStaffName = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      InStaffLanguageCode = ((String)vdf.getEntries()[5].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffLanguageCode = "  ";
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      InStaffMkDeptCode = ((Short)vdf.getEntries()[6].getDataValue().getObject()
        ).shortValue();
    }
    else 
    {
      InStaffMkDeptCode = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      InStaffResignDate = ((Integer)vdf.getEntries()[7].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InStaffResignDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      InStaffEmailAddress = ((String)vdf.getEntries()[8].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffEmailAddress = 
        "                                                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      InStaffContactTelno = ((String)vdf.getEntries()[9].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffContactTelno = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      InStaffOfficeNo = ((String)vdf.getEntries()[10].getDataValue().getObject()
        );
    }
    else 
    {
      InStaffOfficeNo = "       ";
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      InStaffMkSubdeptCode = ((Short)vdf.getEntries()[11].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      InStaffMkSubdeptCode = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[12].getDataValue().getObject() != null )
    {
      InStaffOldStaffNr = ((Integer)vdf.getEntries()[12].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InStaffOldStaffNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[13].getDataValue().getObject() != null )
    {
      InStaffOldInstitution = ((String)vdf.getEntries()[13].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffOldInstitution = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[14].getDataValue().getObject() != null )
    {
      InStaffMkRcCode = ((String)vdf.getEntries()[14].getDataValue().getObject()
        );
    }
    else 
    {
      InStaffMkRcCode = "";
    }
    // predicate view item
    if ( vdf.getEntries()[15].getDataValue().getObject() != null )
    {
      InStaffFirstNames = ((String)vdf.getEntries()[15].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffFirstNames = "";
    }
    // predicate view item
    if ( vdf.getEntries()[16].getDataValue().getObject() != null )
    {
      InStaffDateOfBirth = ((Integer)vdf.getEntries()[16].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InStaffDateOfBirth = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[17].getDataValue().getObject() != null )
    {
      InStaffIdNr = ((Double)vdf.getEntries()[17].getDataValue().getObject())
        .doubleValue();
    }
    else 
    {
      InStaffIdNr = 0.0;
    }
    // predicate view item
    if ( vdf.getEntries()[18].getDataValue().getObject() != null )
    {
      InStaffPassportNr = ((String)vdf.getEntries()[18].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffPassportNr = "";
    }
    // predicate view item
    if ( vdf.getEntries()[19].getDataValue().getObject() != null )
    {
      InStaffTaxNr = ((String)vdf.getEntries()[19].getDataValue().getObject());
    }
    else 
    {
      InStaffTaxNr = "";
    }
    // predicate view item
    if ( vdf.getEntries()[20].getDataValue().getObject() != null )
    {
      InStaffTaxDirectiveNr = ((String)vdf.getEntries()[20].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffTaxDirectiveNr = "";
    }
    // predicate view item
    if ( vdf.getEntries()[21].getDataValue().getObject() != null )
    {
      InStaffGender = ((String)vdf.getEntries()[21].getDataValue().getObject())
        ;
    }
    else 
    {
      InStaffGender = "";
    }
    // predicate view item
    if ( vdf.getEntries()[22].getDataValue().getObject() != null )
    {
      InStaffMkRaceCode = ((String)vdf.getEntries()[22].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffMkRaceCode = "";
    }
    // predicate view item
    if ( vdf.getEntries()[23].getDataValue().getObject() != null )
    {
      InStaffNovellUserId = ((String)vdf.getEntries()[23].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffNovellUserId = "";
    }
    // predicate view item
    if ( vdf.getEntries()[24].getDataValue().getObject() != null )
    {
      InStaffBuilding = ((String)vdf.getEntries()[24].getDataValue().getObject()
        );
    }
    else 
    {
      InStaffBuilding = "";
    }
    // predicate view item
    if ( vdf.getEntries()[25].getDataValue().getObject() != null )
    {
      InStaffCellNumber = ((String)vdf.getEntries()[25].getDataValue()
        .getObject());
    }
    else 
    {
      InStaffCellNumber = "";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((GISTL01S_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(GISTL01S_IA orig)
  {
    InStaffPersno_AS = orig.InStaffPersno_AS;
    InStaffPersno = orig.InStaffPersno;
    InStaffSurname_AS = orig.InStaffSurname_AS;
    InStaffSurname = orig.InStaffSurname;
    InStaffInitials_AS = orig.InStaffInitials_AS;
    InStaffInitials = orig.InStaffInitials;
    InStaffTitle_AS = orig.InStaffTitle_AS;
    InStaffTitle = orig.InStaffTitle;
    InStaffName_AS = orig.InStaffName_AS;
    InStaffName = orig.InStaffName;
    InStaffLanguageCode_AS = orig.InStaffLanguageCode_AS;
    InStaffLanguageCode = orig.InStaffLanguageCode;
    InStaffMkDeptCode_AS = orig.InStaffMkDeptCode_AS;
    InStaffMkDeptCode = orig.InStaffMkDeptCode;
    InStaffResignDate_AS = orig.InStaffResignDate_AS;
    InStaffResignDate = orig.InStaffResignDate;
    InStaffEmailAddress_AS = orig.InStaffEmailAddress_AS;
    InStaffEmailAddress = orig.InStaffEmailAddress;
    InStaffContactTelno_AS = orig.InStaffContactTelno_AS;
    InStaffContactTelno = orig.InStaffContactTelno;
    InStaffOfficeNo_AS = orig.InStaffOfficeNo_AS;
    InStaffOfficeNo = orig.InStaffOfficeNo;
    InStaffMkSubdeptCode_AS = orig.InStaffMkSubdeptCode_AS;
    InStaffMkSubdeptCode = orig.InStaffMkSubdeptCode;
    InStaffOldStaffNr_AS = orig.InStaffOldStaffNr_AS;
    InStaffOldStaffNr = orig.InStaffOldStaffNr;
    InStaffOldInstitution_AS = orig.InStaffOldInstitution_AS;
    InStaffOldInstitution = orig.InStaffOldInstitution;
    InStaffMkRcCode_AS = orig.InStaffMkRcCode_AS;
    InStaffMkRcCode = orig.InStaffMkRcCode;
    InStaffFirstNames_AS = orig.InStaffFirstNames_AS;
    InStaffFirstNames = orig.InStaffFirstNames;
    InStaffDateOfBirth_AS = orig.InStaffDateOfBirth_AS;
    InStaffDateOfBirth = orig.InStaffDateOfBirth;
    InStaffIdNr_AS = orig.InStaffIdNr_AS;
    InStaffIdNr = orig.InStaffIdNr;
    InStaffPassportNr_AS = orig.InStaffPassportNr_AS;
    InStaffPassportNr = orig.InStaffPassportNr;
    InStaffTaxNr_AS = orig.InStaffTaxNr_AS;
    InStaffTaxNr = orig.InStaffTaxNr;
    InStaffTaxDirectiveNr_AS = orig.InStaffTaxDirectiveNr_AS;
    InStaffTaxDirectiveNr = orig.InStaffTaxDirectiveNr;
    InStaffGender_AS = orig.InStaffGender_AS;
    InStaffGender = orig.InStaffGender;
    InStaffMkRaceCode_AS = orig.InStaffMkRaceCode_AS;
    InStaffMkRaceCode = orig.InStaffMkRaceCode;
    InStaffNovellUserId_AS = orig.InStaffNovellUserId_AS;
    InStaffNovellUserId = orig.InStaffNovellUserId;
    InStaffBuilding_AS = orig.InStaffBuilding_AS;
    InStaffBuilding = orig.InStaffBuilding;
    InStaffCellNumber_AS = orig.InStaffCellNumber_AS;
    InStaffCellNumber = orig.InStaffCellNumber;
  }
}
