package Staae05h;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                            CA Gen r8
//
//           Copyright (c) 2017 CA. All rights reserved.
//
//    Name: STAAE05S_OA                      Date: 2017/08/02
//    User: krugegj                          Time: 16:00:15
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen80.vwrt.*;
import com.ca.gen80.vwrt.types.*;
import com.ca.gen80.vwrt.vdf.*;
import com.ca.gen80.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: STAAE05S_OA
 **/
public class STAAE05S_OA extends ViewBase implements IExportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: OUT
  //        Type: WS_ACADEMIC_YEAR
  /**
   * Attribute missing flag for: OutWsAcademicYearYear
   **/
  public char OutWsAcademicYearYear_AS;
  /**
   * Dynamic attribute for: OutWsAcademicYearYear
   **/
  public DynamicAttr OutWsAcademicYearYear_AT;
  /**
   * Attribute for: OutWsAcademicYearYear
   **/
  public short OutWsAcademicYearYear;
  // Entity View: OUT
  //        Type: WS_QUALIFICATION
  /**
   * Attribute missing flag for: OutWsQualificationCode
   **/
  public char OutWsQualificationCode_AS;
  /**
   * Dynamic attribute for: OutWsQualificationCode
   **/
  public DynamicAttr OutWsQualificationCode_AT;
  /**
   * Attribute for: OutWsQualificationCode
   **/
  public String OutWsQualificationCode;
  /**
   * Attribute missing flag for: OutWsQualificationType
   **/
  public char OutWsQualificationType_AS;
  /**
   * Dynamic attribute for: OutWsQualificationType
   **/
  public DynamicAttr OutWsQualificationType_AT;
  /**
   * Attribute for: OutWsQualificationType
   **/
  public String OutWsQualificationType;
  // Entity View: OUT
  //        Type: WS_QUALIFICATION_SPECIALITY_TYPE
  /**
   * Attribute missing flag for: 
    OutWsQualificationSpecialityTypeMkQualificationCode
   **/
  public char OutWsQualificationSpecialityTypeMkQualificationCode_AS;
  /**
   * Dynamic attribute for: OutWsQualificationSpecialityTypeMkQualificationCode
   **/
  public DynamicAttr OutWsQualificationSpecialityTypeMkQualificationCode_AT;
  /**
   * Attribute for: OutWsQualificationSpecialityTypeMkQualificationCode
   **/
  public String OutWsQualificationSpecialityTypeMkQualificationCode;
  /**
   * Attribute missing flag for: OutWsQualificationSpecialityTypeSpecialityCode
   **/
  public char OutWsQualificationSpecialityTypeSpecialityCode_AS;
  /**
   * Dynamic attribute for: OutWsQualificationSpecialityTypeSpecialityCode
   **/
  public DynamicAttr OutWsQualificationSpecialityTypeSpecialityCode_AT;
  /**
   * Attribute for: OutWsQualificationSpecialityTypeSpecialityCode
   **/
  public String OutWsQualificationSpecialityTypeSpecialityCode;
  // Entity View: OUT
  //        Type: WS_STUDENT
  /**
   * Attribute missing flag for: OutWsStudentNr
   **/
  public char OutWsStudentNr_AS;
  /**
   * Dynamic attribute for: OutWsStudentNr
   **/
  public DynamicAttr OutWsStudentNr_AT;
  /**
   * Attribute for: OutWsStudentNr
   **/
  public int OutWsStudentNr;
  /**
   * Attribute missing flag for: OutWsStudentMkTitle
   **/
  public char OutWsStudentMkTitle_AS;
  /**
   * Dynamic attribute for: OutWsStudentMkTitle
   **/
  public DynamicAttr OutWsStudentMkTitle_AT;
  /**
   * Attribute for: OutWsStudentMkTitle
   **/
  public String OutWsStudentMkTitle;
  /**
   * Attribute missing flag for: OutWsStudentSurname
   **/
  public char OutWsStudentSurname_AS;
  /**
   * Dynamic attribute for: OutWsStudentSurname
   **/
  public DynamicAttr OutWsStudentSurname_AT;
  /**
   * Attribute for: OutWsStudentSurname
   **/
  public String OutWsStudentSurname;
  /**
   * Attribute missing flag for: OutWsStudentInitials
   **/
  public char OutWsStudentInitials_AS;
  /**
   * Dynamic attribute for: OutWsStudentInitials
   **/
  public DynamicAttr OutWsStudentInitials_AT;
  /**
   * Attribute for: OutWsStudentInitials
   **/
  public String OutWsStudentInitials;
  /**
   * Attribute missing flag for: OutWsStudentIdentityNr
   **/
  public char OutWsStudentIdentityNr_AS;
  /**
   * Dynamic attribute for: OutWsStudentIdentityNr
   **/
  public DynamicAttr OutWsStudentIdentityNr_AT;
  /**
   * Attribute for: OutWsStudentIdentityNr
   **/
  public String OutWsStudentIdentityNr;
  /**
   * Attribute missing flag for: OutWsStudentBirthDate
   **/
  public char OutWsStudentBirthDate_AS;
  /**
   * Dynamic attribute for: OutWsStudentBirthDate
   **/
  public DynamicAttr OutWsStudentBirthDate_AT;
  /**
   * Attribute for: OutWsStudentBirthDate
   **/
  public int OutWsStudentBirthDate;
  /**
   * Attribute missing flag for: OutWsStudentMkNationality
   **/
  public char OutWsStudentMkNationality_AS;
  /**
   * Dynamic attribute for: OutWsStudentMkNationality
   **/
  public DynamicAttr OutWsStudentMkNationality_AT;
  /**
   * Attribute for: OutWsStudentMkNationality
   **/
  public String OutWsStudentMkNationality;
  /**
   * Attribute missing flag for: OutWsStudentMkLastAcademicYear
   **/
  public char OutWsStudentMkLastAcademicYear_AS;
  /**
   * Dynamic attribute for: OutWsStudentMkLastAcademicYear
   **/
  public DynamicAttr OutWsStudentMkLastAcademicYear_AT;
  /**
   * Attribute for: OutWsStudentMkLastAcademicYear
   **/
  public short OutWsStudentMkLastAcademicYear;
  /**
   * Attribute missing flag for: OutWsStudentMkCountryCode
   **/
  public char OutWsStudentMkCountryCode_AS;
  /**
   * Dynamic attribute for: OutWsStudentMkCountryCode
   **/
  public DynamicAttr OutWsStudentMkCountryCode_AT;
  /**
   * Attribute for: OutWsStudentMkCountryCode
   **/
  public String OutWsStudentMkCountryCode;
  // Entity View: OUT
  //        Type: WS_MATRIC_STATUS
  /**
   * Attribute missing flag for: OutWsMatricStatusCode
   **/
  public char OutWsMatricStatusCode_AS;
  /**
   * Dynamic attribute for: OutWsMatricStatusCode
   **/
  public DynamicAttr OutWsMatricStatusCode_AT;
  /**
   * Attribute for: OutWsMatricStatusCode
   **/
  public String OutWsMatricStatusCode;
  // Entity View: OUT
  //        Type: WS_MATRIC_CERTIFICATE
  /**
   * Attribute missing flag for: OutWsMatricCertificateCode
   **/
  public char OutWsMatricCertificateCode_AS;
  /**
   * Dynamic attribute for: OutWsMatricCertificateCode
   **/
  public DynamicAttr OutWsMatricCertificateCode_AT;
  /**
   * Attribute for: OutWsMatricCertificateCode
   **/
  public String OutWsMatricCertificateCode;
  // Entity View: OUT
  //        Type: WS_MATRIC_RECORD
  /**
   * Attribute missing flag for: OutWsMatricRecordCategory
   **/
  public char OutWsMatricRecordCategory_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordCategory
   **/
  public DynamicAttr OutWsMatricRecordCategory_AT;
  /**
   * Attribute for: OutWsMatricRecordCategory
   **/
  public short OutWsMatricRecordCategory;
  /**
   * Attribute missing flag for: OutWsMatricRecordFullExemptionDate
   **/
  public char OutWsMatricRecordFullExemptionDate_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordFullExemptionDate
   **/
  public DynamicAttr OutWsMatricRecordFullExemptionDate_AT;
  /**
   * Attribute for: OutWsMatricRecordFullExemptionDate
   **/
  public int OutWsMatricRecordFullExemptionDate;
  /**
   * Attribute missing flag for: OutWsMatricRecordExemptionEffectiveDate
   **/
  public char OutWsMatricRecordExemptionEffectiveDate_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordExemptionEffectiveDate
   **/
  public DynamicAttr OutWsMatricRecordExemptionEffectiveDate_AT;
  /**
   * Attribute for: OutWsMatricRecordExemptionEffectiveDate
   **/
  public int OutWsMatricRecordExemptionEffectiveDate;
  /**
   * Attribute missing flag for: OutWsMatricRecordExemptionExpiryDate
   **/
  public char OutWsMatricRecordExemptionExpiryDate_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordExemptionExpiryDate
   **/
  public DynamicAttr OutWsMatricRecordExemptionExpiryDate_AT;
  /**
   * Attribute for: OutWsMatricRecordExemptionExpiryDate
   **/
  public int OutWsMatricRecordExemptionExpiryDate;
  /**
   * Attribute missing flag for: OutWsMatricRecordAuditedFlag
   **/
  public char OutWsMatricRecordAuditedFlag_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordAuditedFlag
   **/
  public DynamicAttr OutWsMatricRecordAuditedFlag_AT;
  /**
   * Attribute for: OutWsMatricRecordAuditedFlag
   **/
  public String OutWsMatricRecordAuditedFlag;
  /**
   * Attribute missing flag for: OutWsMatricRecordSymbol
   **/
  public char OutWsMatricRecordSymbol_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordSymbol
   **/
  public DynamicAttr OutWsMatricRecordSymbol_AT;
  /**
   * Attribute for: OutWsMatricRecordSymbol
   **/
  public String OutWsMatricRecordSymbol;
  /**
   * Attribute missing flag for: OutWsMatricRecordOrigExemptDate
   **/
  public char OutWsMatricRecordOrigExemptDate_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordOrigExemptDate
   **/
  public DynamicAttr OutWsMatricRecordOrigExemptDate_AT;
  /**
   * Attribute for: OutWsMatricRecordOrigExemptDate
   **/
  public int OutWsMatricRecordOrigExemptDate;
  /**
   * Attribute missing flag for: OutWsMatricRecordHcerCompleted
   **/
  public char OutWsMatricRecordHcerCompleted_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordHcerCompleted
   **/
  public DynamicAttr OutWsMatricRecordHcerCompleted_AT;
  /**
   * Attribute for: OutWsMatricRecordHcerCompleted
   **/
  public String OutWsMatricRecordHcerCompleted;
  /**
   * Attribute missing flag for: OutWsMatricRecordDiplCompleted
   **/
  public char OutWsMatricRecordDiplCompleted_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordDiplCompleted
   **/
  public DynamicAttr OutWsMatricRecordDiplCompleted_AT;
  /**
   * Attribute for: OutWsMatricRecordDiplCompleted
   **/
  public String OutWsMatricRecordDiplCompleted;
  /**
   * Attribute missing flag for: OutWsMatricRecordApsScore
   **/
  public char OutWsMatricRecordApsScore_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordApsScore
   **/
  public DynamicAttr OutWsMatricRecordApsScore_AT;
  /**
   * Attribute for: OutWsMatricRecordApsScore
   **/
  public short OutWsMatricRecordApsScore;
  /**
   * Attribute missing flag for: OutWsMatricRecordAcsScore
   **/
  public char OutWsMatricRecordAcsScore_AS;
  /**
   * Dynamic attribute for: OutWsMatricRecordAcsScore
   **/
  public DynamicAttr OutWsMatricRecordAcsScore_AT;
  /**
   * Attribute for: OutWsMatricRecordAcsScore
   **/
  public short OutWsMatricRecordAcsScore;
  // Repeating GV:  OUT_GROUP
  //     Repeats: 350 times
  /**
   * Repeating group view count
   **/
  public int OutGroup_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char OutGroup_AC[] = new char[350];
  // Entity View: OUT_G
  //        Type: CSF_LINE_ACTION_BAR
  /**
   * Attribute missing flag for: OutGCsfLineActionBarSelectionFlag
   **/
  public char OutGCsfLineActionBarSelectionFlag_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGCsfLineActionBarSelectionFlag
   **/
  public DynamicAttr OutGCsfLineActionBarSelectionFlag_AT[] = new DynamicAttr[
    350];
  /**
   * Attribute for: OutGCsfLineActionBarSelectionFlag
   **/
  public String OutGCsfLineActionBarSelectionFlag[] = new String[350];
  // Entity View: OUT_G
  //        Type: WS_QUALIFICATION
  /**
   * Attribute missing flag for: OutGWsQualificationCode
   **/
  public char OutGWsQualificationCode_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGWsQualificationCode
   **/
  public DynamicAttr OutGWsQualificationCode_AT[] = new DynamicAttr[350];
  /**
   * Attribute for: OutGWsQualificationCode
   **/
  public String OutGWsQualificationCode[] = new String[350];
  /**
   * Attribute missing flag for: OutGWsQualificationType
   **/
  public char OutGWsQualificationType_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGWsQualificationType
   **/
  public DynamicAttr OutGWsQualificationType_AT[] = new DynamicAttr[350];
  /**
   * Attribute for: OutGWsQualificationType
   **/
  public String OutGWsQualificationType[] = new String[350];
  /**
   * Attribute missing flag for: OutGWsQualificationCollegeCode
   **/
  public char OutGWsQualificationCollegeCode_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGWsQualificationCollegeCode
   **/
  public DynamicAttr OutGWsQualificationCollegeCode_AT[] = new DynamicAttr[350]
    ;
  /**
   * Attribute for: OutGWsQualificationCollegeCode
   **/
  public short OutGWsQualificationCollegeCode[] = new short[350];
  // Entity View: OUT_G
  //        Type: WS_QUALIFICATION_SPECIALITY_TYPE
  /**
   * Attribute missing flag for: 
    OutGWsQualificationSpecialityTypeSpecialityCode
   **/
  public char OutGWsQualificationSpecialityTypeSpecialityCode_AS[] = new char[
    350];
  /**
   * Dynamic attribute for: OutGWsQualificationSpecialityTypeSpecialityCode
   **/
  public DynamicAttr OutGWsQualificationSpecialityTypeSpecialityCode_AT[] = new 
    DynamicAttr[350];
  /**
   * Attribute for: OutGWsQualificationSpecialityTypeSpecialityCode
   **/
  public String OutGWsQualificationSpecialityTypeSpecialityCode[] = new String[
    350];
  // Entity View: OUT_G
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: OutGCsfStringsString2
   **/
  public char OutGCsfStringsString2_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGCsfStringsString2
   **/
  public DynamicAttr OutGCsfStringsString2_AT[] = new DynamicAttr[350];
  /**
   * Attribute for: OutGCsfStringsString2
   **/
  public String OutGCsfStringsString2[] = new String[350];
  /**
   * Attribute missing flag for: OutGCsfStringsString3
   **/
  public char OutGCsfStringsString3_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGCsfStringsString3
   **/
  public DynamicAttr OutGCsfStringsString3_AT[] = new DynamicAttr[350];
  /**
   * Attribute for: OutGCsfStringsString3
   **/
  public String OutGCsfStringsString3[] = new String[350];
  /**
   * Attribute missing flag for: OutGCsfStringsString4
   **/
  public char OutGCsfStringsString4_AS[] = new char[350];
  /**
   * Dynamic attribute for: OutGCsfStringsString4
   **/
  public DynamicAttr OutGCsfStringsString4_AT[] = new DynamicAttr[350];
  /**
   * Attribute for: OutGCsfStringsString4
   **/
  public String OutGCsfStringsString4[] = new String[350];
  // Repeating GV:  OUT_GROUP_MATRIC
  //     Repeats: 15 times
  /**
   * Repeating group view count
   **/
  public int OutGroupMatric_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char OutGroupMatric_AC[] = new char[15];
  // Entity View: OUT_GM
  //        Type: CSF_LINE_ACTION_BAR
  /**
   * Attribute missing flag for: OutGmCsfLineActionBarSelectionFlag
   **/
  public char OutGmCsfLineActionBarSelectionFlag_AS[] = new char[15];
  /**
   * Dynamic attribute for: OutGmCsfLineActionBarSelectionFlag
   **/
  public DynamicAttr OutGmCsfLineActionBarSelectionFlag_AT[] = new DynamicAttr[
    15];
  /**
   * Attribute for: OutGmCsfLineActionBarSelectionFlag
   **/
  public String OutGmCsfLineActionBarSelectionFlag[] = new String[15];
  // Entity View: OUT_GM
  //        Type: WS_MATRIC_SUBJECT
  /**
   * Attribute missing flag for: OutGmWsMatricSubjectCode
   **/
  public char OutGmWsMatricSubjectCode_AS[] = new char[15];
  /**
   * Dynamic attribute for: OutGmWsMatricSubjectCode
   **/
  public DynamicAttr OutGmWsMatricSubjectCode_AT[] = new DynamicAttr[15];
  /**
   * Attribute for: OutGmWsMatricSubjectCode
   **/
  public String OutGmWsMatricSubjectCode[] = new String[15];
  // Entity View: OUT_GM
  //        Type: WS_MATRIC_SUBJECT_RESULT
  /**
   * Attribute missing flag for: OutGmWsMatricSubjectResultGrade
   **/
  public char OutGmWsMatricSubjectResultGrade_AS[] = new char[15];
  /**
   * Dynamic attribute for: OutGmWsMatricSubjectResultGrade
   **/
  public DynamicAttr OutGmWsMatricSubjectResultGrade_AT[] = new DynamicAttr[15]
    ;
  /**
   * Attribute for: OutGmWsMatricSubjectResultGrade
   **/
  public String OutGmWsMatricSubjectResultGrade[] = new String[15];
  /**
   * Attribute missing flag for: OutGmWsMatricSubjectResultMark
   **/
  public char OutGmWsMatricSubjectResultMark_AS[] = new char[15];
  /**
   * Dynamic attribute for: OutGmWsMatricSubjectResultMark
   **/
  public DynamicAttr OutGmWsMatricSubjectResultMark_AT[] = new DynamicAttr[15];
  /**
   * Attribute for: OutGmWsMatricSubjectResultMark
   **/
  public short OutGmWsMatricSubjectResultMark[] = new short[15];
  // Entity View: OUT
  //        Type: WS_USER
  /**
   * Attribute missing flag for: OutWsUserNumber
   **/
  public char OutWsUserNumber_AS;
  /**
   * Dynamic attribute for: OutWsUserNumber
   **/
  public DynamicAttr OutWsUserNumber_AT;
  /**
   * Attribute for: OutWsUserNumber
   **/
  public int OutWsUserNumber;
  // Entity View: OUT
  //        Type: CSF_CLIENT_SERVER_COMMUNICATIONS
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsReturnCode
   **/
  public char OutCsfClientServerCommunicationsReturnCode_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsReturnCode
   **/
  public DynamicAttr OutCsfClientServerCommunicationsReturnCode_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsReturnCode
   **/
  public short OutCsfClientServerCommunicationsReturnCode;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerVersionNumber
   **/
  public char OutCsfClientServerCommunicationsServerVersionNumber_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerVersionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerVersionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerVersionNumber
   **/
  public short OutCsfClientServerCommunicationsServerVersionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerRevisionNumber
   **/
  public char OutCsfClientServerCommunicationsServerRevisionNumber_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsServerRevisionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerRevisionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerRevisionNumber
   **/
  public short OutCsfClientServerCommunicationsServerRevisionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerDevelopmentPhase
   **/
  public char OutCsfClientServerCommunicationsServerDevelopmentPhase_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsServerDevelopmentPhase
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerDevelopmentPhase_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerDevelopmentPhase
   **/
  public String OutCsfClientServerCommunicationsServerDevelopmentPhase;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsAction
   **/
  public char OutCsfClientServerCommunicationsAction_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsAction
   **/
  public DynamicAttr OutCsfClientServerCommunicationsAction_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsAction
   **/
  public String OutCsfClientServerCommunicationsAction;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public char OutCsfClientServerCommunicationsClientIsGuiFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientIsGuiFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public String OutCsfClientServerCommunicationsClientIsGuiFlag;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsServerDate
   **/
  public char OutCsfClientServerCommunicationsServerDate_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerDate
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerDate_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerDate
   **/
  public int OutCsfClientServerCommunicationsServerDate;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsServerTime
   **/
  public char OutCsfClientServerCommunicationsServerTime_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerTime
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerTime_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerTime
   **/
  public int OutCsfClientServerCommunicationsServerTime;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerTimestamp
   **/
  public char OutCsfClientServerCommunicationsServerTimestamp_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerTimestamp
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerTimestamp_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerTimestamp
   **/
  public String OutCsfClientServerCommunicationsServerTimestamp;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerTransactionCode
   **/
  public char OutCsfClientServerCommunicationsServerTransactionCode_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsServerTransactionCode
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerTransactionCode_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerTransactionCode
   **/
  public String OutCsfClientServerCommunicationsServerTransactionCode;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsServerUserId
   **/
  public char OutCsfClientServerCommunicationsServerUserId_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerUserId
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerUserId_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerUserId
   **/
  public String OutCsfClientServerCommunicationsServerUserId;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerRollbackFlag
   **/
  public char OutCsfClientServerCommunicationsServerRollbackFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerRollbackFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerRollbackFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerRollbackFlag
   **/
  public String OutCsfClientServerCommunicationsServerRollbackFlag;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsActionsPendingFlag
   **/
  public char OutCsfClientServerCommunicationsActionsPendingFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsActionsPendingFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsActionsPendingFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsActionsPendingFlag
   **/
  public String OutCsfClientServerCommunicationsActionsPendingFlag;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientVersionNumber
   **/
  public char OutCsfClientServerCommunicationsClientVersionNumber_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsClientVersionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientVersionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientVersionNumber
   **/
  public short OutCsfClientServerCommunicationsClientVersionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientRevisionNumber
   **/
  public char OutCsfClientServerCommunicationsClientRevisionNumber_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsClientRevisionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientRevisionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientRevisionNumber
   **/
  public short OutCsfClientServerCommunicationsClientRevisionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public char OutCsfClientServerCommunicationsClientDevelopmentPhase_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientDevelopmentPhase_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public String OutCsfClientServerCommunicationsClientDevelopmentPhase;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsListLinkFlag
   **/
  public char OutCsfClientServerCommunicationsListLinkFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsListLinkFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsListLinkFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsListLinkFlag
   **/
  public String OutCsfClientServerCommunicationsListLinkFlag;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsCancelFlag
   **/
  public char OutCsfClientServerCommunicationsCancelFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsCancelFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsCancelFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsCancelFlag
   **/
  public String OutCsfClientServerCommunicationsCancelFlag;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsMaintLinkFlag
   **/
  public char OutCsfClientServerCommunicationsMaintLinkFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsMaintLinkFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsMaintLinkFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsMaintLinkFlag
   **/
  public String OutCsfClientServerCommunicationsMaintLinkFlag;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsForceDatabaseRead
   **/
  public char OutCsfClientServerCommunicationsForceDatabaseRead_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsForceDatabaseRead
   **/
  public DynamicAttr OutCsfClientServerCommunicationsForceDatabaseRead_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsForceDatabaseRead
   **/
  public String OutCsfClientServerCommunicationsForceDatabaseRead;
  // Entity View: OUT
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: OutCsfStringsString500
   **/
  public char OutCsfStringsString500_AS;
  /**
   * Dynamic attribute for: OutCsfStringsString500
   **/
  public DynamicAttr OutCsfStringsString500_AT;
  /**
   * Attribute for: OutCsfStringsString500
   **/
  public String OutCsfStringsString500;
  /**
   * Default Constructor
   **/
  
  public STAAE05S_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public STAAE05S_OA(STAAE05S_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static STAAE05S_OA getInstance()
  {
    return new STAAE05S_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new STAAE05S_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    OutWsAcademicYearYear_AT = null;
    OutWsAcademicYearYear_AS = ' ';
    OutWsAcademicYearYear = 0;
    OutWsQualificationCode_AT = null;
    OutWsQualificationCode_AS = ' ';
    OutWsQualificationCode = "     ";
    OutWsQualificationType_AT = null;
    OutWsQualificationType_AS = ' ';
    OutWsQualificationType = " ";
    OutWsQualificationSpecialityTypeMkQualificationCode_AT = null;
    OutWsQualificationSpecialityTypeMkQualificationCode_AS = ' ';
    OutWsQualificationSpecialityTypeMkQualificationCode = "     ";
    OutWsQualificationSpecialityTypeSpecialityCode_AT = null;
    OutWsQualificationSpecialityTypeSpecialityCode_AS = ' ';
    OutWsQualificationSpecialityTypeSpecialityCode = "   ";
    OutWsStudentNr_AT = null;
    OutWsStudentNr_AS = ' ';
    OutWsStudentNr = 0;
    OutWsStudentMkTitle_AT = null;
    OutWsStudentMkTitle_AS = ' ';
    OutWsStudentMkTitle = "          ";
    OutWsStudentSurname_AT = null;
    OutWsStudentSurname_AS = ' ';
    OutWsStudentSurname = "                            ";
    OutWsStudentInitials_AT = null;
    OutWsStudentInitials_AS = ' ';
    OutWsStudentInitials = "          ";
    OutWsStudentIdentityNr_AT = null;
    OutWsStudentIdentityNr_AS = ' ';
    OutWsStudentIdentityNr = "             ";
    OutWsStudentBirthDate_AT = null;
    OutWsStudentBirthDate_AS = ' ';
    OutWsStudentBirthDate = 00000000;
    OutWsStudentMkNationality_AT = null;
    OutWsStudentMkNationality_AS = ' ';
    OutWsStudentMkNationality = "    ";
    OutWsStudentMkLastAcademicYear_AT = null;
    OutWsStudentMkLastAcademicYear_AS = ' ';
    OutWsStudentMkLastAcademicYear = 0;
    OutWsStudentMkCountryCode_AT = null;
    OutWsStudentMkCountryCode_AS = ' ';
    OutWsStudentMkCountryCode = "    ";
    OutWsMatricStatusCode_AT = null;
    OutWsMatricStatusCode_AS = ' ';
    OutWsMatricStatusCode = "    ";
    OutWsMatricCertificateCode_AT = null;
    OutWsMatricCertificateCode_AS = ' ';
    OutWsMatricCertificateCode = "   ";
    OutWsMatricRecordCategory_AT = null;
    OutWsMatricRecordCategory_AS = ' ';
    OutWsMatricRecordCategory = 0;
    OutWsMatricRecordFullExemptionDate_AT = null;
    OutWsMatricRecordFullExemptionDate_AS = ' ';
    OutWsMatricRecordFullExemptionDate = 00000000;
    OutWsMatricRecordExemptionEffectiveDate_AT = null;
    OutWsMatricRecordExemptionEffectiveDate_AS = ' ';
    OutWsMatricRecordExemptionEffectiveDate = 00000000;
    OutWsMatricRecordExemptionExpiryDate_AT = null;
    OutWsMatricRecordExemptionExpiryDate_AS = ' ';
    OutWsMatricRecordExemptionExpiryDate = 00000000;
    OutWsMatricRecordAuditedFlag_AT = null;
    OutWsMatricRecordAuditedFlag_AS = ' ';
    OutWsMatricRecordAuditedFlag = " ";
    OutWsMatricRecordSymbol_AT = null;
    OutWsMatricRecordSymbol_AS = ' ';
    OutWsMatricRecordSymbol = "   ";
    OutWsMatricRecordOrigExemptDate_AT = null;
    OutWsMatricRecordOrigExemptDate_AS = ' ';
    OutWsMatricRecordOrigExemptDate = 00000000;
    OutWsMatricRecordHcerCompleted_AT = null;
    OutWsMatricRecordHcerCompleted_AS = ' ';
    OutWsMatricRecordHcerCompleted = " ";
    OutWsMatricRecordDiplCompleted_AT = null;
    OutWsMatricRecordDiplCompleted_AS = ' ';
    OutWsMatricRecordDiplCompleted = " ";
    OutWsMatricRecordApsScore_AT = null;
    OutWsMatricRecordApsScore_AS = ' ';
    OutWsMatricRecordApsScore = 0;
    OutWsMatricRecordAcsScore_AT = null;
    OutWsMatricRecordAcsScore_AS = ' ';
    OutWsMatricRecordAcsScore = 0;
    OutGroup_MA = 0;
    for(int a = 0; a < 350; a++)
    {
      OutGroup_AC[a] = ' ';
      OutGCsfLineActionBarSelectionFlag_AT[a] = null;
      OutGCsfLineActionBarSelectionFlag_AS[a] = ' ';
      OutGCsfLineActionBarSelectionFlag[a] = " ";
      OutGWsQualificationCode_AT[a] = null;
      OutGWsQualificationCode_AS[a] = ' ';
      OutGWsQualificationCode[a] = "     ";
      OutGWsQualificationType_AT[a] = null;
      OutGWsQualificationType_AS[a] = ' ';
      OutGWsQualificationType[a] = " ";
      OutGWsQualificationCollegeCode_AT[a] = null;
      OutGWsQualificationCollegeCode_AS[a] = ' ';
      OutGWsQualificationCollegeCode[a] = 0;
      OutGWsQualificationSpecialityTypeSpecialityCode_AT[a] = null;
      OutGWsQualificationSpecialityTypeSpecialityCode_AS[a] = ' ';
      OutGWsQualificationSpecialityTypeSpecialityCode[a] = "   ";
      OutGCsfStringsString2_AT[a] = null;
      OutGCsfStringsString2_AS[a] = ' ';
      OutGCsfStringsString2[a] = "  ";
      OutGCsfStringsString3_AT[a] = null;
      OutGCsfStringsString3_AS[a] = ' ';
      OutGCsfStringsString3[a] = "   ";
      OutGCsfStringsString4_AT[a] = null;
      OutGCsfStringsString4_AS[a] = ' ';
      OutGCsfStringsString4[a] = "    ";
    }
    OutGroupMatric_MA = 0;
    for(int a = 0; a < 15; a++)
    {
      OutGroupMatric_AC[a] = ' ';
      OutGmCsfLineActionBarSelectionFlag_AT[a] = null;
      OutGmCsfLineActionBarSelectionFlag_AS[a] = ' ';
      OutGmCsfLineActionBarSelectionFlag[a] = " ";
      OutGmWsMatricSubjectCode_AT[a] = null;
      OutGmWsMatricSubjectCode_AS[a] = ' ';
      OutGmWsMatricSubjectCode[a] = "   ";
      OutGmWsMatricSubjectResultGrade_AT[a] = null;
      OutGmWsMatricSubjectResultGrade_AS[a] = ' ';
      OutGmWsMatricSubjectResultGrade[a] = " ";
      OutGmWsMatricSubjectResultMark_AT[a] = null;
      OutGmWsMatricSubjectResultMark_AS[a] = ' ';
      OutGmWsMatricSubjectResultMark[a] = 0;
    }
    OutWsUserNumber_AT = null;
    OutWsUserNumber_AS = ' ';
    OutWsUserNumber = 0;
    OutCsfClientServerCommunicationsReturnCode_AT = null;
    OutCsfClientServerCommunicationsReturnCode_AS = ' ';
    OutCsfClientServerCommunicationsReturnCode = 0;
    OutCsfClientServerCommunicationsServerVersionNumber_AT = null;
    OutCsfClientServerCommunicationsServerVersionNumber_AS = ' ';
    OutCsfClientServerCommunicationsServerVersionNumber = 0;
    OutCsfClientServerCommunicationsServerRevisionNumber_AT = null;
    OutCsfClientServerCommunicationsServerRevisionNumber_AS = ' ';
    OutCsfClientServerCommunicationsServerRevisionNumber = 0;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AT = null;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AS = ' ';
    OutCsfClientServerCommunicationsServerDevelopmentPhase = " ";
    OutCsfClientServerCommunicationsAction_AT = null;
    OutCsfClientServerCommunicationsAction_AS = ' ';
    OutCsfClientServerCommunicationsAction = "  ";
    OutCsfClientServerCommunicationsClientIsGuiFlag_AT = null;
    OutCsfClientServerCommunicationsClientIsGuiFlag_AS = ' ';
    OutCsfClientServerCommunicationsClientIsGuiFlag = " ";
    OutCsfClientServerCommunicationsServerDate_AT = null;
    OutCsfClientServerCommunicationsServerDate_AS = ' ';
    OutCsfClientServerCommunicationsServerDate = 00000000;
    OutCsfClientServerCommunicationsServerTime_AT = null;
    OutCsfClientServerCommunicationsServerTime_AS = ' ';
    OutCsfClientServerCommunicationsServerTime = 00000000;
    OutCsfClientServerCommunicationsServerTimestamp_AT = null;
    OutCsfClientServerCommunicationsServerTimestamp_AS = ' ';
    OutCsfClientServerCommunicationsServerTimestamp = "00000000000000000000";
    OutCsfClientServerCommunicationsServerTransactionCode_AT = null;
    OutCsfClientServerCommunicationsServerTransactionCode_AS = ' ';
    OutCsfClientServerCommunicationsServerTransactionCode = "        ";
    OutCsfClientServerCommunicationsServerUserId_AT = null;
    OutCsfClientServerCommunicationsServerUserId_AS = ' ';
    OutCsfClientServerCommunicationsServerUserId = "        ";
    OutCsfClientServerCommunicationsServerRollbackFlag_AT = null;
    OutCsfClientServerCommunicationsServerRollbackFlag_AS = ' ';
    OutCsfClientServerCommunicationsServerRollbackFlag = " ";
    OutCsfClientServerCommunicationsActionsPendingFlag_AT = null;
    OutCsfClientServerCommunicationsActionsPendingFlag_AS = ' ';
    OutCsfClientServerCommunicationsActionsPendingFlag = " ";
    OutCsfClientServerCommunicationsClientVersionNumber_AT = null;
    OutCsfClientServerCommunicationsClientVersionNumber_AS = ' ';
    OutCsfClientServerCommunicationsClientVersionNumber = 0;
    OutCsfClientServerCommunicationsClientRevisionNumber_AT = null;
    OutCsfClientServerCommunicationsClientRevisionNumber_AS = ' ';
    OutCsfClientServerCommunicationsClientRevisionNumber = 0;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AT = null;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AS = ' ';
    OutCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    OutCsfClientServerCommunicationsListLinkFlag_AT = null;
    OutCsfClientServerCommunicationsListLinkFlag_AS = ' ';
    OutCsfClientServerCommunicationsListLinkFlag = " ";
    OutCsfClientServerCommunicationsCancelFlag_AT = null;
    OutCsfClientServerCommunicationsCancelFlag_AS = ' ';
    OutCsfClientServerCommunicationsCancelFlag = " ";
    OutCsfClientServerCommunicationsMaintLinkFlag_AT = null;
    OutCsfClientServerCommunicationsMaintLinkFlag_AS = ' ';
    OutCsfClientServerCommunicationsMaintLinkFlag = " ";
    OutCsfClientServerCommunicationsForceDatabaseRead_AT = null;
    OutCsfClientServerCommunicationsForceDatabaseRead_AS = ' ';
    OutCsfClientServerCommunicationsForceDatabaseRead = " ";
    OutCsfStringsString500_AT = null;
    OutCsfStringsString500_AS = ' ';
    OutCsfStringsString500 = "";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "OutWsAcademicYear", "WsAcademicYear", "Year", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)2, "", "OutWsQualification", "WsQualification", "Code"
          , VDFEntry.TYPE_STRING, (short)1, (short)0, 5, (short)0, null), 
        new VDFEntry((int)3, "", "OutWsQualification", "WsQualification", "Type"
          , VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)4, "", "OutWsQualificationSpecialityType", 
          "WsQualificationSpecialityType", "MkQualificationCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 5, (short)0, null), 
        new VDFEntry((int)5, "", "OutWsQualificationSpecialityType", 
          "WsQualificationSpecialityType", "SpecialityCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 3, (short)0, null), 
        new VDFEntry((int)6, "", "OutWsStudent", "WsStudent", "Nr", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)7, "", "OutWsStudent", "WsStudent", "MkTitle", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)8, "", "OutWsStudent", "WsStudent", "Surname", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)9, "", "OutWsStudent", "WsStudent", "Initials", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)10, "", "OutWsStudent", "WsStudent", "IdentityNr", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 13, (short)0, null), 
        new VDFEntry((int)11, "", "OutWsStudent", "WsStudent", "BirthDate", 
          VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)12, "", "OutWsStudent", "WsStudent", "MkNationality", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)13, "", "OutWsStudent", "WsStudent", 
          "MkLastAcademicYear", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (
          short)0, null), 
        new VDFEntry((int)14, "", "OutWsStudent", "WsStudent", "MkCountryCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)15, "", "OutWsMatricStatus", "WsMatricStatus", "Code",
           VDFEntry.TYPE_STRING, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)16, "", "OutWsMatricCertificate", 
          "WsMatricCertificate", "Code", VDFEntry.TYPE_STRING, (short)1, (short)
          0, 3, (short)0, null), 
        new VDFEntry((int)17, "", "OutWsMatricRecord", "WsMatricRecord", 
          "Category", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, 
          null), 
        new VDFEntry((int)18, "", "OutWsMatricRecord", "WsMatricRecord", 
          "FullExemptionDate", VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (
          short)0, null), 
        new VDFEntry((int)19, "", "OutWsMatricRecord", "WsMatricRecord", 
          "ExemptionEffectiveDate", VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (
          short)0, null), 
        new VDFEntry((int)20, "", "OutWsMatricRecord", "WsMatricRecord", 
          "ExemptionExpiryDate", VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (
          short)0, null), 
        new VDFEntry((int)21, "", "OutWsMatricRecord", "WsMatricRecord", 
          "AuditedFlag", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, 
          null), 
        new VDFEntry((int)22, "", "OutWsMatricRecord", "WsMatricRecord", 
          "Symbol", VDFEntry.TYPE_STRING, (short)1, (short)0, 3, (short)0, null)
          , 
        new VDFEntry((int)23, "", "OutWsMatricRecord", "WsMatricRecord", 
          "OrigExemptDate", VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (short)0,
           null), 
        new VDFEntry((int)24, "", "OutWsMatricRecord", "WsMatricRecord", 
          "HcerCompleted", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)
          0, null), 
        new VDFEntry((int)25, "", "OutWsMatricRecord", "WsMatricRecord", 
          "DiplCompleted", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)
          0, null), 
        new VDFEntry((int)26, "", "OutWsMatricRecord", "WsMatricRecord", 
          "ApsScore", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, 
          null), 
        new VDFEntry((int)27, "", "OutWsMatricRecord", "WsMatricRecord", 
          "AcsScore", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, 
          null), 
        new VDFEntry((int)28, "OutGroup", "", "", "MA", VDFEntry.TYPE_INT, (
          short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)29, "OutGroup", "", "", "AC", VDFEntry.TYPE_CHAR, (
          short)350, (short)0, 1, (short)0, null), 
        new VDFEntry((int)30, "OutGroup", "OutGCsfLineActionBar", 
          "CsfLineActionBar", "SelectionFlag", VDFEntry.TYPE_STRING, (short)350,
           (short)0, 1, (short)0, null), 
        new VDFEntry((int)31, "OutGroup", "OutGWsQualification", 
          "WsQualification", "Code", VDFEntry.TYPE_STRING, (short)350, (short)0,
           5, (short)0, null), 
        new VDFEntry((int)32, "OutGroup", "OutGWsQualification", 
          "WsQualification", "Type", VDFEntry.TYPE_STRING, (short)350, (short)0,
           1, (short)0, null), 
        new VDFEntry((int)33, "OutGroup", "OutGWsQualification", 
          "WsQualification", "CollegeCode", VDFEntry.TYPE_SHORT, (short)350, (
          short)0, 2, (short)0, null), 
new VDFEntry((int)34, "OutGroup", "OutGWsQualificationSpecialityType", 
          "WsQualificationSpecialityType", "SpecialityCode", 
          VDFEntry.TYPE_STRING, (short)350, (short)0, 3, (short)0, null), 
        new VDFEntry((int)35, "OutGroup", "OutGCsfStrings", "CsfStrings", 
          "String2", VDFEntry.TYPE_STRING, (short)350, (short)0, 2, (short)0, 
          null), 
        new VDFEntry((int)36, "OutGroup", "OutGCsfStrings", "CsfStrings", 
          "String3", VDFEntry.TYPE_STRING, (short)350, (short)0, 3, (short)0, 
          null), 
        new VDFEntry((int)37, "OutGroup", "OutGCsfStrings", "CsfStrings", 
          "String4", VDFEntry.TYPE_STRING, (short)350, (short)0, 4, (short)0, 
          null), 
        new VDFEntry((int)38, "OutGroupMatric", "", "", "MA", VDFEntry.TYPE_INT,
           (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)39, "OutGroupMatric", "", "", "AC", 
          VDFEntry.TYPE_CHAR, (short)15, (short)0, 1, (short)0, null), 
        new VDFEntry((int)40, "OutGroupMatric", "OutGmCsfLineActionBar", 
          "CsfLineActionBar", "SelectionFlag", VDFEntry.TYPE_STRING, (short)15, 
          (short)0, 1, (short)0, null), 
        new VDFEntry((int)41, "OutGroupMatric", "OutGmWsMatricSubject", 
          "WsMatricSubject", "Code", VDFEntry.TYPE_STRING, (short)15, (short)0, 
          3, (short)0, null), 
        new VDFEntry((int)42, "OutGroupMatric", "OutGmWsMatricSubjectResult", 
          "WsMatricSubjectResult", "Grade", VDFEntry.TYPE_STRING, (short)15, (
          short)0, 1, (short)0, null), 
        new VDFEntry((int)43, "OutGroupMatric", "OutGmWsMatricSubjectResult", 
          "WsMatricSubjectResult", "Mark", VDFEntry.TYPE_SHORT, (short)15, (
          short)0, 2, (short)0, null), 
        new VDFEntry((int)44, "", "OutWsUser", "WsUser", "Number", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)45, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ReturnCode", VDFEntry.TYPE_SHORT, (
          short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)46, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerVersionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)47, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerRevisionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)48, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerDevelopmentPhase", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)49, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "Action", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)50, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientIsGuiFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)51, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerDate", VDFEntry.TYPE_DATE, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)52, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerTime", VDFEntry.TYPE_TIME, (
          short)1, (short)0, 6, (short)0, null), 
        new VDFEntry((int)53, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerTimestamp", 
          VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)54, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerTransactionCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)55, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerUserId", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)56, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerRollbackFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)57, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ActionsPendingFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)58, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientVersionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)59, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientRevisionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)60, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientDevelopmentPhase", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)61, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ListLinkFlag", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)62, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "CancelFlag", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)63, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "MaintLinkFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)64, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ForceDatabaseRead", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)65, "", "OutCsfStrings", "CsfStrings", "String500", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 500, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      OutWsAcademicYearYear = ((Short)vdf.getEntries()[0].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      OutWsAcademicYearYear = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      OutWsQualificationCode = ((String)vdf.getEntries()[1].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsQualificationCode = "     ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      OutWsQualificationType = ((String)vdf.getEntries()[2].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsQualificationType = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      OutWsQualificationSpecialityTypeMkQualificationCode = ((String)
        vdf.getEntries()[3].getDataValue().getObject());
    }
    else 
    {
      OutWsQualificationSpecialityTypeMkQualificationCode = "     ";
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      OutWsQualificationSpecialityTypeSpecialityCode = ((String)vdf.getEntries()
        [4].getDataValue().getObject());
    }
    else 
    {
      OutWsQualificationSpecialityTypeSpecialityCode = "   ";
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      OutWsStudentNr = ((Integer)vdf.getEntries()[5].getDataValue().getObject())
        .intValue();
    }
    else 
    {
      OutWsStudentNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      OutWsStudentMkTitle = ((String)vdf.getEntries()[6].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsStudentMkTitle = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      OutWsStudentSurname = ((String)vdf.getEntries()[7].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsStudentSurname = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      OutWsStudentInitials = ((String)vdf.getEntries()[8].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsStudentInitials = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      OutWsStudentIdentityNr = ((String)vdf.getEntries()[9].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsStudentIdentityNr = "             ";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      OutWsStudentBirthDate = ((Integer)vdf.getEntries()[10].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      OutWsStudentBirthDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      OutWsStudentMkNationality = ((String)vdf.getEntries()[11].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsStudentMkNationality = "    ";
    }
    // predicate view item
    if ( vdf.getEntries()[12].getDataValue().getObject() != null )
    {
      OutWsStudentMkLastAcademicYear = ((Short)vdf.getEntries()[12]
        .getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutWsStudentMkLastAcademicYear = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[13].getDataValue().getObject() != null )
    {
      OutWsStudentMkCountryCode = ((String)vdf.getEntries()[13].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsStudentMkCountryCode = "    ";
    }
    // predicate view item
    if ( vdf.getEntries()[14].getDataValue().getObject() != null )
    {
      OutWsMatricStatusCode = ((String)vdf.getEntries()[14].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsMatricStatusCode = "    ";
    }
    // predicate view item
    if ( vdf.getEntries()[15].getDataValue().getObject() != null )
    {
      OutWsMatricCertificateCode = ((String)vdf.getEntries()[15].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsMatricCertificateCode = "   ";
    }
    // predicate view item
    if ( vdf.getEntries()[16].getDataValue().getObject() != null )
    {
      OutWsMatricRecordCategory = ((Short)vdf.getEntries()[16].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      OutWsMatricRecordCategory = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[17].getDataValue().getObject() != null )
    {
      OutWsMatricRecordFullExemptionDate = ((Integer)vdf.getEntries()[17]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      OutWsMatricRecordFullExemptionDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[18].getDataValue().getObject() != null )
    {
      OutWsMatricRecordExemptionEffectiveDate = ((Integer)vdf.getEntries()[18]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      OutWsMatricRecordExemptionEffectiveDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[19].getDataValue().getObject() != null )
    {
      OutWsMatricRecordExemptionExpiryDate = ((Integer)vdf.getEntries()[19]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      OutWsMatricRecordExemptionExpiryDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[20].getDataValue().getObject() != null )
    {
      OutWsMatricRecordAuditedFlag = ((String)vdf.getEntries()[20].getDataValue(
        ).getObject());
    }
    else 
    {
      OutWsMatricRecordAuditedFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[21].getDataValue().getObject() != null )
    {
      OutWsMatricRecordSymbol = ((String)vdf.getEntries()[21].getDataValue()
        .getObject());
    }
    else 
    {
      OutWsMatricRecordSymbol = "   ";
    }
    // predicate view item
    if ( vdf.getEntries()[22].getDataValue().getObject() != null )
    {
      OutWsMatricRecordOrigExemptDate = ((Integer)vdf.getEntries()[22]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      OutWsMatricRecordOrigExemptDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[23].getDataValue().getObject() != null )
    {
      OutWsMatricRecordHcerCompleted = ((String)vdf.getEntries()[23]
        .getDataValue().getObject());
    }
    else 
    {
      OutWsMatricRecordHcerCompleted = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[24].getDataValue().getObject() != null )
    {
      OutWsMatricRecordDiplCompleted = ((String)vdf.getEntries()[24]
        .getDataValue().getObject());
    }
    else 
    {
      OutWsMatricRecordDiplCompleted = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[25].getDataValue().getObject() != null )
    {
      OutWsMatricRecordApsScore = ((Short)vdf.getEntries()[25].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      OutWsMatricRecordApsScore = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[26].getDataValue().getObject() != null )
    {
      OutWsMatricRecordAcsScore = ((Short)vdf.getEntries()[26].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      OutWsMatricRecordAcsScore = 0;
    }
    // group view current cardinality
    if ( vdf.getEntries()[27].getDataValue().getObject() != null )
    {
      OutGroup_MA = ((Integer)vdf.getEntries()[27].getDataValue().getObject())
        .intValue();
    }
    else 
    {
      OutGroup_MA = ' ';
    }
    // group view active flags
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[28].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGroup_AC[adim0] = ((Character)((VDFEntryObject [])vdf.getEntries()[
          28].getDataValue().getObject())[adim0].getObject()).charValue();
      }
      else 
      {
        OutGroup_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[29].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfLineActionBarSelectionFlag[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[29].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGCsfLineActionBarSelectionFlag[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[30].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGWsQualificationCode[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[30].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGWsQualificationCode[adim0] = "     ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[31].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGWsQualificationType[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[31].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGWsQualificationType[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[32].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGWsQualificationCollegeCode[adim0] = ((Short)((VDFEntryObject [])
          vdf.getEntries()[32].getDataValue().getObject())[adim0].getObject())
          .shortValue();
      }
      else 
      {
        OutGWsQualificationCollegeCode[adim0] = 0;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[33].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGWsQualificationSpecialityTypeSpecialityCode[adim0] = ((String)((
          VDFEntryObject [])vdf.getEntries()[33].getDataValue().getObject())[
          adim0].getObject());
      }
      else 
      {
        OutGWsQualificationSpecialityTypeSpecialityCode[adim0] = "   ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[34].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfStringsString2[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[34].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGCsfStringsString2[adim0] = "  ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[35].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfStringsString3[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[35].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGCsfStringsString3[adim0] = "   ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[36].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfStringsString4[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[36].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGCsfStringsString4[adim0] = "    ";
      }
    }
    // group view current cardinality
    if ( vdf.getEntries()[37].getDataValue().getObject() != null )
    {
      OutGroupMatric_MA = ((Integer)vdf.getEntries()[37].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      OutGroupMatric_MA = ' ';
    }
    // group view active flags
    for(int adim0 = 0; adim0 < OutGroupMatric_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[38].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGroupMatric_AC[adim0] = ((Character)((VDFEntryObject [])
          vdf.getEntries()[38].getDataValue().getObject())[adim0].getObject())
          .charValue();
      }
      else 
      {
        OutGroupMatric_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupMatric_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[39].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGmCsfLineActionBarSelectionFlag[adim0] = ((String)((VDFEntryObject []
          )vdf.getEntries()[39].getDataValue().getObject())[adim0].getObject())
          ;
      }
      else 
      {
        OutGmCsfLineActionBarSelectionFlag[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupMatric_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[40].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGmWsMatricSubjectCode[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[40].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGmWsMatricSubjectCode[adim0] = "   ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupMatric_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[41].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGmWsMatricSubjectResultGrade[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[41].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGmWsMatricSubjectResultGrade[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupMatric_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[42].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGmWsMatricSubjectResultMark[adim0] = ((Short)((VDFEntryObject [])
          vdf.getEntries()[42].getDataValue().getObject())[adim0].getObject())
          .shortValue();
      }
      else 
      {
        OutGmWsMatricSubjectResultMark[adim0] = 0;
      }
    }
    // predicate view item
    if ( vdf.getEntries()[43].getDataValue().getObject() != null )
    {
      OutWsUserNumber = ((Integer)vdf.getEntries()[43].getDataValue().getObject(
        )).intValue();
    }
    else 
    {
      OutWsUserNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[44].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsReturnCode = ((Short)vdf.getEntries()[44]
        .getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsReturnCode = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[45].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerVersionNumber = ((Short)
        vdf.getEntries()[45].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerVersionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[46].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerRevisionNumber = ((Short)
        vdf.getEntries()[46].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerRevisionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[47].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerDevelopmentPhase = ((String)
        vdf.getEntries()[47].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerDevelopmentPhase = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[48].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsAction = ((String)vdf.getEntries()[48]
        .getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsAction = "  ";
    }
    // predicate view item
    if ( vdf.getEntries()[49].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientIsGuiFlag = ((String)vdf.getEntries(
        )[49].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsClientIsGuiFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[50].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerDate = ((Integer)vdf.getEntries()[
        50].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[51].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerTime = ((Integer)vdf.getEntries()[
        51].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerTime = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[52].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerTimestamp = ((String)vdf.getEntries(
        )[52].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerTimestamp = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[53].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerTransactionCode = ((String)
        vdf.getEntries()[53].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerTransactionCode = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[54].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerUserId = ((String)vdf.getEntries()[
        54].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerUserId = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[55].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerRollbackFlag = ((String)
        vdf.getEntries()[55].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerRollbackFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[56].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsActionsPendingFlag = ((String)
        vdf.getEntries()[56].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsActionsPendingFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[57].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientVersionNumber = ((Short)
        vdf.getEntries()[57].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsClientVersionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[58].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientRevisionNumber = ((Short)
        vdf.getEntries()[58].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsClientRevisionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[59].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientDevelopmentPhase = ((String)
        vdf.getEntries()[59].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[60].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsListLinkFlag = ((String)vdf.getEntries()[
        60].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsListLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[61].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsCancelFlag = ((String)vdf.getEntries()[61]
        .getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsCancelFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[62].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsMaintLinkFlag = ((String)vdf.getEntries()[
        62].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsMaintLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[63].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsForceDatabaseRead = ((String)
        vdf.getEntries()[63].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsForceDatabaseRead = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[64].getDataValue().getObject() != null )
    {
      OutCsfStringsString500 = ((String)vdf.getEntries()[64].getDataValue()
        .getObject());
    }
    else 
    {
      OutCsfStringsString500 = "";
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(new Short(
      OutWsAcademicYearYear));
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(OutWsQualificationCode);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(OutWsQualificationType);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(
      OutWsQualificationSpecialityTypeMkQualificationCode);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(
      OutWsQualificationSpecialityTypeSpecialityCode);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(new Integer(OutWsStudentNr));
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(OutWsStudentMkTitle);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(OutWsStudentSurname);
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(OutWsStudentInitials);
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(OutWsStudentIdentityNr);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(new Integer(
      OutWsStudentBirthDate));
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(OutWsStudentMkNationality);
    // predicate view item
    vdf.getEntries()[12].getDataValue().setObject(new Short(
      OutWsStudentMkLastAcademicYear));
    // predicate view item
    vdf.getEntries()[13].getDataValue().setObject(OutWsStudentMkCountryCode);
    // predicate view item
    vdf.getEntries()[14].getDataValue().setObject(OutWsMatricStatusCode);
    // predicate view item
    vdf.getEntries()[15].getDataValue().setObject(OutWsMatricCertificateCode);
    // predicate view item
    vdf.getEntries()[16].getDataValue().setObject(new Short(
      OutWsMatricRecordCategory));
    // predicate view item
    vdf.getEntries()[17].getDataValue().setObject(new Integer(
      OutWsMatricRecordFullExemptionDate));
    // predicate view item
    vdf.getEntries()[18].getDataValue().setObject(new Integer(
      OutWsMatricRecordExemptionEffectiveDate));
    // predicate view item
    vdf.getEntries()[19].getDataValue().setObject(new Integer(
      OutWsMatricRecordExemptionExpiryDate));
    // predicate view item
    vdf.getEntries()[20].getDataValue().setObject(OutWsMatricRecordAuditedFlag)
      ;
    // predicate view item
    vdf.getEntries()[21].getDataValue().setObject(OutWsMatricRecordSymbol);
    // predicate view item
    vdf.getEntries()[22].getDataValue().setObject(new Integer(
      OutWsMatricRecordOrigExemptDate));
    // predicate view item
    vdf.getEntries()[23].getDataValue().setObject(
      OutWsMatricRecordHcerCompleted);
    // predicate view item
    vdf.getEntries()[24].getDataValue().setObject(
      OutWsMatricRecordDiplCompleted);
    // predicate view item
    vdf.getEntries()[25].getDataValue().setObject(new Short(
      OutWsMatricRecordApsScore));
    // predicate view item
    vdf.getEntries()[26].getDataValue().setObject(new Short(
      OutWsMatricRecordAcsScore));
    // group view current cardinality
    vdf.getEntries()[27].getDataValue().setObject(new Integer(OutGroup_MA));
    // group view active flags
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      if ( adim0 < OutGroup_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[28].getDataValue().getObject())[
          adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[28].getDataValue().getObject())[
          adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[28].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[29].getDataValue().getObject())[
        adim0].setObject(OutGCsfLineActionBarSelectionFlag[adim0]);
    }
    vdf.getEntries()[29].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[30].getDataValue().getObject())[
        adim0].setObject(OutGWsQualificationCode[adim0]);
    }
    vdf.getEntries()[30].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[31].getDataValue().getObject())[
        adim0].setObject(OutGWsQualificationType[adim0]);
    }
    vdf.getEntries()[31].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[32].getDataValue().getObject())[
        adim0].setObject(new Short(OutGWsQualificationCollegeCode[adim0]));
    }
    vdf.getEntries()[32].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[33].getDataValue().getObject())[
        adim0].setObject(OutGWsQualificationSpecialityTypeSpecialityCode[adim0])
        ;
    }
    vdf.getEntries()[33].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[34].getDataValue().getObject())[
        adim0].setObject(OutGCsfStringsString2[adim0]);
    }
    vdf.getEntries()[34].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[35].getDataValue().getObject())[
        adim0].setObject(OutGCsfStringsString3[adim0]);
    }
    vdf.getEntries()[35].setCountUsed((short)OutGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 350; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[36].getDataValue().getObject())[
        adim0].setObject(OutGCsfStringsString4[adim0]);
    }
    vdf.getEntries()[36].setCountUsed((short)OutGroup_MA);
    // group view current cardinality
    vdf.getEntries()[37].getDataValue().setObject(new Integer(OutGroupMatric_MA)
      );
    // group view active flags
    for(int adim0 = 0; adim0 < 15; adim0++)
    {
      if ( adim0 < OutGroupMatric_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[38].getDataValue().getObject())[
          adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[38].getDataValue().getObject())[
          adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[38].setCountUsed((short)OutGroupMatric_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 15; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[39].getDataValue().getObject())[
        adim0].setObject(OutGmCsfLineActionBarSelectionFlag[adim0]);
    }
    vdf.getEntries()[39].setCountUsed((short)OutGroupMatric_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 15; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[40].getDataValue().getObject())[
        adim0].setObject(OutGmWsMatricSubjectCode[adim0]);
    }
    vdf.getEntries()[40].setCountUsed((short)OutGroupMatric_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 15; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[41].getDataValue().getObject())[
        adim0].setObject(OutGmWsMatricSubjectResultGrade[adim0]);
    }
    vdf.getEntries()[41].setCountUsed((short)OutGroupMatric_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 15; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[42].getDataValue().getObject())[
        adim0].setObject(new Short(OutGmWsMatricSubjectResultMark[adim0]));
    }
    vdf.getEntries()[42].setCountUsed((short)OutGroupMatric_MA);
    // predicate view item
    vdf.getEntries()[43].getDataValue().setObject(new Integer(OutWsUserNumber))
      ;
    // predicate view item
    vdf.getEntries()[44].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsReturnCode));
    // predicate view item
    vdf.getEntries()[45].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsServerVersionNumber));
    // predicate view item
    vdf.getEntries()[46].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsServerRevisionNumber));
    // predicate view item
    vdf.getEntries()[47].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerDevelopmentPhase);
    // predicate view item
    vdf.getEntries()[48].getDataValue().setObject(
      OutCsfClientServerCommunicationsAction);
    // predicate view item
    vdf.getEntries()[49].getDataValue().setObject(
      OutCsfClientServerCommunicationsClientIsGuiFlag);
    // predicate view item
    vdf.getEntries()[50].getDataValue().setObject(new Integer(
      OutCsfClientServerCommunicationsServerDate));
    // predicate view item
    vdf.getEntries()[51].getDataValue().setObject(new Integer(
      OutCsfClientServerCommunicationsServerTime));
    // predicate view item
    vdf.getEntries()[52].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerTimestamp);
    // predicate view item
    vdf.getEntries()[53].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerTransactionCode);
    // predicate view item
    vdf.getEntries()[54].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerUserId);
    // predicate view item
    vdf.getEntries()[55].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerRollbackFlag);
    // predicate view item
    vdf.getEntries()[56].getDataValue().setObject(
      OutCsfClientServerCommunicationsActionsPendingFlag);
    // predicate view item
    vdf.getEntries()[57].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsClientVersionNumber));
    // predicate view item
    vdf.getEntries()[58].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsClientRevisionNumber));
    // predicate view item
    vdf.getEntries()[59].getDataValue().setObject(
      OutCsfClientServerCommunicationsClientDevelopmentPhase);
    // predicate view item
    vdf.getEntries()[60].getDataValue().setObject(
      OutCsfClientServerCommunicationsListLinkFlag);
    // predicate view item
    vdf.getEntries()[61].getDataValue().setObject(
      OutCsfClientServerCommunicationsCancelFlag);
    // predicate view item
    vdf.getEntries()[62].getDataValue().setObject(
      OutCsfClientServerCommunicationsMaintLinkFlag);
    // predicate view item
    vdf.getEntries()[63].getDataValue().setObject(
      OutCsfClientServerCommunicationsForceDatabaseRead);
    // predicate view item
    vdf.getEntries()[64].getDataValue().setObject(OutCsfStringsString500);
    return(vdf);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((STAAE05S_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(STAAE05S_OA orig)
  {
    OutWsAcademicYearYear_AT = orig.OutWsAcademicYearYear_AT;
    OutWsAcademicYearYear_AS = orig.OutWsAcademicYearYear_AS;
    OutWsAcademicYearYear = orig.OutWsAcademicYearYear;
    OutWsQualificationCode_AT = orig.OutWsQualificationCode_AT;
    OutWsQualificationCode_AS = orig.OutWsQualificationCode_AS;
    OutWsQualificationCode = orig.OutWsQualificationCode;
    OutWsQualificationType_AT = orig.OutWsQualificationType_AT;
    OutWsQualificationType_AS = orig.OutWsQualificationType_AS;
    OutWsQualificationType = orig.OutWsQualificationType;
    OutWsQualificationSpecialityTypeMkQualificationCode_AT = 
      orig.OutWsQualificationSpecialityTypeMkQualificationCode_AT;
    OutWsQualificationSpecialityTypeMkQualificationCode_AS = 
      orig.OutWsQualificationSpecialityTypeMkQualificationCode_AS;
    OutWsQualificationSpecialityTypeMkQualificationCode = 
      orig.OutWsQualificationSpecialityTypeMkQualificationCode;
    OutWsQualificationSpecialityTypeSpecialityCode_AT = 
      orig.OutWsQualificationSpecialityTypeSpecialityCode_AT;
    OutWsQualificationSpecialityTypeSpecialityCode_AS = 
      orig.OutWsQualificationSpecialityTypeSpecialityCode_AS;
    OutWsQualificationSpecialityTypeSpecialityCode = 
      orig.OutWsQualificationSpecialityTypeSpecialityCode;
    OutWsStudentNr_AT = orig.OutWsStudentNr_AT;
    OutWsStudentNr_AS = orig.OutWsStudentNr_AS;
    OutWsStudentNr = orig.OutWsStudentNr;
    OutWsStudentMkTitle_AT = orig.OutWsStudentMkTitle_AT;
    OutWsStudentMkTitle_AS = orig.OutWsStudentMkTitle_AS;
    OutWsStudentMkTitle = orig.OutWsStudentMkTitle;
    OutWsStudentSurname_AT = orig.OutWsStudentSurname_AT;
    OutWsStudentSurname_AS = orig.OutWsStudentSurname_AS;
    OutWsStudentSurname = orig.OutWsStudentSurname;
    OutWsStudentInitials_AT = orig.OutWsStudentInitials_AT;
    OutWsStudentInitials_AS = orig.OutWsStudentInitials_AS;
    OutWsStudentInitials = orig.OutWsStudentInitials;
    OutWsStudentIdentityNr_AT = orig.OutWsStudentIdentityNr_AT;
    OutWsStudentIdentityNr_AS = orig.OutWsStudentIdentityNr_AS;
    OutWsStudentIdentityNr = orig.OutWsStudentIdentityNr;
    OutWsStudentBirthDate_AT = orig.OutWsStudentBirthDate_AT;
    OutWsStudentBirthDate_AS = orig.OutWsStudentBirthDate_AS;
    OutWsStudentBirthDate = orig.OutWsStudentBirthDate;
    OutWsStudentMkNationality_AT = orig.OutWsStudentMkNationality_AT;
    OutWsStudentMkNationality_AS = orig.OutWsStudentMkNationality_AS;
    OutWsStudentMkNationality = orig.OutWsStudentMkNationality;
    OutWsStudentMkLastAcademicYear_AT = orig.OutWsStudentMkLastAcademicYear_AT;
    OutWsStudentMkLastAcademicYear_AS = orig.OutWsStudentMkLastAcademicYear_AS;
    OutWsStudentMkLastAcademicYear = orig.OutWsStudentMkLastAcademicYear;
    OutWsStudentMkCountryCode_AT = orig.OutWsStudentMkCountryCode_AT;
    OutWsStudentMkCountryCode_AS = orig.OutWsStudentMkCountryCode_AS;
    OutWsStudentMkCountryCode = orig.OutWsStudentMkCountryCode;
    OutWsMatricStatusCode_AT = orig.OutWsMatricStatusCode_AT;
    OutWsMatricStatusCode_AS = orig.OutWsMatricStatusCode_AS;
    OutWsMatricStatusCode = orig.OutWsMatricStatusCode;
    OutWsMatricCertificateCode_AT = orig.OutWsMatricCertificateCode_AT;
    OutWsMatricCertificateCode_AS = orig.OutWsMatricCertificateCode_AS;
    OutWsMatricCertificateCode = orig.OutWsMatricCertificateCode;
    OutWsMatricRecordCategory_AT = orig.OutWsMatricRecordCategory_AT;
    OutWsMatricRecordCategory_AS = orig.OutWsMatricRecordCategory_AS;
    OutWsMatricRecordCategory = orig.OutWsMatricRecordCategory;
    OutWsMatricRecordFullExemptionDate_AT = 
      orig.OutWsMatricRecordFullExemptionDate_AT;
    OutWsMatricRecordFullExemptionDate_AS = 
      orig.OutWsMatricRecordFullExemptionDate_AS;
    OutWsMatricRecordFullExemptionDate = 
      orig.OutWsMatricRecordFullExemptionDate;
    OutWsMatricRecordExemptionEffectiveDate_AT = 
      orig.OutWsMatricRecordExemptionEffectiveDate_AT;
    OutWsMatricRecordExemptionEffectiveDate_AS = 
      orig.OutWsMatricRecordExemptionEffectiveDate_AS;
    OutWsMatricRecordExemptionEffectiveDate = 
      orig.OutWsMatricRecordExemptionEffectiveDate;
    OutWsMatricRecordExemptionExpiryDate_AT = 
      orig.OutWsMatricRecordExemptionExpiryDate_AT;
    OutWsMatricRecordExemptionExpiryDate_AS = 
      orig.OutWsMatricRecordExemptionExpiryDate_AS;
    OutWsMatricRecordExemptionExpiryDate = 
      orig.OutWsMatricRecordExemptionExpiryDate;
    OutWsMatricRecordAuditedFlag_AT = orig.OutWsMatricRecordAuditedFlag_AT;
    OutWsMatricRecordAuditedFlag_AS = orig.OutWsMatricRecordAuditedFlag_AS;
    OutWsMatricRecordAuditedFlag = orig.OutWsMatricRecordAuditedFlag;
    OutWsMatricRecordSymbol_AT = orig.OutWsMatricRecordSymbol_AT;
    OutWsMatricRecordSymbol_AS = orig.OutWsMatricRecordSymbol_AS;
    OutWsMatricRecordSymbol = orig.OutWsMatricRecordSymbol;
    OutWsMatricRecordOrigExemptDate_AT = 
      orig.OutWsMatricRecordOrigExemptDate_AT;
    OutWsMatricRecordOrigExemptDate_AS = 
      orig.OutWsMatricRecordOrigExemptDate_AS;
    OutWsMatricRecordOrigExemptDate = orig.OutWsMatricRecordOrigExemptDate;
    OutWsMatricRecordHcerCompleted_AT = orig.OutWsMatricRecordHcerCompleted_AT;
    OutWsMatricRecordHcerCompleted_AS = orig.OutWsMatricRecordHcerCompleted_AS;
    OutWsMatricRecordHcerCompleted = orig.OutWsMatricRecordHcerCompleted;
    OutWsMatricRecordDiplCompleted_AT = orig.OutWsMatricRecordDiplCompleted_AT;
    OutWsMatricRecordDiplCompleted_AS = orig.OutWsMatricRecordDiplCompleted_AS;
    OutWsMatricRecordDiplCompleted = orig.OutWsMatricRecordDiplCompleted;
    OutWsMatricRecordApsScore_AT = orig.OutWsMatricRecordApsScore_AT;
    OutWsMatricRecordApsScore_AS = orig.OutWsMatricRecordApsScore_AS;
    OutWsMatricRecordApsScore = orig.OutWsMatricRecordApsScore;
    OutWsMatricRecordAcsScore_AT = orig.OutWsMatricRecordAcsScore_AT;
    OutWsMatricRecordAcsScore_AS = orig.OutWsMatricRecordAcsScore_AS;
    OutWsMatricRecordAcsScore = orig.OutWsMatricRecordAcsScore;
    OutGroup_MA = orig.OutGroup_MA;
    for(int a = 0; a < 350; a++)
    {
      OutGroup_AC[a] = orig.OutGroup_AC[a];
      OutGCsfLineActionBarSelectionFlag_AT[a] = 
        orig.OutGCsfLineActionBarSelectionFlag_AT[a];
      OutGCsfLineActionBarSelectionFlag_AS[a] = 
        orig.OutGCsfLineActionBarSelectionFlag_AS[a];
      OutGCsfLineActionBarSelectionFlag[a] = 
        orig.OutGCsfLineActionBarSelectionFlag[a];
      OutGWsQualificationCode_AT[a] = orig.OutGWsQualificationCode_AT[a];
      OutGWsQualificationCode_AS[a] = orig.OutGWsQualificationCode_AS[a];
      OutGWsQualificationCode[a] = orig.OutGWsQualificationCode[a];
      OutGWsQualificationType_AT[a] = orig.OutGWsQualificationType_AT[a];
      OutGWsQualificationType_AS[a] = orig.OutGWsQualificationType_AS[a];
      OutGWsQualificationType[a] = orig.OutGWsQualificationType[a];
      OutGWsQualificationCollegeCode_AT[a] = 
        orig.OutGWsQualificationCollegeCode_AT[a];
      OutGWsQualificationCollegeCode_AS[a] = 
        orig.OutGWsQualificationCollegeCode_AS[a];
      OutGWsQualificationCollegeCode[a] = orig.OutGWsQualificationCollegeCode[a]
        ;
      OutGWsQualificationSpecialityTypeSpecialityCode_AT[a] = 
        orig.OutGWsQualificationSpecialityTypeSpecialityCode_AT[a];
      OutGWsQualificationSpecialityTypeSpecialityCode_AS[a] = 
        orig.OutGWsQualificationSpecialityTypeSpecialityCode_AS[a];
      OutGWsQualificationSpecialityTypeSpecialityCode[a] = 
        orig.OutGWsQualificationSpecialityTypeSpecialityCode[a];
      OutGCsfStringsString2_AT[a] = orig.OutGCsfStringsString2_AT[a];
      OutGCsfStringsString2_AS[a] = orig.OutGCsfStringsString2_AS[a];
      OutGCsfStringsString2[a] = orig.OutGCsfStringsString2[a];
      OutGCsfStringsString3_AT[a] = orig.OutGCsfStringsString3_AT[a];
      OutGCsfStringsString3_AS[a] = orig.OutGCsfStringsString3_AS[a];
      OutGCsfStringsString3[a] = orig.OutGCsfStringsString3[a];
      OutGCsfStringsString4_AT[a] = orig.OutGCsfStringsString4_AT[a];
      OutGCsfStringsString4_AS[a] = orig.OutGCsfStringsString4_AS[a];
      OutGCsfStringsString4[a] = orig.OutGCsfStringsString4[a];
    }
    OutGroupMatric_MA = orig.OutGroupMatric_MA;
    for(int a = 0; a < 15; a++)
    {
      OutGroupMatric_AC[a] = orig.OutGroupMatric_AC[a];
      OutGmCsfLineActionBarSelectionFlag_AT[a] = 
        orig.OutGmCsfLineActionBarSelectionFlag_AT[a];
      OutGmCsfLineActionBarSelectionFlag_AS[a] = 
        orig.OutGmCsfLineActionBarSelectionFlag_AS[a];
      OutGmCsfLineActionBarSelectionFlag[a] = 
        orig.OutGmCsfLineActionBarSelectionFlag[a];
      OutGmWsMatricSubjectCode_AT[a] = orig.OutGmWsMatricSubjectCode_AT[a];
      OutGmWsMatricSubjectCode_AS[a] = orig.OutGmWsMatricSubjectCode_AS[a];
      OutGmWsMatricSubjectCode[a] = orig.OutGmWsMatricSubjectCode[a];
      OutGmWsMatricSubjectResultGrade_AT[a] = 
        orig.OutGmWsMatricSubjectResultGrade_AT[a];
      OutGmWsMatricSubjectResultGrade_AS[a] = 
        orig.OutGmWsMatricSubjectResultGrade_AS[a];
      OutGmWsMatricSubjectResultGrade[a] = orig.OutGmWsMatricSubjectResultGrade[
        a];
      OutGmWsMatricSubjectResultMark_AT[a] = 
        orig.OutGmWsMatricSubjectResultMark_AT[a];
      OutGmWsMatricSubjectResultMark_AS[a] = 
        orig.OutGmWsMatricSubjectResultMark_AS[a];
      OutGmWsMatricSubjectResultMark[a] = orig.OutGmWsMatricSubjectResultMark[a]
        ;
    }
    OutWsUserNumber_AT = orig.OutWsUserNumber_AT;
    OutWsUserNumber_AS = orig.OutWsUserNumber_AS;
    OutWsUserNumber = orig.OutWsUserNumber;
    OutCsfClientServerCommunicationsReturnCode_AT = 
      orig.OutCsfClientServerCommunicationsReturnCode_AT;
    OutCsfClientServerCommunicationsReturnCode_AS = 
      orig.OutCsfClientServerCommunicationsReturnCode_AS;
    OutCsfClientServerCommunicationsReturnCode = 
      orig.OutCsfClientServerCommunicationsReturnCode;
    OutCsfClientServerCommunicationsServerVersionNumber_AT = 
      orig.OutCsfClientServerCommunicationsServerVersionNumber_AT;
    OutCsfClientServerCommunicationsServerVersionNumber_AS = 
      orig.OutCsfClientServerCommunicationsServerVersionNumber_AS;
    OutCsfClientServerCommunicationsServerVersionNumber = 
      orig.OutCsfClientServerCommunicationsServerVersionNumber;
    OutCsfClientServerCommunicationsServerRevisionNumber_AT = 
      orig.OutCsfClientServerCommunicationsServerRevisionNumber_AT;
    OutCsfClientServerCommunicationsServerRevisionNumber_AS = 
      orig.OutCsfClientServerCommunicationsServerRevisionNumber_AS;
    OutCsfClientServerCommunicationsServerRevisionNumber = 
      orig.OutCsfClientServerCommunicationsServerRevisionNumber;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AT = 
      orig.OutCsfClientServerCommunicationsServerDevelopmentPhase_AT;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AS = 
      orig.OutCsfClientServerCommunicationsServerDevelopmentPhase_AS;
    OutCsfClientServerCommunicationsServerDevelopmentPhase = 
      orig.OutCsfClientServerCommunicationsServerDevelopmentPhase;
    OutCsfClientServerCommunicationsAction_AT = 
      orig.OutCsfClientServerCommunicationsAction_AT;
    OutCsfClientServerCommunicationsAction_AS = 
      orig.OutCsfClientServerCommunicationsAction_AS;
    OutCsfClientServerCommunicationsAction = 
      orig.OutCsfClientServerCommunicationsAction;
    OutCsfClientServerCommunicationsClientIsGuiFlag_AT = 
      orig.OutCsfClientServerCommunicationsClientIsGuiFlag_AT;
    OutCsfClientServerCommunicationsClientIsGuiFlag_AS = 
      orig.OutCsfClientServerCommunicationsClientIsGuiFlag_AS;
    OutCsfClientServerCommunicationsClientIsGuiFlag = 
      orig.OutCsfClientServerCommunicationsClientIsGuiFlag;
    OutCsfClientServerCommunicationsServerDate_AT = 
      orig.OutCsfClientServerCommunicationsServerDate_AT;
    OutCsfClientServerCommunicationsServerDate_AS = 
      orig.OutCsfClientServerCommunicationsServerDate_AS;
    OutCsfClientServerCommunicationsServerDate = 
      orig.OutCsfClientServerCommunicationsServerDate;
    OutCsfClientServerCommunicationsServerTime_AT = 
      orig.OutCsfClientServerCommunicationsServerTime_AT;
    OutCsfClientServerCommunicationsServerTime_AS = 
      orig.OutCsfClientServerCommunicationsServerTime_AS;
    OutCsfClientServerCommunicationsServerTime = 
      orig.OutCsfClientServerCommunicationsServerTime;
    OutCsfClientServerCommunicationsServerTimestamp_AT = 
      orig.OutCsfClientServerCommunicationsServerTimestamp_AT;
    OutCsfClientServerCommunicationsServerTimestamp_AS = 
      orig.OutCsfClientServerCommunicationsServerTimestamp_AS;
    OutCsfClientServerCommunicationsServerTimestamp = 
      orig.OutCsfClientServerCommunicationsServerTimestamp;
    OutCsfClientServerCommunicationsServerTransactionCode_AT = 
      orig.OutCsfClientServerCommunicationsServerTransactionCode_AT;
    OutCsfClientServerCommunicationsServerTransactionCode_AS = 
      orig.OutCsfClientServerCommunicationsServerTransactionCode_AS;
    OutCsfClientServerCommunicationsServerTransactionCode = 
      orig.OutCsfClientServerCommunicationsServerTransactionCode;
    OutCsfClientServerCommunicationsServerUserId_AT = 
      orig.OutCsfClientServerCommunicationsServerUserId_AT;
    OutCsfClientServerCommunicationsServerUserId_AS = 
      orig.OutCsfClientServerCommunicationsServerUserId_AS;
    OutCsfClientServerCommunicationsServerUserId = 
      orig.OutCsfClientServerCommunicationsServerUserId;
    OutCsfClientServerCommunicationsServerRollbackFlag_AT = 
      orig.OutCsfClientServerCommunicationsServerRollbackFlag_AT;
    OutCsfClientServerCommunicationsServerRollbackFlag_AS = 
      orig.OutCsfClientServerCommunicationsServerRollbackFlag_AS;
    OutCsfClientServerCommunicationsServerRollbackFlag = 
      orig.OutCsfClientServerCommunicationsServerRollbackFlag;
    OutCsfClientServerCommunicationsActionsPendingFlag_AT = 
      orig.OutCsfClientServerCommunicationsActionsPendingFlag_AT;
    OutCsfClientServerCommunicationsActionsPendingFlag_AS = 
      orig.OutCsfClientServerCommunicationsActionsPendingFlag_AS;
    OutCsfClientServerCommunicationsActionsPendingFlag = 
      orig.OutCsfClientServerCommunicationsActionsPendingFlag;
    OutCsfClientServerCommunicationsClientVersionNumber_AT = 
      orig.OutCsfClientServerCommunicationsClientVersionNumber_AT;
    OutCsfClientServerCommunicationsClientVersionNumber_AS = 
      orig.OutCsfClientServerCommunicationsClientVersionNumber_AS;
    OutCsfClientServerCommunicationsClientVersionNumber = 
      orig.OutCsfClientServerCommunicationsClientVersionNumber;
    OutCsfClientServerCommunicationsClientRevisionNumber_AT = 
      orig.OutCsfClientServerCommunicationsClientRevisionNumber_AT;
    OutCsfClientServerCommunicationsClientRevisionNumber_AS = 
      orig.OutCsfClientServerCommunicationsClientRevisionNumber_AS;
    OutCsfClientServerCommunicationsClientRevisionNumber = 
      orig.OutCsfClientServerCommunicationsClientRevisionNumber;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AT = 
      orig.OutCsfClientServerCommunicationsClientDevelopmentPhase_AT;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AS = 
      orig.OutCsfClientServerCommunicationsClientDevelopmentPhase_AS;
    OutCsfClientServerCommunicationsClientDevelopmentPhase = 
      orig.OutCsfClientServerCommunicationsClientDevelopmentPhase;
    OutCsfClientServerCommunicationsListLinkFlag_AT = 
      orig.OutCsfClientServerCommunicationsListLinkFlag_AT;
    OutCsfClientServerCommunicationsListLinkFlag_AS = 
      orig.OutCsfClientServerCommunicationsListLinkFlag_AS;
    OutCsfClientServerCommunicationsListLinkFlag = 
      orig.OutCsfClientServerCommunicationsListLinkFlag;
    OutCsfClientServerCommunicationsCancelFlag_AT = 
      orig.OutCsfClientServerCommunicationsCancelFlag_AT;
    OutCsfClientServerCommunicationsCancelFlag_AS = 
      orig.OutCsfClientServerCommunicationsCancelFlag_AS;
    OutCsfClientServerCommunicationsCancelFlag = 
      orig.OutCsfClientServerCommunicationsCancelFlag;
    OutCsfClientServerCommunicationsMaintLinkFlag_AT = 
      orig.OutCsfClientServerCommunicationsMaintLinkFlag_AT;
    OutCsfClientServerCommunicationsMaintLinkFlag_AS = 
      orig.OutCsfClientServerCommunicationsMaintLinkFlag_AS;
    OutCsfClientServerCommunicationsMaintLinkFlag = 
      orig.OutCsfClientServerCommunicationsMaintLinkFlag;
    OutCsfClientServerCommunicationsForceDatabaseRead_AT = 
      orig.OutCsfClientServerCommunicationsForceDatabaseRead_AT;
    OutCsfClientServerCommunicationsForceDatabaseRead_AS = 
      orig.OutCsfClientServerCommunicationsForceDatabaseRead_AS;
    OutCsfClientServerCommunicationsForceDatabaseRead = 
      orig.OutCsfClientServerCommunicationsForceDatabaseRead;
    OutCsfStringsString500_AT = orig.OutCsfStringsString500_AT;
    OutCsfStringsString500_AS = orig.OutCsfStringsString500_AS;
    OutCsfStringsString500 = orig.OutCsfStringsString500;
  }
}
