ALTER TABLE `qna_QUESTIONS` MODIFY COLUMN `ownerId` VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN `lastModifierId` VARCHAR(255)  DEFAULT NULL;
ALTER TABLE `qna_ANSWERS` MODIFY COLUMN `ownerId` VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN `lastModifierId` VARCHAR(255)  DEFAULT NULL;