ALTER TABLE YAFT_DISCUSSION ADD COLUMN GRADEBOOK_ASSIGNMENT_ID BIGINT(20);
CREATE TABLE YAFT_DISCUSSION_GROUP (DISCUSSION_ID CHAR(36) NOT NULL,GROUP_ID VARCHAR(36) NOT NULL,CONSTRAINT yaft_discussion_group_pk PRIMARY KEY (DISCUSSION_ID,GROUP_ID));
