package Ecdcq01h;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                            CA Gen r8
//
//           Copyright (c) 2012 CA. All rights reserved.
//
//    Name: ECDCQ01S_OA                      Date: 2012/05/15
//    User: Tanderw                          Time: 13:49:46
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen80.vwrt.*;
import com.ca.gen80.vwrt.types.*;
import com.ca.gen80.vwrt.vdf.*;
import com.ca.gen80.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: ECDCQ01S_OA
 **/
public class ECDCQ01S_OA extends ViewBase implements IExportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: OUT
  //        Type: ECAPS_DOCUMENT
  /**
   * Attribute missing flag for: OutEcapsDocumentMkAcademicYear
   **/
  public char OutEcapsDocumentMkAcademicYear_AS;
  /**
   * Dynamic attribute for: OutEcapsDocumentMkAcademicYear
   **/
  public DynamicAttr OutEcapsDocumentMkAcademicYear_AT;
  /**
   * Attribute for: OutEcapsDocumentMkAcademicYear
   **/
  public short OutEcapsDocumentMkAcademicYear;
  /**
   * Attribute missing flag for: OutEcapsDocumentSemester
   **/
  public char OutEcapsDocumentSemester_AS;
  /**
   * Dynamic attribute for: OutEcapsDocumentSemester
   **/
  public DynamicAttr OutEcapsDocumentSemester_AT;
  /**
   * Attribute for: OutEcapsDocumentSemester
   **/
  public short OutEcapsDocumentSemester;
  /**
   * Attribute missing flag for: OutEcapsDocumentMkStudyUnitCode
   **/
  public char OutEcapsDocumentMkStudyUnitCode_AS;
  /**
   * Dynamic attribute for: OutEcapsDocumentMkStudyUnitCode
   **/
  public DynamicAttr OutEcapsDocumentMkStudyUnitCode_AT;
  /**
   * Attribute for: OutEcapsDocumentMkStudyUnitCode
   **/
  public String OutEcapsDocumentMkStudyUnitCode;
  /**
   * Attribute missing flag for: OutEcapsDocumentStatusGc31
   **/
  public char OutEcapsDocumentStatusGc31_AS;
  /**
   * Dynamic attribute for: OutEcapsDocumentStatusGc31
   **/
  public DynamicAttr OutEcapsDocumentStatusGc31_AT;
  /**
   * Attribute for: OutEcapsDocumentStatusGc31
   **/
  public String OutEcapsDocumentStatusGc31;
  /**
   * Attribute missing flag for: OutEcapsDocumentSignedTimestamp
   **/
  public char OutEcapsDocumentSignedTimestamp_AS;
  /**
   * Dynamic attribute for: OutEcapsDocumentSignedTimestamp
   **/
  public DynamicAttr OutEcapsDocumentSignedTimestamp_AT;
  /**
   * Attribute for: OutEcapsDocumentSignedTimestamp
   **/
  public String OutEcapsDocumentSignedTimestamp;
  // Repeating GV:  OUT_ATTRIBUTE_GROUP
  //     Repeats: 50 times
  /**
   * Repeating group view count
   **/
  public int OutAttributeGroup_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char OutAttributeGroup_AC[] = new char[50];
  // Entity View: OUT_GRP_DOC_DEP_IND
  //        Type: WS_ECAPS
  /**
   * Attribute missing flag for: OutGrpDocDepIndWsEcapsString1
   **/
  public char OutGrpDocDepIndWsEcapsString1_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpDocDepIndWsEcapsString1
   **/
  public DynamicAttr OutGrpDocDepIndWsEcapsString1_AT[] = new DynamicAttr[50];
  /**
   * Attribute for: OutGrpDocDepIndWsEcapsString1
   **/
  public String OutGrpDocDepIndWsEcapsString1[] = new String[50];
  // Entity View: OUT_GRP
  //        Type: ECAPS_DOCUMENT_ATTR
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrField
   **/
  public char OutGrpEcapsDocumentAttrField_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrField
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrField_AT[] = new DynamicAttr[50];
  /**
   * Attribute for: OutGrpEcapsDocumentAttrField
   **/
  public String OutGrpEcapsDocumentAttrField[] = new String[50];
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrFieldValue
   **/
  public char OutGrpEcapsDocumentAttrFieldValue_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrFieldValue
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrFieldValue_AT[] = new DynamicAttr[
    50];
  /**
   * Attribute for: OutGrpEcapsDocumentAttrFieldValue
   **/
  public String OutGrpEcapsDocumentAttrFieldValue[] = new String[50];
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrCreatedTimestamp
   **/
  public char OutGrpEcapsDocumentAttrCreatedTimestamp_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrCreatedTimestamp
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrCreatedTimestamp_AT[] = new 
    DynamicAttr[50];
  /**
   * Attribute for: OutGrpEcapsDocumentAttrCreatedTimestamp
   **/
  public String OutGrpEcapsDocumentAttrCreatedTimestamp[] = new String[50];
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrExamYear
   **/
  public char OutGrpEcapsDocumentAttrExamYear_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrExamYear
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrExamYear_AT[] = new DynamicAttr[50]
    ;
  /**
   * Attribute for: OutGrpEcapsDocumentAttrExamYear
   **/
  public short OutGrpEcapsDocumentAttrExamYear[] = new short[50];
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrExamPeriod
   **/
  public char OutGrpEcapsDocumentAttrExamPeriod_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrExamPeriod
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrExamPeriod_AT[] = new DynamicAttr[
    50];
  /**
   * Attribute for: OutGrpEcapsDocumentAttrExamPeriod
   **/
  public short OutGrpEcapsDocumentAttrExamPeriod[] = new short[50];
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrDepenencyIndGc30
   **/
  public char OutGrpEcapsDocumentAttrDepenencyIndGc30_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrDepenencyIndGc30
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrDepenencyIndGc30_AT[] = new 
    DynamicAttr[50];
  /**
   * Attribute for: OutGrpEcapsDocumentAttrDepenencyIndGc30
   **/
  public String OutGrpEcapsDocumentAttrDepenencyIndGc30[] = new String[50];
  /**
   * Attribute missing flag for: OutGrpEcapsDocumentAttrNovellUserId
   **/
  public char OutGrpEcapsDocumentAttrNovellUserId_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpEcapsDocumentAttrNovellUserId
   **/
  public DynamicAttr OutGrpEcapsDocumentAttrNovellUserId_AT[] = new DynamicAttr[
    50];
  /**
   * Attribute for: OutGrpEcapsDocumentAttrNovellUserId
   **/
  public String OutGrpEcapsDocumentAttrNovellUserId[] = new String[50];
  // Entity View: OUT_GRP_ERR
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: OutGrpErrCsfStringsString10
   **/
  public char OutGrpErrCsfStringsString10_AS[] = new char[50];
  /**
   * Dynamic attribute for: OutGrpErrCsfStringsString10
   **/
  public DynamicAttr OutGrpErrCsfStringsString10_AT[] = new DynamicAttr[50];
  /**
   * Attribute for: OutGrpErrCsfStringsString10
   **/
  public String OutGrpErrCsfStringsString10[] = new String[50];
  // Entity View: OUT_ERRMSG
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: OutErrmsgCsfStringsString500
   **/
  public char OutErrmsgCsfStringsString500_AS;
  /**
   * Dynamic attribute for: OutErrmsgCsfStringsString500
   **/
  public DynamicAttr OutErrmsgCsfStringsString500_AT;
  /**
   * Attribute for: OutErrmsgCsfStringsString500
   **/
  public String OutErrmsgCsfStringsString500;
  /**
   * Default Constructor
   **/
  
  public ECDCQ01S_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public ECDCQ01S_OA(ECDCQ01S_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static ECDCQ01S_OA getInstance()
  {
    return new ECDCQ01S_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new ECDCQ01S_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    OutEcapsDocumentMkAcademicYear_AT = null;
    OutEcapsDocumentMkAcademicYear_AS = ' ';
    OutEcapsDocumentMkAcademicYear = 0;
    OutEcapsDocumentSemester_AT = null;
    OutEcapsDocumentSemester_AS = ' ';
    OutEcapsDocumentSemester = 0;
    OutEcapsDocumentMkStudyUnitCode_AT = null;
    OutEcapsDocumentMkStudyUnitCode_AS = ' ';
    OutEcapsDocumentMkStudyUnitCode = "";
    OutEcapsDocumentStatusGc31_AT = null;
    OutEcapsDocumentStatusGc31_AS = ' ';
    OutEcapsDocumentStatusGc31 = "";
    OutEcapsDocumentSignedTimestamp_AT = null;
    OutEcapsDocumentSignedTimestamp_AS = ' ';
    OutEcapsDocumentSignedTimestamp = "00000000000000000000";
    OutAttributeGroup_MA = 0;
    for(int a = 0; a < 50; a++)
    {
      OutAttributeGroup_AC[a] = ' ';
      OutGrpDocDepIndWsEcapsString1_AT[a] = null;
      OutGrpDocDepIndWsEcapsString1_AS[a] = ' ';
      OutGrpDocDepIndWsEcapsString1[a] = " ";
      OutGrpEcapsDocumentAttrField_AT[a] = null;
      OutGrpEcapsDocumentAttrField_AS[a] = ' ';
      OutGrpEcapsDocumentAttrField[a] = "";
      OutGrpEcapsDocumentAttrFieldValue_AT[a] = null;
      OutGrpEcapsDocumentAttrFieldValue_AS[a] = ' ';
      OutGrpEcapsDocumentAttrFieldValue[a] = "";
      OutGrpEcapsDocumentAttrCreatedTimestamp_AT[a] = null;
      OutGrpEcapsDocumentAttrCreatedTimestamp_AS[a] = ' ';
      OutGrpEcapsDocumentAttrCreatedTimestamp[a] = "00000000000000000000";
      OutGrpEcapsDocumentAttrExamYear_AT[a] = null;
      OutGrpEcapsDocumentAttrExamYear_AS[a] = ' ';
      OutGrpEcapsDocumentAttrExamYear[a] = 0;
      OutGrpEcapsDocumentAttrExamPeriod_AT[a] = null;
      OutGrpEcapsDocumentAttrExamPeriod_AS[a] = ' ';
      OutGrpEcapsDocumentAttrExamPeriod[a] = 0;
      OutGrpEcapsDocumentAttrDepenencyIndGc30_AT[a] = null;
      OutGrpEcapsDocumentAttrDepenencyIndGc30_AS[a] = ' ';
      OutGrpEcapsDocumentAttrDepenencyIndGc30[a] = "";
      OutGrpEcapsDocumentAttrNovellUserId_AT[a] = null;
      OutGrpEcapsDocumentAttrNovellUserId_AS[a] = ' ';
      OutGrpEcapsDocumentAttrNovellUserId[a] = "";
      OutGrpErrCsfStringsString10_AT[a] = null;
      OutGrpErrCsfStringsString10_AS[a] = ' ';
      OutGrpErrCsfStringsString10[a] = "          ";
    }
    OutErrmsgCsfStringsString500_AT = null;
    OutErrmsgCsfStringsString500_AS = ' ';
    OutErrmsgCsfStringsString500 = "";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "OutEcapsDocument", "EcapsDocument", 
          "MkAcademicYear", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)
          0, null), 
        new VDFEntry((int)2, "", "OutEcapsDocument", "EcapsDocument", "Semester"
          , VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)3, "", "OutEcapsDocument", "EcapsDocument", 
          "MkStudyUnitCode", VDFEntry.TYPE_STRING, (short)1, (short)0, 7, (
          short)0, null), 
        new VDFEntry((int)4, "", "OutEcapsDocument", "EcapsDocument", 
          "StatusGc31", VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, 
          null), 
        new VDFEntry((int)5, "", "OutEcapsDocument", "EcapsDocument", 
          "SignedTimestamp", VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (
          short)0, null), 
        new VDFEntry((int)6, "OutAttributeGroup", "", "", "MA", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)7, "OutAttributeGroup", "", "", "AC", 
          VDFEntry.TYPE_CHAR, (short)50, (short)0, 1, (short)0, null), 
        new VDFEntry((int)8, "OutAttributeGroup", "OutGrpDocDepIndWsEcaps", 
          "WsEcaps", "String1", VDFEntry.TYPE_STRING, (short)50, (short)0, 1, (
          short)0, null), 
        new VDFEntry((int)9, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "Field", VDFEntry.TYPE_STRING, (short)50, (short)
          0, 20, (short)0, null), 
        new VDFEntry((int)10, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "FieldValue", VDFEntry.TYPE_STRING, (short)50, (
          short)0, 100, (short)0, null), 
        new VDFEntry((int)11, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "CreatedTimestamp", VDFEntry.TYPE_TIMESTAMP, (
          short)50, (short)0, 20, (short)0, null), 
        new VDFEntry((int)12, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "ExamYear", VDFEntry.TYPE_SHORT, (short)50, (
          short)0, 2, (short)0, null), 
        new VDFEntry((int)13, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "ExamPeriod", VDFEntry.TYPE_SHORT, (short)50, (
          short)0, 2, (short)0, null), 
        new VDFEntry((int)14, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "DepenencyIndGc30", VDFEntry.TYPE_STRING, (short)
          50, (short)0, 10, (short)0, null), 
        new VDFEntry((int)15, "OutAttributeGroup", "OutGrpEcapsDocumentAttr", 
          "EcapsDocumentAttr", "NovellUserId", VDFEntry.TYPE_STRING, (short)50, 
          (short)0, 10, (short)0, null), 
        new VDFEntry((int)16, "OutAttributeGroup", "OutGrpErrCsfStrings", 
          "CsfStrings", "String10", VDFEntry.TYPE_STRING, (short)50, (short)0, 
          10, (short)0, null), 
        new VDFEntry((int)17, "", "OutErrmsgCsfStrings", "CsfStrings", 
          "String500", VDFEntry.TYPE_STRING, (short)1, (short)0, 500, (short)0, 
          null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      OutEcapsDocumentMkAcademicYear = ((Short)vdf.getEntries()[0].getDataValue(
        ).getObject()).shortValue();
    }
    else 
    {
      OutEcapsDocumentMkAcademicYear = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      OutEcapsDocumentSemester = ((Short)vdf.getEntries()[1].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      OutEcapsDocumentSemester = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      OutEcapsDocumentMkStudyUnitCode = ((String)vdf.getEntries()[2]
        .getDataValue().getObject());
    }
    else 
    {
      OutEcapsDocumentMkStudyUnitCode = "";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      OutEcapsDocumentStatusGc31 = ((String)vdf.getEntries()[3].getDataValue()
        .getObject());
    }
    else 
    {
      OutEcapsDocumentStatusGc31 = "";
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      OutEcapsDocumentSignedTimestamp = ((String)vdf.getEntries()[4]
        .getDataValue().getObject());
    }
    else 
    {
      OutEcapsDocumentSignedTimestamp = "00000000000000000000";
    }
    // group view current cardinality
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      OutAttributeGroup_MA = ((Integer)vdf.getEntries()[5].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      OutAttributeGroup_MA = ' ';
    }
    // group view active flags
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[6].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutAttributeGroup_AC[adim0] = ((Character)((VDFEntryObject [])
          vdf.getEntries()[6].getDataValue().getObject())[adim0].getObject())
          .charValue();
      }
      else 
      {
        OutAttributeGroup_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[7].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpDocDepIndWsEcapsString1[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[7].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGrpDocDepIndWsEcapsString1[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[8].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrField[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[8].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGrpEcapsDocumentAttrField[adim0] = "";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[9].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrFieldValue[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[9].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGrpEcapsDocumentAttrFieldValue[adim0] = "";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[10].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrCreatedTimestamp[adim0] = ((String)((
          VDFEntryObject [])vdf.getEntries()[10].getDataValue().getObject())[
          adim0].getObject());
      }
      else 
      {
        OutGrpEcapsDocumentAttrCreatedTimestamp[adim0] = "00000000000000000000"
          ;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[11].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrExamYear[adim0] = ((Short)((VDFEntryObject [])
          vdf.getEntries()[11].getDataValue().getObject())[adim0].getObject())
          .shortValue();
      }
      else 
      {
        OutGrpEcapsDocumentAttrExamYear[adim0] = 0;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[12].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrExamPeriod[adim0] = ((Short)((VDFEntryObject [])
          vdf.getEntries()[12].getDataValue().getObject())[adim0].getObject())
          .shortValue();
      }
      else 
      {
        OutGrpEcapsDocumentAttrExamPeriod[adim0] = 0;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrDepenencyIndGc30[adim0] = ((String)((
          VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[
          adim0].getObject());
      }
      else 
      {
        OutGrpEcapsDocumentAttrDepenencyIndGc30[adim0] = "";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[14].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpEcapsDocumentAttrNovellUserId[adim0] = ((String)((VDFEntryObject [
          ])vdf.getEntries()[14].getDataValue().getObject())[adim0].getObject())
          ;
      }
      else 
      {
        OutGrpEcapsDocumentAttrNovellUserId[adim0] = "";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutAttributeGroup_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[15].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGrpErrCsfStringsString10[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[15].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGrpErrCsfStringsString10[adim0] = "          ";
      }
    }
    // predicate view item
    if ( vdf.getEntries()[16].getDataValue().getObject() != null )
    {
      OutErrmsgCsfStringsString500 = ((String)vdf.getEntries()[16].getDataValue(
        ).getObject());
    }
    else 
    {
      OutErrmsgCsfStringsString500 = "";
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(new Short(
      OutEcapsDocumentMkAcademicYear));
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(new Short(
      OutEcapsDocumentSemester));
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(
      OutEcapsDocumentMkStudyUnitCode);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(OutEcapsDocumentStatusGc31);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(
      OutEcapsDocumentSignedTimestamp);
    // group view current cardinality
    vdf.getEntries()[5].getDataValue().setObject(new Integer(
      OutAttributeGroup_MA));
    // group view active flags
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      if ( adim0 < OutAttributeGroup_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[6].getDataValue().getObject())[
          adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[6].getDataValue().getObject())[
          adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[6].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[7].getDataValue().getObject())[adim0]
        .setObject(OutGrpDocDepIndWsEcapsString1[adim0]);
    }
    vdf.getEntries()[7].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[8].getDataValue().getObject())[adim0]
        .setObject(OutGrpEcapsDocumentAttrField[adim0]);
    }
    vdf.getEntries()[8].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[9].getDataValue().getObject())[adim0]
        .setObject(OutGrpEcapsDocumentAttrFieldValue[adim0]);
    }
    vdf.getEntries()[9].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[10].getDataValue().getObject())[
        adim0].setObject(OutGrpEcapsDocumentAttrCreatedTimestamp[adim0]);
    }
    vdf.getEntries()[10].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[11].getDataValue().getObject())[
        adim0].setObject(new Short(OutGrpEcapsDocumentAttrExamYear[adim0]));
    }
    vdf.getEntries()[11].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[12].getDataValue().getObject())[
        adim0].setObject(new Short(OutGrpEcapsDocumentAttrExamPeriod[adim0]));
    }
    vdf.getEntries()[12].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[13].getDataValue().getObject())[
        adim0].setObject(OutGrpEcapsDocumentAttrDepenencyIndGc30[adim0]);
    }
    vdf.getEntries()[13].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[14].getDataValue().getObject())[
        adim0].setObject(OutGrpEcapsDocumentAttrNovellUserId[adim0]);
    }
    vdf.getEntries()[14].setCountUsed((short)OutAttributeGroup_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 50; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[15].getDataValue().getObject())[
        adim0].setObject(OutGrpErrCsfStringsString10[adim0]);
    }
    vdf.getEntries()[15].setCountUsed((short)OutAttributeGroup_MA);
    // predicate view item
    vdf.getEntries()[16].getDataValue().setObject(OutErrmsgCsfStringsString500)
      ;
    return(vdf);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((ECDCQ01S_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(ECDCQ01S_OA orig)
  {
    OutEcapsDocumentMkAcademicYear_AT = orig.OutEcapsDocumentMkAcademicYear_AT;
    OutEcapsDocumentMkAcademicYear_AS = orig.OutEcapsDocumentMkAcademicYear_AS;
    OutEcapsDocumentMkAcademicYear = orig.OutEcapsDocumentMkAcademicYear;
    OutEcapsDocumentSemester_AT = orig.OutEcapsDocumentSemester_AT;
    OutEcapsDocumentSemester_AS = orig.OutEcapsDocumentSemester_AS;
    OutEcapsDocumentSemester = orig.OutEcapsDocumentSemester;
    OutEcapsDocumentMkStudyUnitCode_AT = 
      orig.OutEcapsDocumentMkStudyUnitCode_AT;
    OutEcapsDocumentMkStudyUnitCode_AS = 
      orig.OutEcapsDocumentMkStudyUnitCode_AS;
    OutEcapsDocumentMkStudyUnitCode = orig.OutEcapsDocumentMkStudyUnitCode;
    OutEcapsDocumentStatusGc31_AT = orig.OutEcapsDocumentStatusGc31_AT;
    OutEcapsDocumentStatusGc31_AS = orig.OutEcapsDocumentStatusGc31_AS;
    OutEcapsDocumentStatusGc31 = orig.OutEcapsDocumentStatusGc31;
    OutEcapsDocumentSignedTimestamp_AT = 
      orig.OutEcapsDocumentSignedTimestamp_AT;
    OutEcapsDocumentSignedTimestamp_AS = 
      orig.OutEcapsDocumentSignedTimestamp_AS;
    OutEcapsDocumentSignedTimestamp = orig.OutEcapsDocumentSignedTimestamp;
    OutAttributeGroup_MA = orig.OutAttributeGroup_MA;
    for(int a = 0; a < 50; a++)
    {
      OutAttributeGroup_AC[a] = orig.OutAttributeGroup_AC[a];
      OutGrpDocDepIndWsEcapsString1_AT[a] = 
        orig.OutGrpDocDepIndWsEcapsString1_AT[a];
      OutGrpDocDepIndWsEcapsString1_AS[a] = 
        orig.OutGrpDocDepIndWsEcapsString1_AS[a];
      OutGrpDocDepIndWsEcapsString1[a] = orig.OutGrpDocDepIndWsEcapsString1[a];
      OutGrpEcapsDocumentAttrField_AT[a] = orig.OutGrpEcapsDocumentAttrField_AT[
        a];
      OutGrpEcapsDocumentAttrField_AS[a] = orig.OutGrpEcapsDocumentAttrField_AS[
        a];
      OutGrpEcapsDocumentAttrField[a] = orig.OutGrpEcapsDocumentAttrField[a];
      OutGrpEcapsDocumentAttrFieldValue_AT[a] = 
        orig.OutGrpEcapsDocumentAttrFieldValue_AT[a];
      OutGrpEcapsDocumentAttrFieldValue_AS[a] = 
        orig.OutGrpEcapsDocumentAttrFieldValue_AS[a];
      OutGrpEcapsDocumentAttrFieldValue[a] = 
        orig.OutGrpEcapsDocumentAttrFieldValue[a];
      OutGrpEcapsDocumentAttrCreatedTimestamp_AT[a] = 
        orig.OutGrpEcapsDocumentAttrCreatedTimestamp_AT[a];
      OutGrpEcapsDocumentAttrCreatedTimestamp_AS[a] = 
        orig.OutGrpEcapsDocumentAttrCreatedTimestamp_AS[a];
      OutGrpEcapsDocumentAttrCreatedTimestamp[a] = 
        orig.OutGrpEcapsDocumentAttrCreatedTimestamp[a];
      OutGrpEcapsDocumentAttrExamYear_AT[a] = 
        orig.OutGrpEcapsDocumentAttrExamYear_AT[a];
      OutGrpEcapsDocumentAttrExamYear_AS[a] = 
        orig.OutGrpEcapsDocumentAttrExamYear_AS[a];
      OutGrpEcapsDocumentAttrExamYear[a] = orig.OutGrpEcapsDocumentAttrExamYear[
        a];
      OutGrpEcapsDocumentAttrExamPeriod_AT[a] = 
        orig.OutGrpEcapsDocumentAttrExamPeriod_AT[a];
      OutGrpEcapsDocumentAttrExamPeriod_AS[a] = 
        orig.OutGrpEcapsDocumentAttrExamPeriod_AS[a];
      OutGrpEcapsDocumentAttrExamPeriod[a] = 
        orig.OutGrpEcapsDocumentAttrExamPeriod[a];
      OutGrpEcapsDocumentAttrDepenencyIndGc30_AT[a] = 
        orig.OutGrpEcapsDocumentAttrDepenencyIndGc30_AT[a];
      OutGrpEcapsDocumentAttrDepenencyIndGc30_AS[a] = 
        orig.OutGrpEcapsDocumentAttrDepenencyIndGc30_AS[a];
      OutGrpEcapsDocumentAttrDepenencyIndGc30[a] = 
        orig.OutGrpEcapsDocumentAttrDepenencyIndGc30[a];
      OutGrpEcapsDocumentAttrNovellUserId_AT[a] = 
        orig.OutGrpEcapsDocumentAttrNovellUserId_AT[a];
      OutGrpEcapsDocumentAttrNovellUserId_AS[a] = 
        orig.OutGrpEcapsDocumentAttrNovellUserId_AS[a];
      OutGrpEcapsDocumentAttrNovellUserId[a] = 
        orig.OutGrpEcapsDocumentAttrNovellUserId[a];
      OutGrpErrCsfStringsString10_AT[a] = orig.OutGrpErrCsfStringsString10_AT[a]
        ;
      OutGrpErrCsfStringsString10_AS[a] = orig.OutGrpErrCsfStringsString10_AS[a]
        ;
      OutGrpErrCsfStringsString10[a] = orig.OutGrpErrCsfStringsString10[a];
    }
    OutErrmsgCsfStringsString500_AT = orig.OutErrmsgCsfStringsString500_AT;
    OutErrmsgCsfStringsString500_AS = orig.OutErrmsgCsfStringsString500_AS;
    OutErrmsgCsfStringsString500 = orig.OutErrmsgCsfStringsString500;
  }
}
