package Exsug07h;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                            CA Gen r8
//
//           Copyright (c) 2017 CA. All rights reserved.
//
//    Name: EXSUG07S_IA                      Date: 2017/07/07
//    User: tmockek                          Time: 13:56:05
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen80.vwrt.*;
import com.ca.gen80.vwrt.types.*;
import com.ca.gen80.vwrt.vdf.*;
import com.ca.gen80.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: EXSUG07S_IA
 **/
public class EXSUG07S_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN_INTERNET_FLAG
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InInternetFlagCsfStringsString1
   **/
  public char InInternetFlagCsfStringsString1_AS;
  /**
   * Attribute for: InInternetFlagCsfStringsString1
   **/
  public String InInternetFlagCsfStringsString1;
  // Entity View: IN_FAX_NAME
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InFaxNameCsfStringsString132
   **/
  public char InFaxNameCsfStringsString132_AS;
  /**
   * Attribute for: InFaxNameCsfStringsString132
   **/
  public String InFaxNameCsfStringsString132;
  // Entity View: IN_FAX_NO
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InFaxNoCsfStringsString132
   **/
  public char InFaxNoCsfStringsString132_AS;
  /**
   * Attribute for: InFaxNoCsfStringsString132
   **/
  public String InFaxNoCsfStringsString132;
  // Entity View: IN_TO_EMAIL_ADDRESS
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InToEmailAddressCsfStringsString132
   **/
  public char InToEmailAddressCsfStringsString132_AS;
  /**
   * Attribute for: InToEmailAddressCsfStringsString132
   **/
  public String InToEmailAddressCsfStringsString132;
  // Entity View: IN_FROM_EMAIL_ADDRESS
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InFromEmailAddressCsfStringsString132
   **/
  public char InFromEmailAddressCsfStringsString132_AS;
  /**
   * Attribute for: InFromEmailAddressCsfStringsString132
   **/
  public String InFromEmailAddressCsfStringsString132;
  // Entity View: IN_SECURITY
  //        Type: WS_WORKSTATION
  /**
   * Attribute missing flag for: InSecurityWsWorkstationCode
   **/
  public char InSecurityWsWorkstationCode_AS;
  /**
   * Attribute for: InSecurityWsWorkstationCode
   **/
  public String InSecurityWsWorkstationCode;
  // Entity View: IN_PRACTICAL_FLAG
  //        Type: WS_PRACTICALS_VALUES
  /**
   * Attribute missing flag for: InPracticalFlagWsPracticalsValuesString1
   **/
  public char InPracticalFlagWsPracticalsValuesString1_AS;
  /**
   * Attribute for: InPracticalFlagWsPracticalsValuesString1
   **/
  public String InPracticalFlagWsPracticalsValuesString1;
  // Entity View: IN
  //        Type: CSF_CLIENT_SERVER_COMMUNICATIONS
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientVersionNumber
   **/
  public char InCsfClientServerCommunicationsClientVersionNumber_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientVersionNumber
   **/
  public short InCsfClientServerCommunicationsClientVersionNumber;
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientRevisionNumber
   **/
  public char InCsfClientServerCommunicationsClientRevisionNumber_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientRevisionNumber
   **/
  public short InCsfClientServerCommunicationsClientRevisionNumber;
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public char InCsfClientServerCommunicationsClientDevelopmentPhase_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public String InCsfClientServerCommunicationsClientDevelopmentPhase;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsAction
   **/
  public char InCsfClientServerCommunicationsAction_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsAction
   **/
  public String InCsfClientServerCommunicationsAction;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public char InCsfClientServerCommunicationsClientIsGuiFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public String InCsfClientServerCommunicationsClientIsGuiFlag;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientDate
   **/
  public char InCsfClientServerCommunicationsClientDate_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientDate
   **/
  public int InCsfClientServerCommunicationsClientDate;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientTime
   **/
  public char InCsfClientServerCommunicationsClientTime_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientTime
   **/
  public int InCsfClientServerCommunicationsClientTime;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientTimestamp
   **/
  public char InCsfClientServerCommunicationsClientTimestamp_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientTimestamp
   **/
  public String InCsfClientServerCommunicationsClientTimestamp;
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientTransactionCode
   **/
  public char InCsfClientServerCommunicationsClientTransactionCode_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientTransactionCode
   **/
  public String InCsfClientServerCommunicationsClientTransactionCode;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientUserId
   **/
  public char InCsfClientServerCommunicationsClientUserId_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientUserId
   **/
  public String InCsfClientServerCommunicationsClientUserId;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsListLinkFlag
   **/
  public char InCsfClientServerCommunicationsListLinkFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsListLinkFlag
   **/
  public String InCsfClientServerCommunicationsListLinkFlag;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsMaintLinkFlag
   **/
  public char InCsfClientServerCommunicationsMaintLinkFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsMaintLinkFlag
   **/
  public String InCsfClientServerCommunicationsMaintLinkFlag;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsFirstpassFlag
   **/
  public char InCsfClientServerCommunicationsFirstpassFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsFirstpassFlag
   **/
  public String InCsfClientServerCommunicationsFirstpassFlag;
  // Entity View: IN_SECURITY
  //        Type: WS_PRINTER
  /**
   * Attribute missing flag for: InSecurityWsPrinterCode
   **/
  public char InSecurityWsPrinterCode_AS;
  /**
   * Attribute for: InSecurityWsPrinterCode
   **/
  public String InSecurityWsPrinterCode;
  // Entity View: IN_SECURITY
  //        Type: WS_USER
  /**
   * Attribute missing flag for: InSecurityWsUserNumber
   **/
  public char InSecurityWsUserNumber_AS;
  /**
   * Attribute for: InSecurityWsUserNumber
   **/
  public int InSecurityWsUserNumber;
  /**
   * Attribute missing flag for: InSecurityWsUserNumberOfLogonAttempts
   **/
  public char InSecurityWsUserNumberOfLogonAttempts_AS;
  /**
   * Attribute for: InSecurityWsUserNumberOfLogonAttempts
   **/
  public short InSecurityWsUserNumberOfLogonAttempts;
  /**
   * Attribute missing flag for: InSecurityWsUserLoggedOnFlag
   **/
  public char InSecurityWsUserLoggedOnFlag_AS;
  /**
   * Attribute for: InSecurityWsUserLoggedOnFlag
   **/
  public String InSecurityWsUserLoggedOnFlag;
  /**
   * Attribute missing flag for: InSecurityWsUserInUsedFlag
   **/
  public char InSecurityWsUserInUsedFlag_AS;
  /**
   * Attribute for: InSecurityWsUserInUsedFlag
   **/
  public String InSecurityWsUserInUsedFlag;
  /**
   * Attribute missing flag for: InSecurityWsUserLastLogonDate
   **/
  public char InSecurityWsUserLastLogonDate_AS;
  /**
   * Attribute for: InSecurityWsUserLastLogonDate
   **/
  public int InSecurityWsUserLastLogonDate;
  /**
   * Attribute missing flag for: InSecurityWsUserName
   **/
  public char InSecurityWsUserName_AS;
  /**
   * Attribute for: InSecurityWsUserName
   **/
  public String InSecurityWsUserName;
  /**
   * Attribute missing flag for: InSecurityWsUserPersonnelNo
   **/
  public char InSecurityWsUserPersonnelNo_AS;
  /**
   * Attribute for: InSecurityWsUserPersonnelNo
   **/
  public String InSecurityWsUserPersonnelNo;
  /**
   * Attribute missing flag for: InSecurityWsUserPhoneNumber
   **/
  public char InSecurityWsUserPhoneNumber_AS;
  /**
   * Attribute for: InSecurityWsUserPhoneNumber
   **/
  public String InSecurityWsUserPhoneNumber;
  /**
   * Attribute missing flag for: InSecurityWsUserPassword
   **/
  public char InSecurityWsUserPassword_AS;
  /**
   * Attribute for: InSecurityWsUserPassword
   **/
  public String InSecurityWsUserPassword;
  // Entity View: IN
  //        Type: WS_STUDENT
  /**
   * Attribute missing flag for: InWsStudentSurname
   **/
  public char InWsStudentSurname_AS;
  /**
   * Attribute for: InWsStudentSurname
   **/
  public String InWsStudentSurname;
  /**
   * Attribute missing flag for: InWsStudentInitials
   **/
  public char InWsStudentInitials_AS;
  /**
   * Attribute for: InWsStudentInitials
   **/
  public String InWsStudentInitials;
  // Entity View: IN
  //        Type: STUDENT_ANNUAL_RECORD
  /**
   * Attribute missing flag for: InStudentAnnualRecordMkStudentNr
   **/
  public char InStudentAnnualRecordMkStudentNr_AS;
  /**
   * Attribute for: InStudentAnnualRecordMkStudentNr
   **/
  public int InStudentAnnualRecordMkStudentNr;
  // Entity View: IN
  //        Type: STUDENT_STUDY_UNIT
  /**
   * Attribute missing flag for: InStudentStudyUnitExamYear
   **/
  public char InStudentStudyUnitExamYear_AS;
  /**
   * Attribute for: InStudentStudyUnitExamYear
   **/
  public short InStudentStudyUnitExamYear;
  /**
   * Attribute missing flag for: InStudentStudyUnitMkExamPeriod
   **/
  public char InStudentStudyUnitMkExamPeriod_AS;
  /**
   * Attribute for: InStudentStudyUnitMkExamPeriod
   **/
  public short InStudentStudyUnitMkExamPeriod;
  // Entity View: IN_COMMENT1
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment1CsfStringsString100
   **/
  public char InComment1CsfStringsString100_AS;
  /**
   * Attribute for: InComment1CsfStringsString100
   **/
  public String InComment1CsfStringsString100;
  // Entity View: IN_COMMENT2
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment2CsfStringsString100
   **/
  public char InComment2CsfStringsString100_AS;
  /**
   * Attribute for: InComment2CsfStringsString100
   **/
  public String InComment2CsfStringsString100;
  // Entity View: IN_COMMENT3
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment3CsfStringsString100
   **/
  public char InComment3CsfStringsString100_AS;
  /**
   * Attribute for: InComment3CsfStringsString100
   **/
  public String InComment3CsfStringsString100;
  // Entity View: IN_COMMENT4
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment4CsfStringsString100
   **/
  public char InComment4CsfStringsString100_AS;
  /**
   * Attribute for: InComment4CsfStringsString100
   **/
  public String InComment4CsfStringsString100;
  // Entity View: IN_COMMENT5
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment5CsfStringsString100
   **/
  public char InComment5CsfStringsString100_AS;
  /**
   * Attribute for: InComment5CsfStringsString100
   **/
  public String InComment5CsfStringsString100;
  // Entity View: IN_COMMENT6
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment6CsfStringsString100
   **/
  public char InComment6CsfStringsString100_AS;
  /**
   * Attribute for: InComment6CsfStringsString100
   **/
  public String InComment6CsfStringsString100;
  // Entity View: IN_COMMENT7
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment7CsfStringsString100
   **/
  public char InComment7CsfStringsString100_AS;
  /**
   * Attribute for: InComment7CsfStringsString100
   **/
  public String InComment7CsfStringsString100;
  // Entity View: IN_COMMENT8
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment8CsfStringsString100
   **/
  public char InComment8CsfStringsString100_AS;
  /**
   * Attribute for: InComment8CsfStringsString100
   **/
  public String InComment8CsfStringsString100;
  // Entity View: IN_COMMENT9
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment9CsfStringsString100
   **/
  public char InComment9CsfStringsString100_AS;
  /**
   * Attribute for: InComment9CsfStringsString100
   **/
  public String InComment9CsfStringsString100;
  // Entity View: IN_COMMENT10
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment10CsfStringsString100
   **/
  public char InComment10CsfStringsString100_AS;
  /**
   * Attribute for: InComment10CsfStringsString100
   **/
  public String InComment10CsfStringsString100;
  // Entity View: IN_COMMENT11
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment11CsfStringsString100
   **/
  public char InComment11CsfStringsString100_AS;
  /**
   * Attribute for: InComment11CsfStringsString100
   **/
  public String InComment11CsfStringsString100;
  // Entity View: IN_COMMENT12
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InComment12CsfStringsString100
   **/
  public char InComment12CsfStringsString100_AS;
  /**
   * Attribute for: InComment12CsfStringsString100
   **/
  public String InComment12CsfStringsString100;
  // Entity View: IN_INVIGILATOR_ADDRESS
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InInvigilatorAddressCsfStringsString1
   **/
  public char InInvigilatorAddressCsfStringsString1_AS;
  /**
   * Attribute for: InInvigilatorAddressCsfStringsString1
   **/
  public String InInvigilatorAddressCsfStringsString1;
  /**
   * Default Constructor
   **/
  
  public EXSUG07S_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public EXSUG07S_IA(EXSUG07S_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static EXSUG07S_IA getInstance()
  {
    return new EXSUG07S_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new EXSUG07S_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InInternetFlagCsfStringsString1_AS = ' ';
    InInternetFlagCsfStringsString1 = " ";
    InFaxNameCsfStringsString132_AS = ' ';
    InFaxNameCsfStringsString132 = 
"                                                                                                                                    "
      ;
    InFaxNoCsfStringsString132_AS = ' ';
    InFaxNoCsfStringsString132 = 
"                                                                                                                                    "
      ;
    InToEmailAddressCsfStringsString132_AS = ' ';
    InToEmailAddressCsfStringsString132 = 
"                                                                                                                                    "
      ;
    InFromEmailAddressCsfStringsString132_AS = ' ';
    InFromEmailAddressCsfStringsString132 = 
"                                                                                                                                    "
      ;
    InSecurityWsWorkstationCode_AS = ' ';
    InSecurityWsWorkstationCode = "";
    InPracticalFlagWsPracticalsValuesString1_AS = ' ';
    InPracticalFlagWsPracticalsValuesString1 = " ";
    InCsfClientServerCommunicationsClientVersionNumber_AS = ' ';
    InCsfClientServerCommunicationsClientVersionNumber = 0;
    InCsfClientServerCommunicationsClientRevisionNumber_AS = ' ';
    InCsfClientServerCommunicationsClientRevisionNumber = 0;
    InCsfClientServerCommunicationsClientDevelopmentPhase_AS = ' ';
    InCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    InCsfClientServerCommunicationsAction_AS = ' ';
    InCsfClientServerCommunicationsAction = "  ";
    InCsfClientServerCommunicationsClientIsGuiFlag_AS = ' ';
    InCsfClientServerCommunicationsClientIsGuiFlag = " ";
    InCsfClientServerCommunicationsClientDate_AS = ' ';
    InCsfClientServerCommunicationsClientDate = 00000000;
    InCsfClientServerCommunicationsClientTime_AS = ' ';
    InCsfClientServerCommunicationsClientTime = 00000000;
    InCsfClientServerCommunicationsClientTimestamp_AS = ' ';
    InCsfClientServerCommunicationsClientTimestamp = "00000000000000000000";
    InCsfClientServerCommunicationsClientTransactionCode_AS = ' ';
    InCsfClientServerCommunicationsClientTransactionCode = "        ";
    InCsfClientServerCommunicationsClientUserId_AS = ' ';
    InCsfClientServerCommunicationsClientUserId = "        ";
    InCsfClientServerCommunicationsListLinkFlag_AS = ' ';
    InCsfClientServerCommunicationsListLinkFlag = " ";
    InCsfClientServerCommunicationsMaintLinkFlag_AS = ' ';
    InCsfClientServerCommunicationsMaintLinkFlag = " ";
    InCsfClientServerCommunicationsFirstpassFlag_AS = ' ';
    InCsfClientServerCommunicationsFirstpassFlag = " ";
    InSecurityWsPrinterCode_AS = ' ';
    InSecurityWsPrinterCode = "          ";
    InSecurityWsUserNumber_AS = ' ';
    InSecurityWsUserNumber = 0;
    InSecurityWsUserNumberOfLogonAttempts_AS = ' ';
    InSecurityWsUserNumberOfLogonAttempts = 0;
    InSecurityWsUserLoggedOnFlag_AS = ' ';
    InSecurityWsUserLoggedOnFlag = " ";
    InSecurityWsUserInUsedFlag_AS = ' ';
    InSecurityWsUserInUsedFlag = " ";
    InSecurityWsUserLastLogonDate_AS = ' ';
    InSecurityWsUserLastLogonDate = 00000000;
    InSecurityWsUserName_AS = ' ';
    InSecurityWsUserName = "                            ";
    InSecurityWsUserPersonnelNo_AS = ' ';
    InSecurityWsUserPersonnelNo = "          ";
    InSecurityWsUserPhoneNumber_AS = ' ';
    InSecurityWsUserPhoneNumber = "                    ";
    InSecurityWsUserPassword_AS = ' ';
    InSecurityWsUserPassword = "            ";
    InWsStudentSurname_AS = ' ';
    InWsStudentSurname = "                            ";
    InWsStudentInitials_AS = ' ';
    InWsStudentInitials = "          ";
    InStudentAnnualRecordMkStudentNr_AS = ' ';
    InStudentAnnualRecordMkStudentNr = 0;
    InStudentStudyUnitExamYear_AS = ' ';
    InStudentStudyUnitExamYear = 0;
    InStudentStudyUnitMkExamPeriod_AS = ' ';
    InStudentStudyUnitMkExamPeriod = 0;
    InComment1CsfStringsString100_AS = ' ';
    InComment1CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment2CsfStringsString100_AS = ' ';
    InComment2CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment3CsfStringsString100_AS = ' ';
    InComment3CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment4CsfStringsString100_AS = ' ';
    InComment4CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment5CsfStringsString100_AS = ' ';
    InComment5CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment6CsfStringsString100_AS = ' ';
    InComment6CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment7CsfStringsString100_AS = ' ';
    InComment7CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment8CsfStringsString100_AS = ' ';
    InComment8CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment9CsfStringsString100_AS = ' ';
    InComment9CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment10CsfStringsString100_AS = ' ';
    InComment10CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment11CsfStringsString100_AS = ' ';
    InComment11CsfStringsString100 = 
"                                                                                                    "
      ;
    InComment12CsfStringsString100_AS = ' ';
    InComment12CsfStringsString100 = 
"                                                                                                    "
      ;
    InInvigilatorAddressCsfStringsString1_AS = ' ';
    InInvigilatorAddressCsfStringsString1 = " ";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InInternetFlagCsfStrings", "CsfStrings", 
          "String1", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, 
          null), 
        new VDFEntry((int)2, "", "InFaxNameCsfStrings", "CsfStrings", 
          "String132", VDFEntry.TYPE_STRING, (short)1, (short)0, 132, (short)0, 
          null), 
        new VDFEntry((int)3, "", "InFaxNoCsfStrings", "CsfStrings", "String132",
           VDFEntry.TYPE_STRING, (short)1, (short)0, 132, (short)0, null), 
        new VDFEntry((int)4, "", "InToEmailAddressCsfStrings", "CsfStrings", 
          "String132", VDFEntry.TYPE_STRING, (short)1, (short)0, 132, (short)0, 
          null), 
new VDFEntry((int)5, "", "InFromEmailAddressCsfStrings", "CsfStrings", 
          "String132", VDFEntry.TYPE_STRING, (short)1, (short)0, 132, (short)0, 
          null), 
        new VDFEntry((int)6, "", "InSecurityWsWorkstation", "WsWorkstation", 
          "Code", VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null),
           
        new VDFEntry((int)7, "", "InPracticalFlagWsPracticalsValues", 
          "WsPracticalsValues", "String1", VDFEntry.TYPE_STRING, (short)1, (
          short)0, 1, (short)0, null), 
        new VDFEntry((int)8, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientVersionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)9, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientRevisionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)10, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientDevelopmentPhase", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)11, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "Action", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)12, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientIsGuiFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)13, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientDate", VDFEntry.TYPE_DATE, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)14, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientTime", VDFEntry.TYPE_TIME, (
          short)1, (short)0, 6, (short)0, null), 
        new VDFEntry((int)15, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientTimestamp", 
          VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)16, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientTransactionCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)17, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientUserId", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)18, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ListLinkFlag", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)19, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "MaintLinkFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)20, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "FirstpassFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)21, "", "InSecurityWsPrinter", "WsPrinter", "Code", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)22, "", "InSecurityWsUser", "WsUser", "Number", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)23, "", "InSecurityWsUser", "WsUser", 
          "NumberOfLogonAttempts", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (
          short)0, null), 
        new VDFEntry((int)24, "", "InSecurityWsUser", "WsUser", "LoggedOnFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)25, "", "InSecurityWsUser", "WsUser", "InUsedFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)26, "", "InSecurityWsUser", "WsUser", "LastLogonDate",
           VDFEntry.TYPE_DATE, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)27, "", "InSecurityWsUser", "WsUser", "Name", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)28, "", "InSecurityWsUser", "WsUser", "PersonnelNo", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)29, "", "InSecurityWsUser", "WsUser", "PhoneNumber", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)30, "", "InSecurityWsUser", "WsUser", "Password", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 12, (short)0, null), 
        new VDFEntry((int)31, "", "InWsStudent", "WsStudent", "Surname", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)32, "", "InWsStudent", "WsStudent", "Initials", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)33, "", "InStudentAnnualRecord", "StudentAnnualRecord"
          , "MkStudentNr", VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, 
          null), 
        new VDFEntry((int)34, "", "InStudentStudyUnit", "StudentStudyUnit", 
          "ExamYear", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, 
          null), 
        new VDFEntry((int)35, "", "InStudentStudyUnit", "StudentStudyUnit", 
          "MkExamPeriod", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, 
          null), 
        new VDFEntry((int)36, "", "InComment1CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)37, "", "InComment2CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)38, "", "InComment3CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)39, "", "InComment4CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)40, "", "InComment5CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)41, "", "InComment6CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)42, "", "InComment7CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)43, "", "InComment8CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)44, "", "InComment9CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)45, "", "InComment10CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)46, "", "InComment11CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)47, "", "InComment12CsfStrings", "CsfStrings", 
          "String100", VDFEntry.TYPE_STRING, (short)1, (short)0, 100, (short)0, 
          null), 
        new VDFEntry((int)48, "", "InInvigilatorAddressCsfStrings", "CsfStrings"
          , "String1", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, 
          null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(
      InInternetFlagCsfStringsString1);
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InFaxNameCsfStringsString132);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InFaxNoCsfStringsString132);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(
      InToEmailAddressCsfStringsString132);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(
      InFromEmailAddressCsfStringsString132);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(InSecurityWsWorkstationCode);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(
      InPracticalFlagWsPracticalsValuesString1);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(new Short(
      InCsfClientServerCommunicationsClientVersionNumber));
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(new Short(
      InCsfClientServerCommunicationsClientRevisionNumber));
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(
      InCsfClientServerCommunicationsClientDevelopmentPhase);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(
      InCsfClientServerCommunicationsAction);
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(
      InCsfClientServerCommunicationsClientIsGuiFlag);
    // predicate view item
    vdf.getEntries()[12].getDataValue().setObject(new Integer(
      InCsfClientServerCommunicationsClientDate));
    // predicate view item
    vdf.getEntries()[13].getDataValue().setObject(new Integer(
      InCsfClientServerCommunicationsClientTime));
    // predicate view item
    vdf.getEntries()[14].getDataValue().setObject(
      InCsfClientServerCommunicationsClientTimestamp);
    // predicate view item
    vdf.getEntries()[15].getDataValue().setObject(
      InCsfClientServerCommunicationsClientTransactionCode);
    // predicate view item
    vdf.getEntries()[16].getDataValue().setObject(
      InCsfClientServerCommunicationsClientUserId);
    // predicate view item
    vdf.getEntries()[17].getDataValue().setObject(
      InCsfClientServerCommunicationsListLinkFlag);
    // predicate view item
    vdf.getEntries()[18].getDataValue().setObject(
      InCsfClientServerCommunicationsMaintLinkFlag);
    // predicate view item
    vdf.getEntries()[19].getDataValue().setObject(
      InCsfClientServerCommunicationsFirstpassFlag);
    // predicate view item
    vdf.getEntries()[20].getDataValue().setObject(InSecurityWsPrinterCode);
    // predicate view item
    vdf.getEntries()[21].getDataValue().setObject(new Integer(
      InSecurityWsUserNumber));
    // predicate view item
    vdf.getEntries()[22].getDataValue().setObject(new Short(
      InSecurityWsUserNumberOfLogonAttempts));
    // predicate view item
    vdf.getEntries()[23].getDataValue().setObject(InSecurityWsUserLoggedOnFlag)
      ;
    // predicate view item
    vdf.getEntries()[24].getDataValue().setObject(InSecurityWsUserInUsedFlag);
    // predicate view item
    vdf.getEntries()[25].getDataValue().setObject(new Integer(
      InSecurityWsUserLastLogonDate));
    // predicate view item
    vdf.getEntries()[26].getDataValue().setObject(InSecurityWsUserName);
    // predicate view item
    vdf.getEntries()[27].getDataValue().setObject(InSecurityWsUserPersonnelNo);
    // predicate view item
    vdf.getEntries()[28].getDataValue().setObject(InSecurityWsUserPhoneNumber);
    // predicate view item
    vdf.getEntries()[29].getDataValue().setObject(InSecurityWsUserPassword);
    // predicate view item
    vdf.getEntries()[30].getDataValue().setObject(InWsStudentSurname);
    // predicate view item
    vdf.getEntries()[31].getDataValue().setObject(InWsStudentInitials);
    // predicate view item
    vdf.getEntries()[32].getDataValue().setObject(new Integer(
      InStudentAnnualRecordMkStudentNr));
    // predicate view item
    vdf.getEntries()[33].getDataValue().setObject(new Short(
      InStudentStudyUnitExamYear));
    // predicate view item
    vdf.getEntries()[34].getDataValue().setObject(new Short(
      InStudentStudyUnitMkExamPeriod));
    // predicate view item
    vdf.getEntries()[35].getDataValue().setObject(InComment1CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[36].getDataValue().setObject(InComment2CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[37].getDataValue().setObject(InComment3CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[38].getDataValue().setObject(InComment4CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[39].getDataValue().setObject(InComment5CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[40].getDataValue().setObject(InComment6CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[41].getDataValue().setObject(InComment7CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[42].getDataValue().setObject(InComment8CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[43].getDataValue().setObject(InComment9CsfStringsString100)
      ;
    // predicate view item
    vdf.getEntries()[44].getDataValue().setObject(
      InComment10CsfStringsString100);
    // predicate view item
    vdf.getEntries()[45].getDataValue().setObject(
      InComment11CsfStringsString100);
    // predicate view item
    vdf.getEntries()[46].getDataValue().setObject(
      InComment12CsfStringsString100);
    // predicate view item
    vdf.getEntries()[47].getDataValue().setObject(
      InInvigilatorAddressCsfStringsString1);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InInternetFlagCsfStringsString1 = ((String)vdf.getEntries()[0]
        .getDataValue().getObject());
    }
    else 
    {
      InInternetFlagCsfStringsString1 = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InFaxNameCsfStringsString132 = ((String)vdf.getEntries()[1].getDataValue()
        .getObject());
    }
    else 
    {
      InFaxNameCsfStringsString132 = 
"                                                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InFaxNoCsfStringsString132 = ((String)vdf.getEntries()[2].getDataValue()
        .getObject());
    }
    else 
    {
      InFaxNoCsfStringsString132 = 
"                                                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InToEmailAddressCsfStringsString132 = ((String)vdf.getEntries()[3]
        .getDataValue().getObject());
    }
    else 
    {
      InToEmailAddressCsfStringsString132 = 
"                                                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      InFromEmailAddressCsfStringsString132 = ((String)vdf.getEntries()[4]
        .getDataValue().getObject());
    }
    else 
    {
      InFromEmailAddressCsfStringsString132 = 
"                                                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      InSecurityWsWorkstationCode = ((String)vdf.getEntries()[5].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsWorkstationCode = "";
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      InPracticalFlagWsPracticalsValuesString1 = ((String)vdf.getEntries()[6]
        .getDataValue().getObject());
    }
    else 
    {
      InPracticalFlagWsPracticalsValuesString1 = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientVersionNumber = ((Short)
        vdf.getEntries()[7].getDataValue().getObject()).shortValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientVersionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientRevisionNumber = ((Short)
        vdf.getEntries()[8].getDataValue().getObject()).shortValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientRevisionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientDevelopmentPhase = ((String)
        vdf.getEntries()[9].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsAction = ((String)vdf.getEntries()[10]
        .getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsAction = "  ";
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientIsGuiFlag = ((String)vdf.getEntries()
        [11].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientIsGuiFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[12].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientDate = ((Integer)vdf.getEntries()[12]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[13].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientTime = ((Integer)vdf.getEntries()[13]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientTime = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[14].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientTimestamp = ((String)vdf.getEntries()
        [14].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientTimestamp = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[15].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientTransactionCode = ((String)
        vdf.getEntries()[15].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientTransactionCode = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[16].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientUserId = ((String)vdf.getEntries()[
        16].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientUserId = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[17].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsListLinkFlag = ((String)vdf.getEntries()[
        17].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsListLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[18].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsMaintLinkFlag = ((String)vdf.getEntries()[
        18].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsMaintLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[19].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsFirstpassFlag = ((String)vdf.getEntries()[
        19].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsFirstpassFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[20].getDataValue().getObject() != null )
    {
      InSecurityWsPrinterCode = ((String)vdf.getEntries()[20].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsPrinterCode = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[21].getDataValue().getObject() != null )
    {
      InSecurityWsUserNumber = ((Integer)vdf.getEntries()[21].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InSecurityWsUserNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[22].getDataValue().getObject() != null )
    {
      InSecurityWsUserNumberOfLogonAttempts = ((Short)vdf.getEntries()[22]
        .getDataValue().getObject()).shortValue();
    }
    else 
    {
      InSecurityWsUserNumberOfLogonAttempts = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[23].getDataValue().getObject() != null )
    {
      InSecurityWsUserLoggedOnFlag = ((String)vdf.getEntries()[23].getDataValue(
        ).getObject());
    }
    else 
    {
      InSecurityWsUserLoggedOnFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[24].getDataValue().getObject() != null )
    {
      InSecurityWsUserInUsedFlag = ((String)vdf.getEntries()[24].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsUserInUsedFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[25].getDataValue().getObject() != null )
    {
      InSecurityWsUserLastLogonDate = ((Integer)vdf.getEntries()[25]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      InSecurityWsUserLastLogonDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[26].getDataValue().getObject() != null )
    {
      InSecurityWsUserName = ((String)vdf.getEntries()[26].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsUserName = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[27].getDataValue().getObject() != null )
    {
      InSecurityWsUserPersonnelNo = ((String)vdf.getEntries()[27].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsUserPersonnelNo = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[28].getDataValue().getObject() != null )
    {
      InSecurityWsUserPhoneNumber = ((String)vdf.getEntries()[28].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsUserPhoneNumber = "                    ";
    }
    // predicate view item
    if ( vdf.getEntries()[29].getDataValue().getObject() != null )
    {
      InSecurityWsUserPassword = ((String)vdf.getEntries()[29].getDataValue()
        .getObject());
    }
    else 
    {
      InSecurityWsUserPassword = "            ";
    }
    // predicate view item
    if ( vdf.getEntries()[30].getDataValue().getObject() != null )
    {
      InWsStudentSurname = ((String)vdf.getEntries()[30].getDataValue()
        .getObject());
    }
    else 
    {
      InWsStudentSurname = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[31].getDataValue().getObject() != null )
    {
      InWsStudentInitials = ((String)vdf.getEntries()[31].getDataValue()
        .getObject());
    }
    else 
    {
      InWsStudentInitials = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[32].getDataValue().getObject() != null )
    {
      InStudentAnnualRecordMkStudentNr = ((Integer)vdf.getEntries()[32]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      InStudentAnnualRecordMkStudentNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[33].getDataValue().getObject() != null )
    {
      InStudentStudyUnitExamYear = ((Short)vdf.getEntries()[33].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      InStudentStudyUnitExamYear = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[34].getDataValue().getObject() != null )
    {
      InStudentStudyUnitMkExamPeriod = ((Short)vdf.getEntries()[34]
        .getDataValue().getObject()).shortValue();
    }
    else 
    {
      InStudentStudyUnitMkExamPeriod = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[35].getDataValue().getObject() != null )
    {
      InComment1CsfStringsString100 = ((String)vdf.getEntries()[35]
        .getDataValue().getObject());
    }
    else 
    {
      InComment1CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[36].getDataValue().getObject() != null )
    {
      InComment2CsfStringsString100 = ((String)vdf.getEntries()[36]
        .getDataValue().getObject());
    }
    else 
    {
      InComment2CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[37].getDataValue().getObject() != null )
    {
      InComment3CsfStringsString100 = ((String)vdf.getEntries()[37]
        .getDataValue().getObject());
    }
    else 
    {
      InComment3CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[38].getDataValue().getObject() != null )
    {
      InComment4CsfStringsString100 = ((String)vdf.getEntries()[38]
        .getDataValue().getObject());
    }
    else 
    {
      InComment4CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[39].getDataValue().getObject() != null )
    {
      InComment5CsfStringsString100 = ((String)vdf.getEntries()[39]
        .getDataValue().getObject());
    }
    else 
    {
      InComment5CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[40].getDataValue().getObject() != null )
    {
      InComment6CsfStringsString100 = ((String)vdf.getEntries()[40]
        .getDataValue().getObject());
    }
    else 
    {
      InComment6CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[41].getDataValue().getObject() != null )
    {
      InComment7CsfStringsString100 = ((String)vdf.getEntries()[41]
        .getDataValue().getObject());
    }
    else 
    {
      InComment7CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[42].getDataValue().getObject() != null )
    {
      InComment8CsfStringsString100 = ((String)vdf.getEntries()[42]
        .getDataValue().getObject());
    }
    else 
    {
      InComment8CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[43].getDataValue().getObject() != null )
    {
      InComment9CsfStringsString100 = ((String)vdf.getEntries()[43]
        .getDataValue().getObject());
    }
    else 
    {
      InComment9CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[44].getDataValue().getObject() != null )
    {
      InComment10CsfStringsString100 = ((String)vdf.getEntries()[44]
        .getDataValue().getObject());
    }
    else 
    {
      InComment10CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[45].getDataValue().getObject() != null )
    {
      InComment11CsfStringsString100 = ((String)vdf.getEntries()[45]
        .getDataValue().getObject());
    }
    else 
    {
      InComment11CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[46].getDataValue().getObject() != null )
    {
      InComment12CsfStringsString100 = ((String)vdf.getEntries()[46]
        .getDataValue().getObject());
    }
    else 
    {
      InComment12CsfStringsString100 = 
"                                                                                                    "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[47].getDataValue().getObject() != null )
    {
      InInvigilatorAddressCsfStringsString1 = ((String)vdf.getEntries()[47]
        .getDataValue().getObject());
    }
    else 
    {
      InInvigilatorAddressCsfStringsString1 = " ";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((EXSUG07S_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(EXSUG07S_IA orig)
  {
    InInternetFlagCsfStringsString1_AS = 
      orig.InInternetFlagCsfStringsString1_AS;
    InInternetFlagCsfStringsString1 = orig.InInternetFlagCsfStringsString1;
    InFaxNameCsfStringsString132_AS = orig.InFaxNameCsfStringsString132_AS;
    InFaxNameCsfStringsString132 = orig.InFaxNameCsfStringsString132;
    InFaxNoCsfStringsString132_AS = orig.InFaxNoCsfStringsString132_AS;
    InFaxNoCsfStringsString132 = orig.InFaxNoCsfStringsString132;
    InToEmailAddressCsfStringsString132_AS = 
      orig.InToEmailAddressCsfStringsString132_AS;
    InToEmailAddressCsfStringsString132 = 
      orig.InToEmailAddressCsfStringsString132;
    InFromEmailAddressCsfStringsString132_AS = 
      orig.InFromEmailAddressCsfStringsString132_AS;
    InFromEmailAddressCsfStringsString132 = 
      orig.InFromEmailAddressCsfStringsString132;
    InSecurityWsWorkstationCode_AS = orig.InSecurityWsWorkstationCode_AS;
    InSecurityWsWorkstationCode = orig.InSecurityWsWorkstationCode;
    InPracticalFlagWsPracticalsValuesString1_AS = 
      orig.InPracticalFlagWsPracticalsValuesString1_AS;
    InPracticalFlagWsPracticalsValuesString1 = 
      orig.InPracticalFlagWsPracticalsValuesString1;
    InCsfClientServerCommunicationsClientVersionNumber_AS = 
      orig.InCsfClientServerCommunicationsClientVersionNumber_AS;
    InCsfClientServerCommunicationsClientVersionNumber = 
      orig.InCsfClientServerCommunicationsClientVersionNumber;
    InCsfClientServerCommunicationsClientRevisionNumber_AS = 
      orig.InCsfClientServerCommunicationsClientRevisionNumber_AS;
    InCsfClientServerCommunicationsClientRevisionNumber = 
      orig.InCsfClientServerCommunicationsClientRevisionNumber;
    InCsfClientServerCommunicationsClientDevelopmentPhase_AS = 
      orig.InCsfClientServerCommunicationsClientDevelopmentPhase_AS;
    InCsfClientServerCommunicationsClientDevelopmentPhase = 
      orig.InCsfClientServerCommunicationsClientDevelopmentPhase;
    InCsfClientServerCommunicationsAction_AS = 
      orig.InCsfClientServerCommunicationsAction_AS;
    InCsfClientServerCommunicationsAction = 
      orig.InCsfClientServerCommunicationsAction;
    InCsfClientServerCommunicationsClientIsGuiFlag_AS = 
      orig.InCsfClientServerCommunicationsClientIsGuiFlag_AS;
    InCsfClientServerCommunicationsClientIsGuiFlag = 
      orig.InCsfClientServerCommunicationsClientIsGuiFlag;
    InCsfClientServerCommunicationsClientDate_AS = 
      orig.InCsfClientServerCommunicationsClientDate_AS;
    InCsfClientServerCommunicationsClientDate = 
      orig.InCsfClientServerCommunicationsClientDate;
    InCsfClientServerCommunicationsClientTime_AS = 
      orig.InCsfClientServerCommunicationsClientTime_AS;
    InCsfClientServerCommunicationsClientTime = 
      orig.InCsfClientServerCommunicationsClientTime;
    InCsfClientServerCommunicationsClientTimestamp_AS = 
      orig.InCsfClientServerCommunicationsClientTimestamp_AS;
    InCsfClientServerCommunicationsClientTimestamp = 
      orig.InCsfClientServerCommunicationsClientTimestamp;
    InCsfClientServerCommunicationsClientTransactionCode_AS = 
      orig.InCsfClientServerCommunicationsClientTransactionCode_AS;
    InCsfClientServerCommunicationsClientTransactionCode = 
      orig.InCsfClientServerCommunicationsClientTransactionCode;
    InCsfClientServerCommunicationsClientUserId_AS = 
      orig.InCsfClientServerCommunicationsClientUserId_AS;
    InCsfClientServerCommunicationsClientUserId = 
      orig.InCsfClientServerCommunicationsClientUserId;
    InCsfClientServerCommunicationsListLinkFlag_AS = 
      orig.InCsfClientServerCommunicationsListLinkFlag_AS;
    InCsfClientServerCommunicationsListLinkFlag = 
      orig.InCsfClientServerCommunicationsListLinkFlag;
    InCsfClientServerCommunicationsMaintLinkFlag_AS = 
      orig.InCsfClientServerCommunicationsMaintLinkFlag_AS;
    InCsfClientServerCommunicationsMaintLinkFlag = 
      orig.InCsfClientServerCommunicationsMaintLinkFlag;
    InCsfClientServerCommunicationsFirstpassFlag_AS = 
      orig.InCsfClientServerCommunicationsFirstpassFlag_AS;
    InCsfClientServerCommunicationsFirstpassFlag = 
      orig.InCsfClientServerCommunicationsFirstpassFlag;
    InSecurityWsPrinterCode_AS = orig.InSecurityWsPrinterCode_AS;
    InSecurityWsPrinterCode = orig.InSecurityWsPrinterCode;
    InSecurityWsUserNumber_AS = orig.InSecurityWsUserNumber_AS;
    InSecurityWsUserNumber = orig.InSecurityWsUserNumber;
    InSecurityWsUserNumberOfLogonAttempts_AS = 
      orig.InSecurityWsUserNumberOfLogonAttempts_AS;
    InSecurityWsUserNumberOfLogonAttempts = 
      orig.InSecurityWsUserNumberOfLogonAttempts;
    InSecurityWsUserLoggedOnFlag_AS = orig.InSecurityWsUserLoggedOnFlag_AS;
    InSecurityWsUserLoggedOnFlag = orig.InSecurityWsUserLoggedOnFlag;
    InSecurityWsUserInUsedFlag_AS = orig.InSecurityWsUserInUsedFlag_AS;
    InSecurityWsUserInUsedFlag = orig.InSecurityWsUserInUsedFlag;
    InSecurityWsUserLastLogonDate_AS = orig.InSecurityWsUserLastLogonDate_AS;
    InSecurityWsUserLastLogonDate = orig.InSecurityWsUserLastLogonDate;
    InSecurityWsUserName_AS = orig.InSecurityWsUserName_AS;
    InSecurityWsUserName = orig.InSecurityWsUserName;
    InSecurityWsUserPersonnelNo_AS = orig.InSecurityWsUserPersonnelNo_AS;
    InSecurityWsUserPersonnelNo = orig.InSecurityWsUserPersonnelNo;
    InSecurityWsUserPhoneNumber_AS = orig.InSecurityWsUserPhoneNumber_AS;
    InSecurityWsUserPhoneNumber = orig.InSecurityWsUserPhoneNumber;
    InSecurityWsUserPassword_AS = orig.InSecurityWsUserPassword_AS;
    InSecurityWsUserPassword = orig.InSecurityWsUserPassword;
    InWsStudentSurname_AS = orig.InWsStudentSurname_AS;
    InWsStudentSurname = orig.InWsStudentSurname;
    InWsStudentInitials_AS = orig.InWsStudentInitials_AS;
    InWsStudentInitials = orig.InWsStudentInitials;
    InStudentAnnualRecordMkStudentNr_AS = 
      orig.InStudentAnnualRecordMkStudentNr_AS;
    InStudentAnnualRecordMkStudentNr = orig.InStudentAnnualRecordMkStudentNr;
    InStudentStudyUnitExamYear_AS = orig.InStudentStudyUnitExamYear_AS;
    InStudentStudyUnitExamYear = orig.InStudentStudyUnitExamYear;
    InStudentStudyUnitMkExamPeriod_AS = orig.InStudentStudyUnitMkExamPeriod_AS;
    InStudentStudyUnitMkExamPeriod = orig.InStudentStudyUnitMkExamPeriod;
    InComment1CsfStringsString100_AS = orig.InComment1CsfStringsString100_AS;
    InComment1CsfStringsString100 = orig.InComment1CsfStringsString100;
    InComment2CsfStringsString100_AS = orig.InComment2CsfStringsString100_AS;
    InComment2CsfStringsString100 = orig.InComment2CsfStringsString100;
    InComment3CsfStringsString100_AS = orig.InComment3CsfStringsString100_AS;
    InComment3CsfStringsString100 = orig.InComment3CsfStringsString100;
    InComment4CsfStringsString100_AS = orig.InComment4CsfStringsString100_AS;
    InComment4CsfStringsString100 = orig.InComment4CsfStringsString100;
    InComment5CsfStringsString100_AS = orig.InComment5CsfStringsString100_AS;
    InComment5CsfStringsString100 = orig.InComment5CsfStringsString100;
    InComment6CsfStringsString100_AS = orig.InComment6CsfStringsString100_AS;
    InComment6CsfStringsString100 = orig.InComment6CsfStringsString100;
    InComment7CsfStringsString100_AS = orig.InComment7CsfStringsString100_AS;
    InComment7CsfStringsString100 = orig.InComment7CsfStringsString100;
    InComment8CsfStringsString100_AS = orig.InComment8CsfStringsString100_AS;
    InComment8CsfStringsString100 = orig.InComment8CsfStringsString100;
    InComment9CsfStringsString100_AS = orig.InComment9CsfStringsString100_AS;
    InComment9CsfStringsString100 = orig.InComment9CsfStringsString100;
    InComment10CsfStringsString100_AS = orig.InComment10CsfStringsString100_AS;
    InComment10CsfStringsString100 = orig.InComment10CsfStringsString100;
    InComment11CsfStringsString100_AS = orig.InComment11CsfStringsString100_AS;
    InComment11CsfStringsString100 = orig.InComment11CsfStringsString100;
    InComment12CsfStringsString100_AS = orig.InComment12CsfStringsString100_AS;
    InComment12CsfStringsString100 = orig.InComment12CsfStringsString100;
    InInvigilatorAddressCsfStringsString1_AS = 
      orig.InInvigilatorAddressCsfStringsString1_AS;
    InInvigilatorAddressCsfStringsString1 = 
      orig.InInvigilatorAddressCsfStringsString1;
  }
}
