package Gigcf01h;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                            CA Gen r8
//
//           Copyright (c) 2012 CA. All rights reserved.
//
//    Name: GIGCF01S_OA                      Date: 2012/05/15
//    User: Tanderw                          Time: 13:57:43
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen80.vwrt.*;
import com.ca.gen80.vwrt.types.*;
import com.ca.gen80.vwrt.vdf.*;
import com.ca.gen80.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: GIGCF01S_OA
 **/
public class GIGCF01S_OA extends ViewBase implements IExportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: OUT
  //        Type: CSF_EVENT_COMMUNICATIONS
  /**
   * Attribute missing flag for: 
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag
   **/
  public char OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AS;
  /**
   * Dynamic attribute for: 
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag
   **/
  public DynamicAttr OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AT;
  /**
   * Attribute for: OutCsfEventCommunicationsRgvExistingLineSelectedFlag
   **/
  public String OutCsfEventCommunicationsRgvExistingLineSelectedFlag;
  /**
   * Attribute missing flag for: 
    OutCsfEventCommunicationsRgvNewLineSelectedFlag
   **/
  public char OutCsfEventCommunicationsRgvNewLineSelectedFlag_AS;
  /**
   * Dynamic attribute for: OutCsfEventCommunicationsRgvNewLineSelectedFlag
   **/
  public DynamicAttr OutCsfEventCommunicationsRgvNewLineSelectedFlag_AT;
  /**
   * Attribute for: OutCsfEventCommunicationsRgvNewLineSelectedFlag
   **/
  public String OutCsfEventCommunicationsRgvNewLineSelectedFlag;
  // Entity View: OUT
  //        Type: GENERIC_CODE
  /**
   * Attribute missing flag for: OutGenericCodeCode
   **/
  public char OutGenericCodeCode_AS;
  /**
   * Dynamic attribute for: OutGenericCodeCode
   **/
  public DynamicAttr OutGenericCodeCode_AT;
  /**
   * Attribute for: OutGenericCodeCode
   **/
  public String OutGenericCodeCode;
  /**
   * Attribute missing flag for: OutGenericCodeEngDescription
   **/
  public char OutGenericCodeEngDescription_AS;
  /**
   * Dynamic attribute for: OutGenericCodeEngDescription
   **/
  public DynamicAttr OutGenericCodeEngDescription_AT;
  /**
   * Attribute for: OutGenericCodeEngDescription
   **/
  public String OutGenericCodeEngDescription;
  /**
   * Attribute missing flag for: OutGenericCodeAfrDescription
   **/
  public char OutGenericCodeAfrDescription_AS;
  /**
   * Dynamic attribute for: OutGenericCodeAfrDescription
   **/
  public DynamicAttr OutGenericCodeAfrDescription_AT;
  /**
   * Attribute for: OutGenericCodeAfrDescription
   **/
  public String OutGenericCodeAfrDescription;
  /**
   * Attribute missing flag for: OutGenericCodeInUseFlag
   **/
  public char OutGenericCodeInUseFlag_AS;
  /**
   * Dynamic attribute for: OutGenericCodeInUseFlag
   **/
  public DynamicAttr OutGenericCodeInUseFlag_AT;
  /**
   * Attribute for: OutGenericCodeInUseFlag
   **/
  public String OutGenericCodeInUseFlag;
  /**
   * Attribute missing flag for: OutGenericCodeInfo
   **/
  public char OutGenericCodeInfo_AS;
  /**
   * Dynamic attribute for: OutGenericCodeInfo
   **/
  public DynamicAttr OutGenericCodeInfo_AT;
  /**
   * Attribute for: OutGenericCodeInfo
   **/
  public String OutGenericCodeInfo;
  // Entity View: OUT
  //        Type: WIZFUNC_REPORTING_CONTROL
  /**
   * Attribute missing flag for: OutWizfuncReportingControlPath
   **/
  public char OutWizfuncReportingControlPath_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlPath
   **/
  public DynamicAttr OutWizfuncReportingControlPath_AT;
  /**
   * Attribute for: OutWizfuncReportingControlPath
   **/
  public String OutWizfuncReportingControlPath;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlFilename
   **/
  public char OutWizfuncReportingControlFilename_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlFilename
   **/
  public DynamicAttr OutWizfuncReportingControlFilename_AT;
  /**
   * Attribute for: OutWizfuncReportingControlFilename
   **/
  public String OutWizfuncReportingControlFilename;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlSupressFormFeed
   **/
  public char OutWizfuncReportingControlSupressFormFeed_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlSupressFormFeed
   **/
  public DynamicAttr OutWizfuncReportingControlSupressFormFeed_AT;
  /**
   * Attribute for: OutWizfuncReportingControlSupressFormFeed
   **/
  public String OutWizfuncReportingControlSupressFormFeed;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlPrintOptions
   **/
  public char OutWizfuncReportingControlPrintOptions_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlPrintOptions
   **/
  public DynamicAttr OutWizfuncReportingControlPrintOptions_AT;
  /**
   * Attribute for: OutWizfuncReportingControlPrintOptions
   **/
  public String OutWizfuncReportingControlPrintOptions;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlPrinterCode
   **/
  public char OutWizfuncReportingControlPrinterCode_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlPrinterCode
   **/
  public DynamicAttr OutWizfuncReportingControlPrinterCode_AT;
  /**
   * Attribute for: OutWizfuncReportingControlPrinterCode
   **/
  public String OutWizfuncReportingControlPrinterCode;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlFunction
   **/
  public char OutWizfuncReportingControlFunction_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlFunction
   **/
  public DynamicAttr OutWizfuncReportingControlFunction_AT;
  /**
   * Attribute for: OutWizfuncReportingControlFunction
   **/
  public String OutWizfuncReportingControlFunction;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlPathAndFilename
   **/
  public char OutWizfuncReportingControlPathAndFilename_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlPathAndFilename
   **/
  public DynamicAttr OutWizfuncReportingControlPathAndFilename_AT;
  /**
   * Attribute for: OutWizfuncReportingControlPathAndFilename
   **/
  public String OutWizfuncReportingControlPathAndFilename;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlProgramName
   **/
  public char OutWizfuncReportingControlProgramName_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlProgramName
   **/
  public DynamicAttr OutWizfuncReportingControlProgramName_AT;
  /**
   * Attribute for: OutWizfuncReportingControlProgramName
   **/
  public String OutWizfuncReportingControlProgramName;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlReportWidth
   **/
  public char OutWizfuncReportingControlReportWidth_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlReportWidth
   **/
  public DynamicAttr OutWizfuncReportingControlReportWidth_AT;
  /**
   * Attribute for: OutWizfuncReportingControlReportWidth
   **/
  public short OutWizfuncReportingControlReportWidth;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlStartingLineCount
   **/
  public char OutWizfuncReportingControlStartingLineCount_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlStartingLineCount
   **/
  public DynamicAttr OutWizfuncReportingControlStartingLineCount_AT;
  /**
   * Attribute for: OutWizfuncReportingControlStartingLineCount
   **/
  public int OutWizfuncReportingControlStartingLineCount;
  /**
   * Attribute missing flag for: OutWizfuncReportingControlEndingLineCount
   **/
  public char OutWizfuncReportingControlEndingLineCount_AS;
  /**
   * Dynamic attribute for: OutWizfuncReportingControlEndingLineCount
   **/
  public DynamicAttr OutWizfuncReportingControlEndingLineCount_AT;
  /**
   * Attribute for: OutWizfuncReportingControlEndingLineCount
   **/
  public int OutWizfuncReportingControlEndingLineCount;
  // Entity View: OUT
  //        Type: GENERIC_CATEGORY
  /**
   * Attribute missing flag for: OutGenericCategoryCode
   **/
  public char OutGenericCategoryCode_AS;
  /**
   * Dynamic attribute for: OutGenericCategoryCode
   **/
  public DynamicAttr OutGenericCategoryCode_AT;
  /**
   * Attribute for: OutGenericCategoryCode
   **/
  public short OutGenericCategoryCode;
  /**
   * Attribute missing flag for: OutGenericCategoryDescription
   **/
  public char OutGenericCategoryDescription_AS;
  /**
   * Dynamic attribute for: OutGenericCategoryDescription
   **/
  public DynamicAttr OutGenericCategoryDescription_AT;
  /**
   * Attribute for: OutGenericCategoryDescription
   **/
  public String OutGenericCategoryDescription;
  /**
   * Attribute missing flag for: OutGenericCategoryInUseFlag
   **/
  public char OutGenericCategoryInUseFlag_AS;
  /**
   * Dynamic attribute for: OutGenericCategoryInUseFlag
   **/
  public DynamicAttr OutGenericCategoryInUseFlag_AT;
  /**
   * Attribute for: OutGenericCategoryInUseFlag
   **/
  public String OutGenericCategoryInUseFlag;
  // Repeating GV:  OUT_GROUP_GENERIC_CODE
  //     Repeats: 120 times
  /**
   * Repeating group view count
   **/
  public int OutGroupGenericCode_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char OutGroupGenericCode_AC[] = new char[120];
  // Entity View: OUT_G
  //        Type: GENERIC_CODE
  /**
   * Attribute missing flag for: OutGGenericCodeCode
   **/
  public char OutGGenericCodeCode_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGGenericCodeCode
   **/
  public DynamicAttr OutGGenericCodeCode_AT[] = new DynamicAttr[120];
  /**
   * Attribute for: OutGGenericCodeCode
   **/
  public String OutGGenericCodeCode[] = new String[120];
  /**
   * Attribute missing flag for: OutGGenericCodeEngDescription
   **/
  public char OutGGenericCodeEngDescription_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGGenericCodeEngDescription
   **/
  public DynamicAttr OutGGenericCodeEngDescription_AT[] = new DynamicAttr[120];
  /**
   * Attribute for: OutGGenericCodeEngDescription
   **/
  public String OutGGenericCodeEngDescription[] = new String[120];
  /**
   * Attribute missing flag for: OutGGenericCodeAfrDescription
   **/
  public char OutGGenericCodeAfrDescription_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGGenericCodeAfrDescription
   **/
  public DynamicAttr OutGGenericCodeAfrDescription_AT[] = new DynamicAttr[120];
  /**
   * Attribute for: OutGGenericCodeAfrDescription
   **/
  public String OutGGenericCodeAfrDescription[] = new String[120];
  /**
   * Attribute missing flag for: OutGGenericCodeInUseFlag
   **/
  public char OutGGenericCodeInUseFlag_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGGenericCodeInUseFlag
   **/
  public DynamicAttr OutGGenericCodeInUseFlag_AT[] = new DynamicAttr[120];
  /**
   * Attribute for: OutGGenericCodeInUseFlag
   **/
  public String OutGGenericCodeInUseFlag[] = new String[120];
  /**
   * Attribute missing flag for: OutGGenericCodeInfo
   **/
  public char OutGGenericCodeInfo_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGGenericCodeInfo
   **/
  public DynamicAttr OutGGenericCodeInfo_AT[] = new DynamicAttr[120];
  /**
   * Attribute for: OutGGenericCodeInfo
   **/
  public String OutGGenericCodeInfo[] = new String[120];
  // Entity View: OUT_G
  //        Type: CSF_LINE_ACTION_BAR
  /**
   * Attribute missing flag for: OutGCsfLineActionBarAction
   **/
  public char OutGCsfLineActionBarAction_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGCsfLineActionBarAction
   **/
  public DynamicAttr OutGCsfLineActionBarAction_AT[] = new DynamicAttr[120];
  /**
   * Attribute for: OutGCsfLineActionBarAction
   **/
  public String OutGCsfLineActionBarAction[] = new String[120];
  /**
   * Attribute missing flag for: OutGCsfLineActionBarLineReturnCode
   **/
  public char OutGCsfLineActionBarLineReturnCode_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGCsfLineActionBarLineReturnCode
   **/
  public DynamicAttr OutGCsfLineActionBarLineReturnCode_AT[] = new DynamicAttr[
    120];
  /**
   * Attribute for: OutGCsfLineActionBarLineReturnCode
   **/
  public short OutGCsfLineActionBarLineReturnCode[] = new short[120];
  /**
   * Attribute missing flag for: OutGCsfLineActionBarSelectionFlag
   **/
  public char OutGCsfLineActionBarSelectionFlag_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGCsfLineActionBarSelectionFlag
   **/
  public DynamicAttr OutGCsfLineActionBarSelectionFlag_AT[] = new DynamicAttr[
    120];
  /**
   * Attribute for: OutGCsfLineActionBarSelectionFlag
   **/
  public String OutGCsfLineActionBarSelectionFlag[] = new String[120];
  /**
   * Attribute missing flag for: OutGCsfLineActionBarTranslatedAction
   **/
  public char OutGCsfLineActionBarTranslatedAction_AS[] = new char[120];
  /**
   * Dynamic attribute for: OutGCsfLineActionBarTranslatedAction
   **/
  public DynamicAttr OutGCsfLineActionBarTranslatedAction_AT[] = new 
    DynamicAttr[120];
  /**
   * Attribute for: OutGCsfLineActionBarTranslatedAction
   **/
  public String OutGCsfLineActionBarTranslatedAction[] = new String[120];
  // Entity View: OUTPUT
  //        Type: WS_USER
  /**
   * Attribute missing flag for: OutputWsUserNumber
   **/
  public char OutputWsUserNumber_AS;
  /**
   * Dynamic attribute for: OutputWsUserNumber
   **/
  public DynamicAttr OutputWsUserNumber_AT;
  /**
   * Attribute for: OutputWsUserNumber
   **/
  public int OutputWsUserNumber;
  // Entity View: OUTPUT
  //        Type: WS_PRINTER
  /**
   * Attribute missing flag for: OutputWsPrinterCode
   **/
  public char OutputWsPrinterCode_AS;
  /**
   * Dynamic attribute for: OutputWsPrinterCode
   **/
  public DynamicAttr OutputWsPrinterCode_AT;
  /**
   * Attribute for: OutputWsPrinterCode
   **/
  public String OutputWsPrinterCode;
  // Entity View: OUT
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: OutCsfStringsString500
   **/
  public char OutCsfStringsString500_AS;
  /**
   * Dynamic attribute for: OutCsfStringsString500
   **/
  public DynamicAttr OutCsfStringsString500_AT;
  /**
   * Attribute for: OutCsfStringsString500
   **/
  public String OutCsfStringsString500;
  // Entity View: OUT
  //        Type: CSF_CLIENT_SERVER_COMMUNICATIONS
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsReturnCode
   **/
  public char OutCsfClientServerCommunicationsReturnCode_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsReturnCode
   **/
  public DynamicAttr OutCsfClientServerCommunicationsReturnCode_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsReturnCode
   **/
  public short OutCsfClientServerCommunicationsReturnCode;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerVersionNumber
   **/
  public char OutCsfClientServerCommunicationsServerVersionNumber_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerVersionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerVersionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerVersionNumber
   **/
  public short OutCsfClientServerCommunicationsServerVersionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerRevisionNumber
   **/
  public char OutCsfClientServerCommunicationsServerRevisionNumber_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsServerRevisionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerRevisionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerRevisionNumber
   **/
  public short OutCsfClientServerCommunicationsServerRevisionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerDevelopmentPhase
   **/
  public char OutCsfClientServerCommunicationsServerDevelopmentPhase_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsServerDevelopmentPhase
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerDevelopmentPhase_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerDevelopmentPhase
   **/
  public String OutCsfClientServerCommunicationsServerDevelopmentPhase;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsAction
   **/
  public char OutCsfClientServerCommunicationsAction_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsAction
   **/
  public DynamicAttr OutCsfClientServerCommunicationsAction_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsAction
   **/
  public String OutCsfClientServerCommunicationsAction;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public char OutCsfClientServerCommunicationsClientIsGuiFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientIsGuiFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public String OutCsfClientServerCommunicationsClientIsGuiFlag;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsServerDate
   **/
  public char OutCsfClientServerCommunicationsServerDate_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerDate
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerDate_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerDate
   **/
  public int OutCsfClientServerCommunicationsServerDate;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsServerTime
   **/
  public char OutCsfClientServerCommunicationsServerTime_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerTime
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerTime_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerTime
   **/
  public int OutCsfClientServerCommunicationsServerTime;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerTimestamp
   **/
  public char OutCsfClientServerCommunicationsServerTimestamp_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerTimestamp
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerTimestamp_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerTimestamp
   **/
  public String OutCsfClientServerCommunicationsServerTimestamp;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerTransactionCode
   **/
  public char OutCsfClientServerCommunicationsServerTransactionCode_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsServerTransactionCode
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerTransactionCode_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerTransactionCode
   **/
  public String OutCsfClientServerCommunicationsServerTransactionCode;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsServerUserId
   **/
  public char OutCsfClientServerCommunicationsServerUserId_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerUserId
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerUserId_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerUserId
   **/
  public String OutCsfClientServerCommunicationsServerUserId;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsServerRollbackFlag
   **/
  public char OutCsfClientServerCommunicationsServerRollbackFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsServerRollbackFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsServerRollbackFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsServerRollbackFlag
   **/
  public String OutCsfClientServerCommunicationsServerRollbackFlag;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsActionsPendingFlag
   **/
  public char OutCsfClientServerCommunicationsActionsPendingFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsActionsPendingFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsActionsPendingFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsActionsPendingFlag
   **/
  public String OutCsfClientServerCommunicationsActionsPendingFlag;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientVersionNumber
   **/
  public char OutCsfClientServerCommunicationsClientVersionNumber_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsClientVersionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientVersionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientVersionNumber
   **/
  public short OutCsfClientServerCommunicationsClientVersionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientRevisionNumber
   **/
  public char OutCsfClientServerCommunicationsClientRevisionNumber_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsClientRevisionNumber
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientRevisionNumber_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientRevisionNumber
   **/
  public short OutCsfClientServerCommunicationsClientRevisionNumber;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public char OutCsfClientServerCommunicationsClientDevelopmentPhase_AS;
  /**
   * Dynamic attribute for: 
    OutCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public DynamicAttr OutCsfClientServerCommunicationsClientDevelopmentPhase_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public String OutCsfClientServerCommunicationsClientDevelopmentPhase;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsListLinkFlag
   **/
  public char OutCsfClientServerCommunicationsListLinkFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsListLinkFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsListLinkFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsListLinkFlag
   **/
  public String OutCsfClientServerCommunicationsListLinkFlag;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsCancelFlag
   **/
  public char OutCsfClientServerCommunicationsCancelFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsCancelFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsCancelFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsCancelFlag
   **/
  public String OutCsfClientServerCommunicationsCancelFlag;
  /**
   * Attribute missing flag for: OutCsfClientServerCommunicationsMaintLinkFlag
   **/
  public char OutCsfClientServerCommunicationsMaintLinkFlag_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsMaintLinkFlag
   **/
  public DynamicAttr OutCsfClientServerCommunicationsMaintLinkFlag_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsMaintLinkFlag
   **/
  public String OutCsfClientServerCommunicationsMaintLinkFlag;
  /**
   * Attribute missing flag for: 
    OutCsfClientServerCommunicationsForceDatabaseRead
   **/
  public char OutCsfClientServerCommunicationsForceDatabaseRead_AS;
  /**
   * Dynamic attribute for: OutCsfClientServerCommunicationsForceDatabaseRead
   **/
  public DynamicAttr OutCsfClientServerCommunicationsForceDatabaseRead_AT;
  /**
   * Attribute for: OutCsfClientServerCommunicationsForceDatabaseRead
   **/
  public String OutCsfClientServerCommunicationsForceDatabaseRead;
  /**
   * Default Constructor
   **/
  
  public GIGCF01S_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public GIGCF01S_OA(GIGCF01S_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static GIGCF01S_OA getInstance()
  {
    return new GIGCF01S_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new GIGCF01S_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AT = null;
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AS = ' ';
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag = " ";
    OutCsfEventCommunicationsRgvNewLineSelectedFlag_AT = null;
    OutCsfEventCommunicationsRgvNewLineSelectedFlag_AS = ' ';
    OutCsfEventCommunicationsRgvNewLineSelectedFlag = " ";
    OutGenericCodeCode_AT = null;
    OutGenericCodeCode_AS = ' ';
    OutGenericCodeCode = "          ";
    OutGenericCodeEngDescription_AT = null;
    OutGenericCodeEngDescription_AS = ' ';
    OutGenericCodeEngDescription = "                                        ";
    OutGenericCodeAfrDescription_AT = null;
    OutGenericCodeAfrDescription_AS = ' ';
    OutGenericCodeAfrDescription = "                                        ";
    OutGenericCodeInUseFlag_AT = null;
    OutGenericCodeInUseFlag_AS = ' ';
    OutGenericCodeInUseFlag = " ";
    OutGenericCodeInfo_AT = null;
    OutGenericCodeInfo_AS = ' ';
    OutGenericCodeInfo = "                                        ";
    OutWizfuncReportingControlPath_AT = null;
    OutWizfuncReportingControlPath_AS = ' ';
    OutWizfuncReportingControlPath = 
      "                                          ";
    OutWizfuncReportingControlFilename_AT = null;
    OutWizfuncReportingControlFilename_AS = ' ';
    OutWizfuncReportingControlFilename = "                    ";
    OutWizfuncReportingControlSupressFormFeed_AT = null;
    OutWizfuncReportingControlSupressFormFeed_AS = ' ';
    OutWizfuncReportingControlSupressFormFeed = " ";
    OutWizfuncReportingControlPrintOptions_AT = null;
    OutWizfuncReportingControlPrintOptions_AS = ' ';
    OutWizfuncReportingControlPrintOptions = "";
    OutWizfuncReportingControlPrinterCode_AT = null;
    OutWizfuncReportingControlPrinterCode_AS = ' ';
    OutWizfuncReportingControlPrinterCode = "";
    OutWizfuncReportingControlFunction_AT = null;
    OutWizfuncReportingControlFunction_AS = ' ';
    OutWizfuncReportingControlFunction = "        ";
    OutWizfuncReportingControlPathAndFilename_AT = null;
    OutWizfuncReportingControlPathAndFilename_AS = ' ';
    OutWizfuncReportingControlPathAndFilename = "";
    OutWizfuncReportingControlProgramName_AT = null;
    OutWizfuncReportingControlProgramName_AS = ' ';
    OutWizfuncReportingControlProgramName = "        ";
    OutWizfuncReportingControlReportWidth_AT = null;
    OutWizfuncReportingControlReportWidth_AS = ' ';
    OutWizfuncReportingControlReportWidth = 0;
    OutWizfuncReportingControlStartingLineCount_AT = null;
    OutWizfuncReportingControlStartingLineCount_AS = ' ';
    OutWizfuncReportingControlStartingLineCount = 0;
    OutWizfuncReportingControlEndingLineCount_AT = null;
    OutWizfuncReportingControlEndingLineCount_AS = ' ';
    OutWizfuncReportingControlEndingLineCount = 0;
    OutGenericCategoryCode_AT = null;
    OutGenericCategoryCode_AS = ' ';
    OutGenericCategoryCode = 0;
    OutGenericCategoryDescription_AT = null;
    OutGenericCategoryDescription_AS = ' ';
    OutGenericCategoryDescription = "                                        ";
    OutGenericCategoryInUseFlag_AT = null;
    OutGenericCategoryInUseFlag_AS = ' ';
    OutGenericCategoryInUseFlag = " ";
    OutGroupGenericCode_MA = 0;
    for(int a = 0; a < 120; a++)
    {
      OutGroupGenericCode_AC[a] = ' ';
      OutGGenericCodeCode_AT[a] = null;
      OutGGenericCodeCode_AS[a] = ' ';
      OutGGenericCodeCode[a] = "          ";
      OutGGenericCodeEngDescription_AT[a] = null;
      OutGGenericCodeEngDescription_AS[a] = ' ';
      OutGGenericCodeEngDescription[a] = 
        "                                        ";
      OutGGenericCodeAfrDescription_AT[a] = null;
      OutGGenericCodeAfrDescription_AS[a] = ' ';
      OutGGenericCodeAfrDescription[a] = 
        "                                        ";
      OutGGenericCodeInUseFlag_AT[a] = null;
      OutGGenericCodeInUseFlag_AS[a] = ' ';
      OutGGenericCodeInUseFlag[a] = " ";
      OutGGenericCodeInfo_AT[a] = null;
      OutGGenericCodeInfo_AS[a] = ' ';
      OutGGenericCodeInfo[a] = "                                        ";
      OutGCsfLineActionBarAction_AT[a] = null;
      OutGCsfLineActionBarAction_AS[a] = ' ';
      OutGCsfLineActionBarAction[a] = " ";
      OutGCsfLineActionBarLineReturnCode_AT[a] = null;
      OutGCsfLineActionBarLineReturnCode_AS[a] = ' ';
      OutGCsfLineActionBarLineReturnCode[a] = 0;
      OutGCsfLineActionBarSelectionFlag_AT[a] = null;
      OutGCsfLineActionBarSelectionFlag_AS[a] = ' ';
      OutGCsfLineActionBarSelectionFlag[a] = " ";
      OutGCsfLineActionBarTranslatedAction_AT[a] = null;
      OutGCsfLineActionBarTranslatedAction_AS[a] = ' ';
      OutGCsfLineActionBarTranslatedAction[a] = " ";
    }
    OutputWsUserNumber_AT = null;
    OutputWsUserNumber_AS = ' ';
    OutputWsUserNumber = 0;
    OutputWsPrinterCode_AT = null;
    OutputWsPrinterCode_AS = ' ';
    OutputWsPrinterCode = "          ";
    OutCsfStringsString500_AT = null;
    OutCsfStringsString500_AS = ' ';
    OutCsfStringsString500 = "";
    OutCsfClientServerCommunicationsReturnCode_AT = null;
    OutCsfClientServerCommunicationsReturnCode_AS = ' ';
    OutCsfClientServerCommunicationsReturnCode = 0;
    OutCsfClientServerCommunicationsServerVersionNumber_AT = null;
    OutCsfClientServerCommunicationsServerVersionNumber_AS = ' ';
    OutCsfClientServerCommunicationsServerVersionNumber = 0;
    OutCsfClientServerCommunicationsServerRevisionNumber_AT = null;
    OutCsfClientServerCommunicationsServerRevisionNumber_AS = ' ';
    OutCsfClientServerCommunicationsServerRevisionNumber = 0;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AT = null;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AS = ' ';
    OutCsfClientServerCommunicationsServerDevelopmentPhase = " ";
    OutCsfClientServerCommunicationsAction_AT = null;
    OutCsfClientServerCommunicationsAction_AS = ' ';
    OutCsfClientServerCommunicationsAction = "  ";
    OutCsfClientServerCommunicationsClientIsGuiFlag_AT = null;
    OutCsfClientServerCommunicationsClientIsGuiFlag_AS = ' ';
    OutCsfClientServerCommunicationsClientIsGuiFlag = " ";
    OutCsfClientServerCommunicationsServerDate_AT = null;
    OutCsfClientServerCommunicationsServerDate_AS = ' ';
    OutCsfClientServerCommunicationsServerDate = 00000000;
    OutCsfClientServerCommunicationsServerTime_AT = null;
    OutCsfClientServerCommunicationsServerTime_AS = ' ';
    OutCsfClientServerCommunicationsServerTime = 00000000;
    OutCsfClientServerCommunicationsServerTimestamp_AT = null;
    OutCsfClientServerCommunicationsServerTimestamp_AS = ' ';
    OutCsfClientServerCommunicationsServerTimestamp = "00000000000000000000";
    OutCsfClientServerCommunicationsServerTransactionCode_AT = null;
    OutCsfClientServerCommunicationsServerTransactionCode_AS = ' ';
    OutCsfClientServerCommunicationsServerTransactionCode = "        ";
    OutCsfClientServerCommunicationsServerUserId_AT = null;
    OutCsfClientServerCommunicationsServerUserId_AS = ' ';
    OutCsfClientServerCommunicationsServerUserId = "        ";
    OutCsfClientServerCommunicationsServerRollbackFlag_AT = null;
    OutCsfClientServerCommunicationsServerRollbackFlag_AS = ' ';
    OutCsfClientServerCommunicationsServerRollbackFlag = " ";
    OutCsfClientServerCommunicationsActionsPendingFlag_AT = null;
    OutCsfClientServerCommunicationsActionsPendingFlag_AS = ' ';
    OutCsfClientServerCommunicationsActionsPendingFlag = " ";
    OutCsfClientServerCommunicationsClientVersionNumber_AT = null;
    OutCsfClientServerCommunicationsClientVersionNumber_AS = ' ';
    OutCsfClientServerCommunicationsClientVersionNumber = 0;
    OutCsfClientServerCommunicationsClientRevisionNumber_AT = null;
    OutCsfClientServerCommunicationsClientRevisionNumber_AS = ' ';
    OutCsfClientServerCommunicationsClientRevisionNumber = 0;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AT = null;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AS = ' ';
    OutCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    OutCsfClientServerCommunicationsListLinkFlag_AT = null;
    OutCsfClientServerCommunicationsListLinkFlag_AS = ' ';
    OutCsfClientServerCommunicationsListLinkFlag = " ";
    OutCsfClientServerCommunicationsCancelFlag_AT = null;
    OutCsfClientServerCommunicationsCancelFlag_AS = ' ';
    OutCsfClientServerCommunicationsCancelFlag = " ";
    OutCsfClientServerCommunicationsMaintLinkFlag_AT = null;
    OutCsfClientServerCommunicationsMaintLinkFlag_AS = ' ';
    OutCsfClientServerCommunicationsMaintLinkFlag = " ";
    OutCsfClientServerCommunicationsForceDatabaseRead_AT = null;
    OutCsfClientServerCommunicationsForceDatabaseRead_AS = ' ';
    OutCsfClientServerCommunicationsForceDatabaseRead = " ";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "OutCsfEventCommunications", 
          "CsfEventCommunications", "RgvExistingLineSelectedFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)2, "", "OutCsfEventCommunications", 
          "CsfEventCommunications", "RgvNewLineSelectedFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)3, "", "OutGenericCode", "GenericCode", "Code", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)4, "", "OutGenericCode", "GenericCode", 
          "EngDescription", VDFEntry.TYPE_STRING, (short)1, (short)0, 40, (
          short)0, null), 
        new VDFEntry((int)5, "", "OutGenericCode", "GenericCode", 
          "AfrDescription", VDFEntry.TYPE_STRING, (short)1, (short)0, 40, (
          short)0, null), 
        new VDFEntry((int)6, "", "OutGenericCode", "GenericCode", "InUseFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)7, "", "OutGenericCode", "GenericCode", "Info", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 40, (short)0, null), 
        new VDFEntry((int)8, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "Path", VDFEntry.TYPE_STRING, (short)1, (
          short)0, 42, (short)0, null), 
        new VDFEntry((int)9, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "Filename", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 20, (short)0, null), 
        new VDFEntry((int)10, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "SupressFormFeed", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)11, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "PrintOptions", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 132, (short)0, null), 
        new VDFEntry((int)12, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "PrinterCode", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)13, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "Function", VDFEntry.TYPE_STRING, (short)1,
           (short)0, 8, (short)0, null), 
        new VDFEntry((int)14, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "PathAndFilename", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 256, (short)0, null), 
        new VDFEntry((int)15, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "ProgramName", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)16, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "ReportWidth", VDFEntry.TYPE_SHORT, (short)
          1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)17, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "StartingLineCount", VDFEntry.TYPE_INT, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)18, "", "OutWizfuncReportingControl", 
          "WizfuncReportingControl", "EndingLineCount", VDFEntry.TYPE_INT, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)19, "", "OutGenericCategory", "GenericCategory", 
          "Code", VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)20, "", "OutGenericCategory", "GenericCategory", 
          "Description", VDFEntry.TYPE_STRING, (short)1, (short)0, 40, (short)0,
           null), 
        new VDFEntry((int)21, "", "OutGenericCategory", "GenericCategory", 
          "InUseFlag", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, 
          null), 
        new VDFEntry((int)22, "OutGroupGenericCode", "", "", "MA", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 4, (short)0, null), 
        new VDFEntry((int)23, "OutGroupGenericCode", "", "", "AC", 
          VDFEntry.TYPE_CHAR, (short)120, (short)0, 1, (short)0, null), 
        new VDFEntry((int)24, "OutGroupGenericCode", "OutGGenericCode", 
          "GenericCode", "Code", VDFEntry.TYPE_STRING, (short)120, (short)0, 10,
           (short)0, null), 
        new VDFEntry((int)25, "OutGroupGenericCode", "OutGGenericCode", 
          "GenericCode", "EngDescription", VDFEntry.TYPE_STRING, (short)120, (
          short)0, 40, (short)0, null), 
        new VDFEntry((int)26, "OutGroupGenericCode", "OutGGenericCode", 
          "GenericCode", "AfrDescription", VDFEntry.TYPE_STRING, (short)120, (
          short)0, 40, (short)0, null), 
        new VDFEntry((int)27, "OutGroupGenericCode", "OutGGenericCode", 
          "GenericCode", "InUseFlag", VDFEntry.TYPE_STRING, (short)120, (short)
          0, 1, (short)0, null), 
        new VDFEntry((int)28, "OutGroupGenericCode", "OutGGenericCode", 
          "GenericCode", "Info", VDFEntry.TYPE_STRING, (short)120, (short)0, 40,
           (short)0, null), 
        new VDFEntry((int)29, "OutGroupGenericCode", "OutGCsfLineActionBar", 
          "CsfLineActionBar", "Action", VDFEntry.TYPE_STRING, (short)120, (
          short)0, 1, (short)0, null), 
        new VDFEntry((int)30, "OutGroupGenericCode", "OutGCsfLineActionBar", 
          "CsfLineActionBar", "LineReturnCode", VDFEntry.TYPE_SHORT, (short)120,
           (short)0, 2, (short)0, null), 
        new VDFEntry((int)31, "OutGroupGenericCode", "OutGCsfLineActionBar", 
          "CsfLineActionBar", "SelectionFlag", VDFEntry.TYPE_STRING, (short)120,
           (short)0, 1, (short)0, null), 
        new VDFEntry((int)32, "OutGroupGenericCode", "OutGCsfLineActionBar", 
          "CsfLineActionBar", "TranslatedAction", VDFEntry.TYPE_STRING, (short)
          120, (short)0, 1, (short)0, null), 
        new VDFEntry((int)33, "", "OutputWsUser", "WsUser", "Number", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)34, "", "OutputWsPrinter", "WsPrinter", "Code", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)35, "", "OutCsfStrings", "CsfStrings", "String500", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 500, (short)0, null), 
        new VDFEntry((int)36, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ReturnCode", VDFEntry.TYPE_SHORT, (
          short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)37, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerVersionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)38, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerRevisionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)39, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerDevelopmentPhase", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)40, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "Action", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)41, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientIsGuiFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)42, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerDate", VDFEntry.TYPE_DATE, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)43, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerTime", VDFEntry.TYPE_TIME, (
          short)1, (short)0, 6, (short)0, null), 
        new VDFEntry((int)44, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerTimestamp", 
          VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)45, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerTransactionCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)46, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerUserId", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)47, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ServerRollbackFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)48, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ActionsPendingFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)49, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientVersionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)50, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientRevisionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)51, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientDevelopmentPhase", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)52, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ListLinkFlag", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)53, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "CancelFlag", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)54, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "MaintLinkFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)55, "", "OutCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ForceDatabaseRead", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      OutCsfEventCommunicationsRgvExistingLineSelectedFlag = ((String)
        vdf.getEntries()[0].getDataValue().getObject());
    }
    else 
    {
      OutCsfEventCommunicationsRgvExistingLineSelectedFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      OutCsfEventCommunicationsRgvNewLineSelectedFlag = ((String)vdf.getEntries(
        )[1].getDataValue().getObject());
    }
    else 
    {
      OutCsfEventCommunicationsRgvNewLineSelectedFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      OutGenericCodeCode = ((String)vdf.getEntries()[2].getDataValue()
        .getObject());
    }
    else 
    {
      OutGenericCodeCode = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      OutGenericCodeEngDescription = ((String)vdf.getEntries()[3].getDataValue()
        .getObject());
    }
    else 
    {
      OutGenericCodeEngDescription = "                                        "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      OutGenericCodeAfrDescription = ((String)vdf.getEntries()[4].getDataValue()
        .getObject());
    }
    else 
    {
      OutGenericCodeAfrDescription = "                                        "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      OutGenericCodeInUseFlag = ((String)vdf.getEntries()[5].getDataValue()
        .getObject());
    }
    else 
    {
      OutGenericCodeInUseFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      OutGenericCodeInfo = ((String)vdf.getEntries()[6].getDataValue()
        .getObject());
    }
    else 
    {
      OutGenericCodeInfo = "                                        ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlPath = ((String)vdf.getEntries()[7]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlPath = 
        "                                          ";
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlFilename = ((String)vdf.getEntries()[8]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlFilename = "                    ";
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlSupressFormFeed = ((String)vdf.getEntries()[9]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlSupressFormFeed = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlPrintOptions = ((String)vdf.getEntries()[10]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlPrintOptions = "";
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlPrinterCode = ((String)vdf.getEntries()[11]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlPrinterCode = "";
    }
    // predicate view item
    if ( vdf.getEntries()[12].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlFunction = ((String)vdf.getEntries()[12]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlFunction = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[13].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlPathAndFilename = ((String)vdf.getEntries()[13]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlPathAndFilename = "";
    }
    // predicate view item
    if ( vdf.getEntries()[14].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlProgramName = ((String)vdf.getEntries()[14]
        .getDataValue().getObject());
    }
    else 
    {
      OutWizfuncReportingControlProgramName = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[15].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlReportWidth = ((Short)vdf.getEntries()[15]
        .getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutWizfuncReportingControlReportWidth = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[16].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlStartingLineCount = ((Integer)vdf.getEntries()[
        16].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutWizfuncReportingControlStartingLineCount = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[17].getDataValue().getObject() != null )
    {
      OutWizfuncReportingControlEndingLineCount = ((Integer)vdf.getEntries()[17]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      OutWizfuncReportingControlEndingLineCount = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[18].getDataValue().getObject() != null )
    {
      OutGenericCategoryCode = ((Short)vdf.getEntries()[18].getDataValue()
        .getObject()).shortValue();
    }
    else 
    {
      OutGenericCategoryCode = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[19].getDataValue().getObject() != null )
    {
      OutGenericCategoryDescription = ((String)vdf.getEntries()[19]
        .getDataValue().getObject());
    }
    else 
    {
      OutGenericCategoryDescription = "                                        "
        ;
    }
    // predicate view item
    if ( vdf.getEntries()[20].getDataValue().getObject() != null )
    {
      OutGenericCategoryInUseFlag = ((String)vdf.getEntries()[20].getDataValue()
        .getObject());
    }
    else 
    {
      OutGenericCategoryInUseFlag = " ";
    }
    // group view current cardinality
    if ( vdf.getEntries()[21].getDataValue().getObject() != null )
    {
      OutGroupGenericCode_MA = ((Integer)vdf.getEntries()[21].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      OutGroupGenericCode_MA = ' ';
    }
    // group view active flags
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[22].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGroupGenericCode_AC[adim0] = ((Character)((VDFEntryObject [])
          vdf.getEntries()[22].getDataValue().getObject())[adim0].getObject())
          .charValue();
      }
      else 
      {
        OutGroupGenericCode_AC[adim0] = ' ';
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[23].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGGenericCodeCode[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[23].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGGenericCodeCode[adim0] = "          ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[24].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGGenericCodeEngDescription[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[24].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGGenericCodeEngDescription[adim0] = 
          "                                        ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[25].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGGenericCodeAfrDescription[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[25].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGGenericCodeAfrDescription[adim0] = 
          "                                        ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[26].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGGenericCodeInUseFlag[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[26].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGGenericCodeInUseFlag[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[27].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGGenericCodeInfo[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[27].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGGenericCodeInfo[adim0] = "                                        "
          ;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[28].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfLineActionBarAction[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[28].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGCsfLineActionBarAction[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[29].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfLineActionBarLineReturnCode[adim0] = ((Short)((VDFEntryObject [])
          vdf.getEntries()[29].getDataValue().getObject())[adim0].getObject())
          .shortValue();
      }
      else 
      {
        OutGCsfLineActionBarLineReturnCode[adim0] = 0;
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[30].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfLineActionBarSelectionFlag[adim0] = ((String)((VDFEntryObject [])
          vdf.getEntries()[30].getDataValue().getObject())[adim0].getObject());
      }
      else 
      {
        OutGCsfLineActionBarSelectionFlag[adim0] = " ";
      }
    }
    // current cardinality group view items
    for(int adim0 = 0; adim0 < OutGroupGenericCode_MA; adim0++)
    {
      if ( ((VDFEntryObject [])vdf.getEntries()[31].getDataValue().getObject())[
        adim0].getObject() != null )
      {
        OutGCsfLineActionBarTranslatedAction[adim0] = ((String)((VDFEntryObject 
          [])vdf.getEntries()[31].getDataValue().getObject())[adim0].getObject()
          );
      }
      else 
      {
        OutGCsfLineActionBarTranslatedAction[adim0] = " ";
      }
    }
    // predicate view item
    if ( vdf.getEntries()[32].getDataValue().getObject() != null )
    {
      OutputWsUserNumber = ((Integer)vdf.getEntries()[32].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      OutputWsUserNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[33].getDataValue().getObject() != null )
    {
      OutputWsPrinterCode = ((String)vdf.getEntries()[33].getDataValue()
        .getObject());
    }
    else 
    {
      OutputWsPrinterCode = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[34].getDataValue().getObject() != null )
    {
      OutCsfStringsString500 = ((String)vdf.getEntries()[34].getDataValue()
        .getObject());
    }
    else 
    {
      OutCsfStringsString500 = "";
    }
    // predicate view item
    if ( vdf.getEntries()[35].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsReturnCode = ((Short)vdf.getEntries()[35]
        .getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsReturnCode = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[36].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerVersionNumber = ((Short)
        vdf.getEntries()[36].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerVersionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[37].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerRevisionNumber = ((Short)
        vdf.getEntries()[37].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerRevisionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[38].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerDevelopmentPhase = ((String)
        vdf.getEntries()[38].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerDevelopmentPhase = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[39].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsAction = ((String)vdf.getEntries()[39]
        .getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsAction = "  ";
    }
    // predicate view item
    if ( vdf.getEntries()[40].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientIsGuiFlag = ((String)vdf.getEntries(
        )[40].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsClientIsGuiFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[41].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerDate = ((Integer)vdf.getEntries()[
        41].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[42].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerTime = ((Integer)vdf.getEntries()[
        42].getDataValue().getObject()).intValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsServerTime = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[43].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerTimestamp = ((String)vdf.getEntries(
        )[43].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerTimestamp = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[44].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerTransactionCode = ((String)
        vdf.getEntries()[44].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerTransactionCode = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[45].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerUserId = ((String)vdf.getEntries()[
        45].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerUserId = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[46].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsServerRollbackFlag = ((String)
        vdf.getEntries()[46].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsServerRollbackFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[47].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsActionsPendingFlag = ((String)
        vdf.getEntries()[47].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsActionsPendingFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[48].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientVersionNumber = ((Short)
        vdf.getEntries()[48].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsClientVersionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[49].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientRevisionNumber = ((Short)
        vdf.getEntries()[49].getDataValue().getObject()).shortValue();
    }
    else 
    {
      OutCsfClientServerCommunicationsClientRevisionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[50].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsClientDevelopmentPhase = ((String)
        vdf.getEntries()[50].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[51].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsListLinkFlag = ((String)vdf.getEntries()[
        51].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsListLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[52].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsCancelFlag = ((String)vdf.getEntries()[52]
        .getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsCancelFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[53].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsMaintLinkFlag = ((String)vdf.getEntries()[
        53].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsMaintLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[54].getDataValue().getObject() != null )
    {
      OutCsfClientServerCommunicationsForceDatabaseRead = ((String)
        vdf.getEntries()[54].getDataValue().getObject());
    }
    else 
    {
      OutCsfClientServerCommunicationsForceDatabaseRead = " ";
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(
      OutCsfEventCommunicationsRgvExistingLineSelectedFlag);
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(
      OutCsfEventCommunicationsRgvNewLineSelectedFlag);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(OutGenericCodeCode);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(OutGenericCodeEngDescription);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(OutGenericCodeAfrDescription);
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(OutGenericCodeInUseFlag);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(OutGenericCodeInfo);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(OutWizfuncReportingControlPath)
      ;
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(
      OutWizfuncReportingControlFilename);
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(
      OutWizfuncReportingControlSupressFormFeed);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(
      OutWizfuncReportingControlPrintOptions);
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(
      OutWizfuncReportingControlPrinterCode);
    // predicate view item
    vdf.getEntries()[12].getDataValue().setObject(
      OutWizfuncReportingControlFunction);
    // predicate view item
    vdf.getEntries()[13].getDataValue().setObject(
      OutWizfuncReportingControlPathAndFilename);
    // predicate view item
    vdf.getEntries()[14].getDataValue().setObject(
      OutWizfuncReportingControlProgramName);
    // predicate view item
    vdf.getEntries()[15].getDataValue().setObject(new Short(
      OutWizfuncReportingControlReportWidth));
    // predicate view item
    vdf.getEntries()[16].getDataValue().setObject(new Integer(
      OutWizfuncReportingControlStartingLineCount));
    // predicate view item
    vdf.getEntries()[17].getDataValue().setObject(new Integer(
      OutWizfuncReportingControlEndingLineCount));
    // predicate view item
    vdf.getEntries()[18].getDataValue().setObject(new Short(
      OutGenericCategoryCode));
    // predicate view item
    vdf.getEntries()[19].getDataValue().setObject(OutGenericCategoryDescription)
      ;
    // predicate view item
    vdf.getEntries()[20].getDataValue().setObject(OutGenericCategoryInUseFlag);
    // group view current cardinality
    vdf.getEntries()[21].getDataValue().setObject(new Integer(
      OutGroupGenericCode_MA));
    // group view active flags
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      if ( adim0 < OutGroupGenericCode_MA )
      {
        ((VDFEntryObject [])vdf.getEntries()[22].getDataValue().getObject())[
          adim0].setObject(new Character('Y'));
      }
      else 
      {
        ((VDFEntryObject [])vdf.getEntries()[22].getDataValue().getObject())[
          adim0].setObject(new Character('N'));
      }
    }
    vdf.getEntries()[22].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[23].getDataValue().getObject())[
        adim0].setObject(OutGGenericCodeCode[adim0]);
    }
    vdf.getEntries()[23].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[24].getDataValue().getObject())[
        adim0].setObject(OutGGenericCodeEngDescription[adim0]);
    }
    vdf.getEntries()[24].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[25].getDataValue().getObject())[
        adim0].setObject(OutGGenericCodeAfrDescription[adim0]);
    }
    vdf.getEntries()[25].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[26].getDataValue().getObject())[
        adim0].setObject(OutGGenericCodeInUseFlag[adim0]);
    }
    vdf.getEntries()[26].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[27].getDataValue().getObject())[
        adim0].setObject(OutGGenericCodeInfo[adim0]);
    }
    vdf.getEntries()[27].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[28].getDataValue().getObject())[
        adim0].setObject(OutGCsfLineActionBarAction[adim0]);
    }
    vdf.getEntries()[28].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[29].getDataValue().getObject())[
        adim0].setObject(new Short(OutGCsfLineActionBarLineReturnCode[adim0]));
    }
    vdf.getEntries()[29].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[30].getDataValue().getObject())[
        adim0].setObject(OutGCsfLineActionBarSelectionFlag[adim0]);
    }
    vdf.getEntries()[30].setCountUsed((short)OutGroupGenericCode_MA);
    // current cardinality group view items
    for(int adim0 = 0; adim0 < 120; adim0++)
    {
      ((VDFEntryObject [])vdf.getEntries()[31].getDataValue().getObject())[
        adim0].setObject(OutGCsfLineActionBarTranslatedAction[adim0]);
    }
    vdf.getEntries()[31].setCountUsed((short)OutGroupGenericCode_MA);
    // predicate view item
    vdf.getEntries()[32].getDataValue().setObject(new Integer(
      OutputWsUserNumber));
    // predicate view item
    vdf.getEntries()[33].getDataValue().setObject(OutputWsPrinterCode);
    // predicate view item
    vdf.getEntries()[34].getDataValue().setObject(OutCsfStringsString500);
    // predicate view item
    vdf.getEntries()[35].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsReturnCode));
    // predicate view item
    vdf.getEntries()[36].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsServerVersionNumber));
    // predicate view item
    vdf.getEntries()[37].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsServerRevisionNumber));
    // predicate view item
    vdf.getEntries()[38].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerDevelopmentPhase);
    // predicate view item
    vdf.getEntries()[39].getDataValue().setObject(
      OutCsfClientServerCommunicationsAction);
    // predicate view item
    vdf.getEntries()[40].getDataValue().setObject(
      OutCsfClientServerCommunicationsClientIsGuiFlag);
    // predicate view item
    vdf.getEntries()[41].getDataValue().setObject(new Integer(
      OutCsfClientServerCommunicationsServerDate));
    // predicate view item
    vdf.getEntries()[42].getDataValue().setObject(new Integer(
      OutCsfClientServerCommunicationsServerTime));
    // predicate view item
    vdf.getEntries()[43].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerTimestamp);
    // predicate view item
    vdf.getEntries()[44].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerTransactionCode);
    // predicate view item
    vdf.getEntries()[45].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerUserId);
    // predicate view item
    vdf.getEntries()[46].getDataValue().setObject(
      OutCsfClientServerCommunicationsServerRollbackFlag);
    // predicate view item
    vdf.getEntries()[47].getDataValue().setObject(
      OutCsfClientServerCommunicationsActionsPendingFlag);
    // predicate view item
    vdf.getEntries()[48].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsClientVersionNumber));
    // predicate view item
    vdf.getEntries()[49].getDataValue().setObject(new Short(
      OutCsfClientServerCommunicationsClientRevisionNumber));
    // predicate view item
    vdf.getEntries()[50].getDataValue().setObject(
      OutCsfClientServerCommunicationsClientDevelopmentPhase);
    // predicate view item
    vdf.getEntries()[51].getDataValue().setObject(
      OutCsfClientServerCommunicationsListLinkFlag);
    // predicate view item
    vdf.getEntries()[52].getDataValue().setObject(
      OutCsfClientServerCommunicationsCancelFlag);
    // predicate view item
    vdf.getEntries()[53].getDataValue().setObject(
      OutCsfClientServerCommunicationsMaintLinkFlag);
    // predicate view item
    vdf.getEntries()[54].getDataValue().setObject(
      OutCsfClientServerCommunicationsForceDatabaseRead);
    return(vdf);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((GIGCF01S_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(GIGCF01S_OA orig)
  {
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AT = 
      orig.OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AT;
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AS = 
      orig.OutCsfEventCommunicationsRgvExistingLineSelectedFlag_AS;
    OutCsfEventCommunicationsRgvExistingLineSelectedFlag = 
      orig.OutCsfEventCommunicationsRgvExistingLineSelectedFlag;
    OutCsfEventCommunicationsRgvNewLineSelectedFlag_AT = 
      orig.OutCsfEventCommunicationsRgvNewLineSelectedFlag_AT;
    OutCsfEventCommunicationsRgvNewLineSelectedFlag_AS = 
      orig.OutCsfEventCommunicationsRgvNewLineSelectedFlag_AS;
    OutCsfEventCommunicationsRgvNewLineSelectedFlag = 
      orig.OutCsfEventCommunicationsRgvNewLineSelectedFlag;
    OutGenericCodeCode_AT = orig.OutGenericCodeCode_AT;
    OutGenericCodeCode_AS = orig.OutGenericCodeCode_AS;
    OutGenericCodeCode = orig.OutGenericCodeCode;
    OutGenericCodeEngDescription_AT = orig.OutGenericCodeEngDescription_AT;
    OutGenericCodeEngDescription_AS = orig.OutGenericCodeEngDescription_AS;
    OutGenericCodeEngDescription = orig.OutGenericCodeEngDescription;
    OutGenericCodeAfrDescription_AT = orig.OutGenericCodeAfrDescription_AT;
    OutGenericCodeAfrDescription_AS = orig.OutGenericCodeAfrDescription_AS;
    OutGenericCodeAfrDescription = orig.OutGenericCodeAfrDescription;
    OutGenericCodeInUseFlag_AT = orig.OutGenericCodeInUseFlag_AT;
    OutGenericCodeInUseFlag_AS = orig.OutGenericCodeInUseFlag_AS;
    OutGenericCodeInUseFlag = orig.OutGenericCodeInUseFlag;
    OutGenericCodeInfo_AT = orig.OutGenericCodeInfo_AT;
    OutGenericCodeInfo_AS = orig.OutGenericCodeInfo_AS;
    OutGenericCodeInfo = orig.OutGenericCodeInfo;
    OutWizfuncReportingControlPath_AT = orig.OutWizfuncReportingControlPath_AT;
    OutWizfuncReportingControlPath_AS = orig.OutWizfuncReportingControlPath_AS;
    OutWizfuncReportingControlPath = orig.OutWizfuncReportingControlPath;
    OutWizfuncReportingControlFilename_AT = 
      orig.OutWizfuncReportingControlFilename_AT;
    OutWizfuncReportingControlFilename_AS = 
      orig.OutWizfuncReportingControlFilename_AS;
    OutWizfuncReportingControlFilename = 
      orig.OutWizfuncReportingControlFilename;
    OutWizfuncReportingControlSupressFormFeed_AT = 
      orig.OutWizfuncReportingControlSupressFormFeed_AT;
    OutWizfuncReportingControlSupressFormFeed_AS = 
      orig.OutWizfuncReportingControlSupressFormFeed_AS;
    OutWizfuncReportingControlSupressFormFeed = 
      orig.OutWizfuncReportingControlSupressFormFeed;
    OutWizfuncReportingControlPrintOptions_AT = 
      orig.OutWizfuncReportingControlPrintOptions_AT;
    OutWizfuncReportingControlPrintOptions_AS = 
      orig.OutWizfuncReportingControlPrintOptions_AS;
    OutWizfuncReportingControlPrintOptions = 
      orig.OutWizfuncReportingControlPrintOptions;
    OutWizfuncReportingControlPrinterCode_AT = 
      orig.OutWizfuncReportingControlPrinterCode_AT;
    OutWizfuncReportingControlPrinterCode_AS = 
      orig.OutWizfuncReportingControlPrinterCode_AS;
    OutWizfuncReportingControlPrinterCode = 
      orig.OutWizfuncReportingControlPrinterCode;
    OutWizfuncReportingControlFunction_AT = 
      orig.OutWizfuncReportingControlFunction_AT;
    OutWizfuncReportingControlFunction_AS = 
      orig.OutWizfuncReportingControlFunction_AS;
    OutWizfuncReportingControlFunction = 
      orig.OutWizfuncReportingControlFunction;
    OutWizfuncReportingControlPathAndFilename_AT = 
      orig.OutWizfuncReportingControlPathAndFilename_AT;
    OutWizfuncReportingControlPathAndFilename_AS = 
      orig.OutWizfuncReportingControlPathAndFilename_AS;
    OutWizfuncReportingControlPathAndFilename = 
      orig.OutWizfuncReportingControlPathAndFilename;
    OutWizfuncReportingControlProgramName_AT = 
      orig.OutWizfuncReportingControlProgramName_AT;
    OutWizfuncReportingControlProgramName_AS = 
      orig.OutWizfuncReportingControlProgramName_AS;
    OutWizfuncReportingControlProgramName = 
      orig.OutWizfuncReportingControlProgramName;
    OutWizfuncReportingControlReportWidth_AT = 
      orig.OutWizfuncReportingControlReportWidth_AT;
    OutWizfuncReportingControlReportWidth_AS = 
      orig.OutWizfuncReportingControlReportWidth_AS;
    OutWizfuncReportingControlReportWidth = 
      orig.OutWizfuncReportingControlReportWidth;
    OutWizfuncReportingControlStartingLineCount_AT = 
      orig.OutWizfuncReportingControlStartingLineCount_AT;
    OutWizfuncReportingControlStartingLineCount_AS = 
      orig.OutWizfuncReportingControlStartingLineCount_AS;
    OutWizfuncReportingControlStartingLineCount = 
      orig.OutWizfuncReportingControlStartingLineCount;
    OutWizfuncReportingControlEndingLineCount_AT = 
      orig.OutWizfuncReportingControlEndingLineCount_AT;
    OutWizfuncReportingControlEndingLineCount_AS = 
      orig.OutWizfuncReportingControlEndingLineCount_AS;
    OutWizfuncReportingControlEndingLineCount = 
      orig.OutWizfuncReportingControlEndingLineCount;
    OutGenericCategoryCode_AT = orig.OutGenericCategoryCode_AT;
    OutGenericCategoryCode_AS = orig.OutGenericCategoryCode_AS;
    OutGenericCategoryCode = orig.OutGenericCategoryCode;
    OutGenericCategoryDescription_AT = orig.OutGenericCategoryDescription_AT;
    OutGenericCategoryDescription_AS = orig.OutGenericCategoryDescription_AS;
    OutGenericCategoryDescription = orig.OutGenericCategoryDescription;
    OutGenericCategoryInUseFlag_AT = orig.OutGenericCategoryInUseFlag_AT;
    OutGenericCategoryInUseFlag_AS = orig.OutGenericCategoryInUseFlag_AS;
    OutGenericCategoryInUseFlag = orig.OutGenericCategoryInUseFlag;
    OutGroupGenericCode_MA = orig.OutGroupGenericCode_MA;
    for(int a = 0; a < 120; a++)
    {
      OutGroupGenericCode_AC[a] = orig.OutGroupGenericCode_AC[a];
      OutGGenericCodeCode_AT[a] = orig.OutGGenericCodeCode_AT[a];
      OutGGenericCodeCode_AS[a] = orig.OutGGenericCodeCode_AS[a];
      OutGGenericCodeCode[a] = orig.OutGGenericCodeCode[a];
      OutGGenericCodeEngDescription_AT[a] = 
        orig.OutGGenericCodeEngDescription_AT[a];
      OutGGenericCodeEngDescription_AS[a] = 
        orig.OutGGenericCodeEngDescription_AS[a];
      OutGGenericCodeEngDescription[a] = orig.OutGGenericCodeEngDescription[a];
      OutGGenericCodeAfrDescription_AT[a] = 
        orig.OutGGenericCodeAfrDescription_AT[a];
      OutGGenericCodeAfrDescription_AS[a] = 
        orig.OutGGenericCodeAfrDescription_AS[a];
      OutGGenericCodeAfrDescription[a] = orig.OutGGenericCodeAfrDescription[a];
      OutGGenericCodeInUseFlag_AT[a] = orig.OutGGenericCodeInUseFlag_AT[a];
      OutGGenericCodeInUseFlag_AS[a] = orig.OutGGenericCodeInUseFlag_AS[a];
      OutGGenericCodeInUseFlag[a] = orig.OutGGenericCodeInUseFlag[a];
      OutGGenericCodeInfo_AT[a] = orig.OutGGenericCodeInfo_AT[a];
      OutGGenericCodeInfo_AS[a] = orig.OutGGenericCodeInfo_AS[a];
      OutGGenericCodeInfo[a] = orig.OutGGenericCodeInfo[a];
      OutGCsfLineActionBarAction_AT[a] = orig.OutGCsfLineActionBarAction_AT[a];
      OutGCsfLineActionBarAction_AS[a] = orig.OutGCsfLineActionBarAction_AS[a];
      OutGCsfLineActionBarAction[a] = orig.OutGCsfLineActionBarAction[a];
      OutGCsfLineActionBarLineReturnCode_AT[a] = 
        orig.OutGCsfLineActionBarLineReturnCode_AT[a];
      OutGCsfLineActionBarLineReturnCode_AS[a] = 
        orig.OutGCsfLineActionBarLineReturnCode_AS[a];
      OutGCsfLineActionBarLineReturnCode[a] = 
        orig.OutGCsfLineActionBarLineReturnCode[a];
      OutGCsfLineActionBarSelectionFlag_AT[a] = 
        orig.OutGCsfLineActionBarSelectionFlag_AT[a];
      OutGCsfLineActionBarSelectionFlag_AS[a] = 
        orig.OutGCsfLineActionBarSelectionFlag_AS[a];
      OutGCsfLineActionBarSelectionFlag[a] = 
        orig.OutGCsfLineActionBarSelectionFlag[a];
      OutGCsfLineActionBarTranslatedAction_AT[a] = 
        orig.OutGCsfLineActionBarTranslatedAction_AT[a];
      OutGCsfLineActionBarTranslatedAction_AS[a] = 
        orig.OutGCsfLineActionBarTranslatedAction_AS[a];
      OutGCsfLineActionBarTranslatedAction[a] = 
        orig.OutGCsfLineActionBarTranslatedAction[a];
    }
    OutputWsUserNumber_AT = orig.OutputWsUserNumber_AT;
    OutputWsUserNumber_AS = orig.OutputWsUserNumber_AS;
    OutputWsUserNumber = orig.OutputWsUserNumber;
    OutputWsPrinterCode_AT = orig.OutputWsPrinterCode_AT;
    OutputWsPrinterCode_AS = orig.OutputWsPrinterCode_AS;
    OutputWsPrinterCode = orig.OutputWsPrinterCode;
    OutCsfStringsString500_AT = orig.OutCsfStringsString500_AT;
    OutCsfStringsString500_AS = orig.OutCsfStringsString500_AS;
    OutCsfStringsString500 = orig.OutCsfStringsString500;
    OutCsfClientServerCommunicationsReturnCode_AT = 
      orig.OutCsfClientServerCommunicationsReturnCode_AT;
    OutCsfClientServerCommunicationsReturnCode_AS = 
      orig.OutCsfClientServerCommunicationsReturnCode_AS;
    OutCsfClientServerCommunicationsReturnCode = 
      orig.OutCsfClientServerCommunicationsReturnCode;
    OutCsfClientServerCommunicationsServerVersionNumber_AT = 
      orig.OutCsfClientServerCommunicationsServerVersionNumber_AT;
    OutCsfClientServerCommunicationsServerVersionNumber_AS = 
      orig.OutCsfClientServerCommunicationsServerVersionNumber_AS;
    OutCsfClientServerCommunicationsServerVersionNumber = 
      orig.OutCsfClientServerCommunicationsServerVersionNumber;
    OutCsfClientServerCommunicationsServerRevisionNumber_AT = 
      orig.OutCsfClientServerCommunicationsServerRevisionNumber_AT;
    OutCsfClientServerCommunicationsServerRevisionNumber_AS = 
      orig.OutCsfClientServerCommunicationsServerRevisionNumber_AS;
    OutCsfClientServerCommunicationsServerRevisionNumber = 
      orig.OutCsfClientServerCommunicationsServerRevisionNumber;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AT = 
      orig.OutCsfClientServerCommunicationsServerDevelopmentPhase_AT;
    OutCsfClientServerCommunicationsServerDevelopmentPhase_AS = 
      orig.OutCsfClientServerCommunicationsServerDevelopmentPhase_AS;
    OutCsfClientServerCommunicationsServerDevelopmentPhase = 
      orig.OutCsfClientServerCommunicationsServerDevelopmentPhase;
    OutCsfClientServerCommunicationsAction_AT = 
      orig.OutCsfClientServerCommunicationsAction_AT;
    OutCsfClientServerCommunicationsAction_AS = 
      orig.OutCsfClientServerCommunicationsAction_AS;
    OutCsfClientServerCommunicationsAction = 
      orig.OutCsfClientServerCommunicationsAction;
    OutCsfClientServerCommunicationsClientIsGuiFlag_AT = 
      orig.OutCsfClientServerCommunicationsClientIsGuiFlag_AT;
    OutCsfClientServerCommunicationsClientIsGuiFlag_AS = 
      orig.OutCsfClientServerCommunicationsClientIsGuiFlag_AS;
    OutCsfClientServerCommunicationsClientIsGuiFlag = 
      orig.OutCsfClientServerCommunicationsClientIsGuiFlag;
    OutCsfClientServerCommunicationsServerDate_AT = 
      orig.OutCsfClientServerCommunicationsServerDate_AT;
    OutCsfClientServerCommunicationsServerDate_AS = 
      orig.OutCsfClientServerCommunicationsServerDate_AS;
    OutCsfClientServerCommunicationsServerDate = 
      orig.OutCsfClientServerCommunicationsServerDate;
    OutCsfClientServerCommunicationsServerTime_AT = 
      orig.OutCsfClientServerCommunicationsServerTime_AT;
    OutCsfClientServerCommunicationsServerTime_AS = 
      orig.OutCsfClientServerCommunicationsServerTime_AS;
    OutCsfClientServerCommunicationsServerTime = 
      orig.OutCsfClientServerCommunicationsServerTime;
    OutCsfClientServerCommunicationsServerTimestamp_AT = 
      orig.OutCsfClientServerCommunicationsServerTimestamp_AT;
    OutCsfClientServerCommunicationsServerTimestamp_AS = 
      orig.OutCsfClientServerCommunicationsServerTimestamp_AS;
    OutCsfClientServerCommunicationsServerTimestamp = 
      orig.OutCsfClientServerCommunicationsServerTimestamp;
    OutCsfClientServerCommunicationsServerTransactionCode_AT = 
      orig.OutCsfClientServerCommunicationsServerTransactionCode_AT;
    OutCsfClientServerCommunicationsServerTransactionCode_AS = 
      orig.OutCsfClientServerCommunicationsServerTransactionCode_AS;
    OutCsfClientServerCommunicationsServerTransactionCode = 
      orig.OutCsfClientServerCommunicationsServerTransactionCode;
    OutCsfClientServerCommunicationsServerUserId_AT = 
      orig.OutCsfClientServerCommunicationsServerUserId_AT;
    OutCsfClientServerCommunicationsServerUserId_AS = 
      orig.OutCsfClientServerCommunicationsServerUserId_AS;
    OutCsfClientServerCommunicationsServerUserId = 
      orig.OutCsfClientServerCommunicationsServerUserId;
    OutCsfClientServerCommunicationsServerRollbackFlag_AT = 
      orig.OutCsfClientServerCommunicationsServerRollbackFlag_AT;
    OutCsfClientServerCommunicationsServerRollbackFlag_AS = 
      orig.OutCsfClientServerCommunicationsServerRollbackFlag_AS;
    OutCsfClientServerCommunicationsServerRollbackFlag = 
      orig.OutCsfClientServerCommunicationsServerRollbackFlag;
    OutCsfClientServerCommunicationsActionsPendingFlag_AT = 
      orig.OutCsfClientServerCommunicationsActionsPendingFlag_AT;
    OutCsfClientServerCommunicationsActionsPendingFlag_AS = 
      orig.OutCsfClientServerCommunicationsActionsPendingFlag_AS;
    OutCsfClientServerCommunicationsActionsPendingFlag = 
      orig.OutCsfClientServerCommunicationsActionsPendingFlag;
    OutCsfClientServerCommunicationsClientVersionNumber_AT = 
      orig.OutCsfClientServerCommunicationsClientVersionNumber_AT;
    OutCsfClientServerCommunicationsClientVersionNumber_AS = 
      orig.OutCsfClientServerCommunicationsClientVersionNumber_AS;
    OutCsfClientServerCommunicationsClientVersionNumber = 
      orig.OutCsfClientServerCommunicationsClientVersionNumber;
    OutCsfClientServerCommunicationsClientRevisionNumber_AT = 
      orig.OutCsfClientServerCommunicationsClientRevisionNumber_AT;
    OutCsfClientServerCommunicationsClientRevisionNumber_AS = 
      orig.OutCsfClientServerCommunicationsClientRevisionNumber_AS;
    OutCsfClientServerCommunicationsClientRevisionNumber = 
      orig.OutCsfClientServerCommunicationsClientRevisionNumber;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AT = 
      orig.OutCsfClientServerCommunicationsClientDevelopmentPhase_AT;
    OutCsfClientServerCommunicationsClientDevelopmentPhase_AS = 
      orig.OutCsfClientServerCommunicationsClientDevelopmentPhase_AS;
    OutCsfClientServerCommunicationsClientDevelopmentPhase = 
      orig.OutCsfClientServerCommunicationsClientDevelopmentPhase;
    OutCsfClientServerCommunicationsListLinkFlag_AT = 
      orig.OutCsfClientServerCommunicationsListLinkFlag_AT;
    OutCsfClientServerCommunicationsListLinkFlag_AS = 
      orig.OutCsfClientServerCommunicationsListLinkFlag_AS;
    OutCsfClientServerCommunicationsListLinkFlag = 
      orig.OutCsfClientServerCommunicationsListLinkFlag;
    OutCsfClientServerCommunicationsCancelFlag_AT = 
      orig.OutCsfClientServerCommunicationsCancelFlag_AT;
    OutCsfClientServerCommunicationsCancelFlag_AS = 
      orig.OutCsfClientServerCommunicationsCancelFlag_AS;
    OutCsfClientServerCommunicationsCancelFlag = 
      orig.OutCsfClientServerCommunicationsCancelFlag;
    OutCsfClientServerCommunicationsMaintLinkFlag_AT = 
      orig.OutCsfClientServerCommunicationsMaintLinkFlag_AT;
    OutCsfClientServerCommunicationsMaintLinkFlag_AS = 
      orig.OutCsfClientServerCommunicationsMaintLinkFlag_AS;
    OutCsfClientServerCommunicationsMaintLinkFlag = 
      orig.OutCsfClientServerCommunicationsMaintLinkFlag;
    OutCsfClientServerCommunicationsForceDatabaseRead_AT = 
      orig.OutCsfClientServerCommunicationsForceDatabaseRead_AT;
    OutCsfClientServerCommunicationsForceDatabaseRead_AS = 
      orig.OutCsfClientServerCommunicationsForceDatabaseRead_AS;
    OutCsfClientServerCommunicationsForceDatabaseRead = 
      orig.OutCsfClientServerCommunicationsForceDatabaseRead;
  }
}
