package Srslf05h;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                            CA Gen r8
//
//           Copyright (c) 2015 CA. All rights reserved.
//
//    Name: SRSLF051_IA                      Date: 2015/03/05
//    User: pretoj                           Time: 11:26:03
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen80.vwrt.*;
import com.ca.gen80.vwrt.types.*;
import com.ca.gen80.vwrt.vdf.*;
import com.ca.gen80.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: SRSLF051_IA
 **/
public class SRSLF051_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IN_STAFF_NAME
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InStaffNameCsfStringsString30
   **/
  public char InStaffNameCsfStringsString30_AS;
  /**
   * Attribute for: InStaffNameCsfStringsString30
   **/
  public String InStaffNameCsfStringsString30;
  // Entity View: IN
  //        Type: WS_STAFF
  /**
   * Attribute missing flag for: InWsStaffPersno
   **/
  public char InWsStaffPersno_AS;
  /**
   * Attribute for: InWsStaffPersno
   **/
  public int InWsStaffPersno;
  /**
   * Attribute missing flag for: InWsStaffMkRcCode
   **/
  public char InWsStaffMkRcCode_AS;
  /**
   * Attribute for: InWsStaffMkRcCode
   **/
  public String InWsStaffMkRcCode;
  // Entity View: IN_USER_NAME
  //        Type: CSF_STRINGS
  /**
   * Attribute missing flag for: InUserNameCsfStringsString30
   **/
  public char InUserNameCsfStringsString30_AS;
  /**
   * Attribute for: InUserNameCsfStringsString30
   **/
  public String InUserNameCsfStringsString30;
  // Entity View: IN_USER
  //        Type: WS_STAFF
  /**
   * Attribute missing flag for: InUserWsStaffPersno
   **/
  public char InUserWsStaffPersno_AS;
  /**
   * Attribute for: InUserWsStaffPersno
   **/
  public int InUserWsStaffPersno;
  /**
   * Attribute missing flag for: InUserWsStaffSurname
   **/
  public char InUserWsStaffSurname_AS;
  /**
   * Attribute for: InUserWsStaffSurname
   **/
  public String InUserWsStaffSurname;
  /**
   * Attribute missing flag for: InUserWsStaffInitials
   **/
  public char InUserWsStaffInitials_AS;
  /**
   * Attribute for: InUserWsStaffInitials
   **/
  public String InUserWsStaffInitials;
  /**
   * Attribute missing flag for: InUserWsStaffTitle
   **/
  public char InUserWsStaffTitle_AS;
  /**
   * Attribute for: InUserWsStaffTitle
   **/
  public String InUserWsStaffTitle;
  /**
   * Attribute missing flag for: InUserWsStaffEmailAddress
   **/
  public char InUserWsStaffEmailAddress_AS;
  /**
   * Attribute for: InUserWsStaffEmailAddress
   **/
  public String InUserWsStaffEmailAddress;
  /**
   * Attribute missing flag for: InUserWsStaffContactTelno
   **/
  public char InUserWsStaffContactTelno_AS;
  /**
   * Attribute for: InUserWsStaffContactTelno
   **/
  public String InUserWsStaffContactTelno;
  // Entity View: IN
  //        Type: SMS_LOG
  /**
   * Attribute missing flag for: InSmsLogMkBatchNr
   **/
  public char InSmsLogMkBatchNr_AS;
  /**
   * Attribute for: InSmsLogMkBatchNr
   **/
  public int InSmsLogMkBatchNr;
  /**
   * Attribute missing flag for: InSmsLogReferenceNr
   **/
  public char InSmsLogReferenceNr_AS;
  /**
   * Attribute for: InSmsLogReferenceNr
   **/
  public int InSmsLogReferenceNr;
  /**
   * Attribute missing flag for: InSmsLogCellNr
   **/
  public char InSmsLogCellNr_AS;
  /**
   * Attribute for: InSmsLogCellNr
   **/
  public String InSmsLogCellNr;
  /**
   * Attribute missing flag for: InSmsLogMessage
   **/
  public char InSmsLogMessage_AS;
  /**
   * Attribute for: InSmsLogMessage
   **/
  public String InSmsLogMessage;
  /**
   * Attribute missing flag for: InSmsLogSentOn
   **/
  public char InSmsLogSentOn_AS;
  /**
   * Attribute for: InSmsLogSentOn
   **/
  public String InSmsLogSentOn;
  /**
   * Attribute missing flag for: InSmsLogDeliveredOn
   **/
  public char InSmsLogDeliveredOn_AS;
  /**
   * Attribute for: InSmsLogDeliveredOn
   **/
  public String InSmsLogDeliveredOn;
  /**
   * Attribute missing flag for: InSmsLogMessageStatus
   **/
  public char InSmsLogMessageStatus_AS;
  /**
   * Attribute for: InSmsLogMessageStatus
   **/
  public String InSmsLogMessageStatus;
  /**
   * Attribute missing flag for: InSmsLogMkPersNr
   **/
  public char InSmsLogMkPersNr_AS;
  /**
   * Attribute for: InSmsLogMkPersNr
   **/
  public int InSmsLogMkPersNr;
  /**
   * Attribute missing flag for: InSmsLogSequenceNr
   **/
  public char InSmsLogSequenceNr_AS;
  /**
   * Attribute for: InSmsLogSequenceNr
   **/
  public int InSmsLogSequenceNr;
  // Entity View: IN
  //        Type: CSF_CLIENT_SERVER_COMMUNICATIONS
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientVersionNumber
   **/
  public char InCsfClientServerCommunicationsClientVersionNumber_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientVersionNumber
   **/
  public short InCsfClientServerCommunicationsClientVersionNumber;
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientRevisionNumber
   **/
  public char InCsfClientServerCommunicationsClientRevisionNumber_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientRevisionNumber
   **/
  public short InCsfClientServerCommunicationsClientRevisionNumber;
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public char InCsfClientServerCommunicationsClientDevelopmentPhase_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientDevelopmentPhase
   **/
  public String InCsfClientServerCommunicationsClientDevelopmentPhase;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsAction
   **/
  public char InCsfClientServerCommunicationsAction_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsAction
   **/
  public String InCsfClientServerCommunicationsAction;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public char InCsfClientServerCommunicationsClientIsGuiFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientIsGuiFlag
   **/
  public String InCsfClientServerCommunicationsClientIsGuiFlag;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientDate
   **/
  public char InCsfClientServerCommunicationsClientDate_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientDate
   **/
  public int InCsfClientServerCommunicationsClientDate;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientTime
   **/
  public char InCsfClientServerCommunicationsClientTime_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientTime
   **/
  public int InCsfClientServerCommunicationsClientTime;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientTimestamp
   **/
  public char InCsfClientServerCommunicationsClientTimestamp_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientTimestamp
   **/
  public String InCsfClientServerCommunicationsClientTimestamp;
  /**
   * Attribute missing flag for: 
    InCsfClientServerCommunicationsClientTransactionCode
   **/
  public char InCsfClientServerCommunicationsClientTransactionCode_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientTransactionCode
   **/
  public String InCsfClientServerCommunicationsClientTransactionCode;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsClientUserId
   **/
  public char InCsfClientServerCommunicationsClientUserId_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsClientUserId
   **/
  public String InCsfClientServerCommunicationsClientUserId;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsListLinkFlag
   **/
  public char InCsfClientServerCommunicationsListLinkFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsListLinkFlag
   **/
  public String InCsfClientServerCommunicationsListLinkFlag;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsMaintLinkFlag
   **/
  public char InCsfClientServerCommunicationsMaintLinkFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsMaintLinkFlag
   **/
  public String InCsfClientServerCommunicationsMaintLinkFlag;
  /**
   * Attribute missing flag for: InCsfClientServerCommunicationsFirstpassFlag
   **/
  public char InCsfClientServerCommunicationsFirstpassFlag_AS;
  /**
   * Attribute for: InCsfClientServerCommunicationsFirstpassFlag
   **/
  public String InCsfClientServerCommunicationsFirstpassFlag;
  /**
   * Default Constructor
   **/
  
  public SRSLF051_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public SRSLF051_IA(SRSLF051_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static SRSLF051_IA getInstance()
  {
    return new SRSLF051_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new SRSLF051_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    InStaffNameCsfStringsString30_AS = ' ';
    InStaffNameCsfStringsString30 = "                              ";
    InWsStaffPersno_AS = ' ';
    InWsStaffPersno = 0;
    InWsStaffMkRcCode_AS = ' ';
    InWsStaffMkRcCode = "      ";
    InUserNameCsfStringsString30_AS = ' ';
    InUserNameCsfStringsString30 = "                              ";
    InUserWsStaffPersno_AS = ' ';
    InUserWsStaffPersno = 0;
    InUserWsStaffSurname_AS = ' ';
    InUserWsStaffSurname = "                            ";
    InUserWsStaffInitials_AS = ' ';
    InUserWsStaffInitials = "          ";
    InUserWsStaffTitle_AS = ' ';
    InUserWsStaffTitle = "          ";
    InUserWsStaffEmailAddress_AS = ' ';
    InUserWsStaffEmailAddress = 
      "                                                            ";
    InUserWsStaffContactTelno_AS = ' ';
    InUserWsStaffContactTelno = "                            ";
    InSmsLogMkBatchNr_AS = ' ';
    InSmsLogMkBatchNr = 0;
    InSmsLogReferenceNr_AS = ' ';
    InSmsLogReferenceNr = 0;
    InSmsLogCellNr_AS = ' ';
    InSmsLogCellNr = "";
    InSmsLogMessage_AS = ' ';
    InSmsLogMessage = "";
    InSmsLogSentOn_AS = ' ';
    InSmsLogSentOn = "00000000000000000000";
    InSmsLogDeliveredOn_AS = ' ';
    InSmsLogDeliveredOn = "00000000000000000000";
    InSmsLogMessageStatus_AS = ' ';
    InSmsLogMessageStatus = "";
    InSmsLogMkPersNr_AS = ' ';
    InSmsLogMkPersNr = 0;
    InSmsLogSequenceNr_AS = ' ';
    InSmsLogSequenceNr = 0;
    InCsfClientServerCommunicationsClientVersionNumber_AS = ' ';
    InCsfClientServerCommunicationsClientVersionNumber = 0;
    InCsfClientServerCommunicationsClientRevisionNumber_AS = ' ';
    InCsfClientServerCommunicationsClientRevisionNumber = 0;
    InCsfClientServerCommunicationsClientDevelopmentPhase_AS = ' ';
    InCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    InCsfClientServerCommunicationsAction_AS = ' ';
    InCsfClientServerCommunicationsAction = "  ";
    InCsfClientServerCommunicationsClientIsGuiFlag_AS = ' ';
    InCsfClientServerCommunicationsClientIsGuiFlag = " ";
    InCsfClientServerCommunicationsClientDate_AS = ' ';
    InCsfClientServerCommunicationsClientDate = 00000000;
    InCsfClientServerCommunicationsClientTime_AS = ' ';
    InCsfClientServerCommunicationsClientTime = 00000000;
    InCsfClientServerCommunicationsClientTimestamp_AS = ' ';
    InCsfClientServerCommunicationsClientTimestamp = "00000000000000000000";
    InCsfClientServerCommunicationsClientTransactionCode_AS = ' ';
    InCsfClientServerCommunicationsClientTransactionCode = "        ";
    InCsfClientServerCommunicationsClientUserId_AS = ' ';
    InCsfClientServerCommunicationsClientUserId = "        ";
    InCsfClientServerCommunicationsListLinkFlag_AS = ' ';
    InCsfClientServerCommunicationsListLinkFlag = " ";
    InCsfClientServerCommunicationsMaintLinkFlag_AS = ' ';
    InCsfClientServerCommunicationsMaintLinkFlag = " ";
    InCsfClientServerCommunicationsFirstpassFlag_AS = ' ';
    InCsfClientServerCommunicationsFirstpassFlag = " ";
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "InStaffNameCsfStrings", "CsfStrings", 
          "String30", VDFEntry.TYPE_STRING, (short)1, (short)0, 30, (short)0, 
          null), 
        new VDFEntry((int)2, "", "InWsStaff", "WsStaff", "Persno", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)3, "", "InWsStaff", "WsStaff", "MkRcCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 6, (short)0, null), 
        new VDFEntry((int)4, "", "InUserNameCsfStrings", "CsfStrings", 
          "String30", VDFEntry.TYPE_STRING, (short)1, (short)0, 30, (short)0, 
          null), 
        new VDFEntry((int)5, "", "InUserWsStaff", "WsStaff", "Persno", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)6, "", "InUserWsStaff", "WsStaff", "Surname", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)7, "", "InUserWsStaff", "WsStaff", "Initials", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)8, "", "InUserWsStaff", "WsStaff", "Title", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 10, (short)0, null), 
        new VDFEntry((int)9, "", "InUserWsStaff", "WsStaff", "EmailAddress", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 60, (short)0, null), 
        new VDFEntry((int)10, "", "InUserWsStaff", "WsStaff", "ContactTelno", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 28, (short)0, null), 
        new VDFEntry((int)11, "", "InSmsLog", "SmsLog", "MkBatchNr", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)12, "", "InSmsLog", "SmsLog", "ReferenceNr", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)13, "", "InSmsLog", "SmsLog", "CellNr", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)14, "", "InSmsLog", "SmsLog", "Message", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 160, (short)0, null), 
        new VDFEntry((int)15, "", "InSmsLog", "SmsLog", "SentOn", 
          VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)16, "", "InSmsLog", "SmsLog", "DeliveredOn", 
          VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)17, "", "InSmsLog", "SmsLog", "MessageStatus", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 7, (short)0, null), 
        new VDFEntry((int)18, "", "InSmsLog", "SmsLog", "MkPersNr", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)19, "", "InSmsLog", "SmsLog", "SequenceNr", 
          VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)20, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientVersionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)21, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientRevisionNumber", 
          VDFEntry.TYPE_SHORT, (short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)22, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientDevelopmentPhase", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)23, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "Action", VDFEntry.TYPE_STRING, (
          short)1, (short)0, 2, (short)0, null), 
        new VDFEntry((int)24, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientIsGuiFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)25, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientDate", VDFEntry.TYPE_DATE, (
          short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)26, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientTime", VDFEntry.TYPE_TIME, (
          short)1, (short)0, 6, (short)0, null), 
        new VDFEntry((int)27, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientTimestamp", 
          VDFEntry.TYPE_TIMESTAMP, (short)1, (short)0, 20, (short)0, null), 
        new VDFEntry((int)28, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientTransactionCode", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)29, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ClientUserId", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 8, (short)0, null), 
        new VDFEntry((int)30, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "ListLinkFlag", VDFEntry.TYPE_STRING,
           (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)31, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "MaintLinkFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
        new VDFEntry((int)32, "", "InCsfClientServerCommunications", 
          "CsfClientServerCommunications", "FirstpassFlag", 
          VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(InStaffNameCsfStringsString30)
      ;
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(new Integer(InWsStaffPersno));
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(InWsStaffMkRcCode);
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(InUserNameCsfStringsString30);
    // predicate view item
    vdf.getEntries()[4].getDataValue().setObject(new Integer(
      InUserWsStaffPersno));
    // predicate view item
    vdf.getEntries()[5].getDataValue().setObject(InUserWsStaffSurname);
    // predicate view item
    vdf.getEntries()[6].getDataValue().setObject(InUserWsStaffInitials);
    // predicate view item
    vdf.getEntries()[7].getDataValue().setObject(InUserWsStaffTitle);
    // predicate view item
    vdf.getEntries()[8].getDataValue().setObject(InUserWsStaffEmailAddress);
    // predicate view item
    vdf.getEntries()[9].getDataValue().setObject(InUserWsStaffContactTelno);
    // predicate view item
    vdf.getEntries()[10].getDataValue().setObject(new Integer(InSmsLogMkBatchNr)
      );
    // predicate view item
    vdf.getEntries()[11].getDataValue().setObject(new Integer(
      InSmsLogReferenceNr));
    // predicate view item
    vdf.getEntries()[12].getDataValue().setObject(InSmsLogCellNr);
    // predicate view item
    vdf.getEntries()[13].getDataValue().setObject(InSmsLogMessage);
    // predicate view item
    vdf.getEntries()[14].getDataValue().setObject(InSmsLogSentOn);
    // predicate view item
    vdf.getEntries()[15].getDataValue().setObject(InSmsLogDeliveredOn);
    // predicate view item
    vdf.getEntries()[16].getDataValue().setObject(InSmsLogMessageStatus);
    // predicate view item
    vdf.getEntries()[17].getDataValue().setObject(new Integer(InSmsLogMkPersNr))
      ;
    // predicate view item
    vdf.getEntries()[18].getDataValue().setObject(new Integer(
      InSmsLogSequenceNr));
    // predicate view item
    vdf.getEntries()[19].getDataValue().setObject(new Short(
      InCsfClientServerCommunicationsClientVersionNumber));
    // predicate view item
    vdf.getEntries()[20].getDataValue().setObject(new Short(
      InCsfClientServerCommunicationsClientRevisionNumber));
    // predicate view item
    vdf.getEntries()[21].getDataValue().setObject(
      InCsfClientServerCommunicationsClientDevelopmentPhase);
    // predicate view item
    vdf.getEntries()[22].getDataValue().setObject(
      InCsfClientServerCommunicationsAction);
    // predicate view item
    vdf.getEntries()[23].getDataValue().setObject(
      InCsfClientServerCommunicationsClientIsGuiFlag);
    // predicate view item
    vdf.getEntries()[24].getDataValue().setObject(new Integer(
      InCsfClientServerCommunicationsClientDate));
    // predicate view item
    vdf.getEntries()[25].getDataValue().setObject(new Integer(
      InCsfClientServerCommunicationsClientTime));
    // predicate view item
    vdf.getEntries()[26].getDataValue().setObject(
      InCsfClientServerCommunicationsClientTimestamp);
    // predicate view item
    vdf.getEntries()[27].getDataValue().setObject(
      InCsfClientServerCommunicationsClientTransactionCode);
    // predicate view item
    vdf.getEntries()[28].getDataValue().setObject(
      InCsfClientServerCommunicationsClientUserId);
    // predicate view item
    vdf.getEntries()[29].getDataValue().setObject(
      InCsfClientServerCommunicationsListLinkFlag);
    // predicate view item
    vdf.getEntries()[30].getDataValue().setObject(
      InCsfClientServerCommunicationsMaintLinkFlag);
    // predicate view item
    vdf.getEntries()[31].getDataValue().setObject(
      InCsfClientServerCommunicationsFirstpassFlag);
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      InStaffNameCsfStringsString30 = ((String)vdf.getEntries()[0].getDataValue(
        ).getObject());
    }
    else 
    {
      InStaffNameCsfStringsString30 = "                              ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InWsStaffPersno = ((Integer)vdf.getEntries()[1].getDataValue().getObject()
        ).intValue();
    }
    else 
    {
      InWsStaffPersno = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InWsStaffMkRcCode = ((String)vdf.getEntries()[2].getDataValue().getObject(
        ));
    }
    else 
    {
      InWsStaffMkRcCode = "      ";
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InUserNameCsfStringsString30 = ((String)vdf.getEntries()[3].getDataValue()
        .getObject());
    }
    else 
    {
      InUserNameCsfStringsString30 = "                              ";
    }
    // predicate view item
    if ( vdf.getEntries()[4].getDataValue().getObject() != null )
    {
      InUserWsStaffPersno = ((Integer)vdf.getEntries()[4].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InUserWsStaffPersno = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[5].getDataValue().getObject() != null )
    {
      InUserWsStaffSurname = ((String)vdf.getEntries()[5].getDataValue()
        .getObject());
    }
    else 
    {
      InUserWsStaffSurname = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[6].getDataValue().getObject() != null )
    {
      InUserWsStaffInitials = ((String)vdf.getEntries()[6].getDataValue()
        .getObject());
    }
    else 
    {
      InUserWsStaffInitials = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[7].getDataValue().getObject() != null )
    {
      InUserWsStaffTitle = ((String)vdf.getEntries()[7].getDataValue()
        .getObject());
    }
    else 
    {
      InUserWsStaffTitle = "          ";
    }
    // predicate view item
    if ( vdf.getEntries()[8].getDataValue().getObject() != null )
    {
      InUserWsStaffEmailAddress = ((String)vdf.getEntries()[8].getDataValue()
        .getObject());
    }
    else 
    {
      InUserWsStaffEmailAddress = 
        "                                                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[9].getDataValue().getObject() != null )
    {
      InUserWsStaffContactTelno = ((String)vdf.getEntries()[9].getDataValue()
        .getObject());
    }
    else 
    {
      InUserWsStaffContactTelno = "                            ";
    }
    // predicate view item
    if ( vdf.getEntries()[10].getDataValue().getObject() != null )
    {
      InSmsLogMkBatchNr = ((Integer)vdf.getEntries()[10].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InSmsLogMkBatchNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[11].getDataValue().getObject() != null )
    {
      InSmsLogReferenceNr = ((Integer)vdf.getEntries()[11].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InSmsLogReferenceNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[12].getDataValue().getObject() != null )
    {
      InSmsLogCellNr = ((String)vdf.getEntries()[12].getDataValue().getObject())
        ;
    }
    else 
    {
      InSmsLogCellNr = "";
    }
    // predicate view item
    if ( vdf.getEntries()[13].getDataValue().getObject() != null )
    {
      InSmsLogMessage = ((String)vdf.getEntries()[13].getDataValue().getObject()
        );
    }
    else 
    {
      InSmsLogMessage = "";
    }
    // predicate view item
    if ( vdf.getEntries()[14].getDataValue().getObject() != null )
    {
      InSmsLogSentOn = ((String)vdf.getEntries()[14].getDataValue().getObject())
        ;
    }
    else 
    {
      InSmsLogSentOn = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[15].getDataValue().getObject() != null )
    {
      InSmsLogDeliveredOn = ((String)vdf.getEntries()[15].getDataValue()
        .getObject());
    }
    else 
    {
      InSmsLogDeliveredOn = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[16].getDataValue().getObject() != null )
    {
      InSmsLogMessageStatus = ((String)vdf.getEntries()[16].getDataValue()
        .getObject());
    }
    else 
    {
      InSmsLogMessageStatus = "";
    }
    // predicate view item
    if ( vdf.getEntries()[17].getDataValue().getObject() != null )
    {
      InSmsLogMkPersNr = ((Integer)vdf.getEntries()[17].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InSmsLogMkPersNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[18].getDataValue().getObject() != null )
    {
      InSmsLogSequenceNr = ((Integer)vdf.getEntries()[18].getDataValue()
        .getObject()).intValue();
    }
    else 
    {
      InSmsLogSequenceNr = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[19].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientVersionNumber = ((Short)
        vdf.getEntries()[19].getDataValue().getObject()).shortValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientVersionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[20].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientRevisionNumber = ((Short)
        vdf.getEntries()[20].getDataValue().getObject()).shortValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientRevisionNumber = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[21].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientDevelopmentPhase = ((String)
        vdf.getEntries()[21].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientDevelopmentPhase = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[22].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsAction = ((String)vdf.getEntries()[22]
        .getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsAction = "  ";
    }
    // predicate view item
    if ( vdf.getEntries()[23].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientIsGuiFlag = ((String)vdf.getEntries()
        [23].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientIsGuiFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[24].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientDate = ((Integer)vdf.getEntries()[24]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientDate = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[25].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientTime = ((Integer)vdf.getEntries()[25]
        .getDataValue().getObject()).intValue();
    }
    else 
    {
      InCsfClientServerCommunicationsClientTime = 00000000;
    }
    // predicate view item
    if ( vdf.getEntries()[26].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientTimestamp = ((String)vdf.getEntries()
        [26].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientTimestamp = "00000000000000000000";
    }
    // predicate view item
    if ( vdf.getEntries()[27].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientTransactionCode = ((String)
        vdf.getEntries()[27].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientTransactionCode = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[28].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsClientUserId = ((String)vdf.getEntries()[
        28].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsClientUserId = "        ";
    }
    // predicate view item
    if ( vdf.getEntries()[29].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsListLinkFlag = ((String)vdf.getEntries()[
        29].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsListLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[30].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsMaintLinkFlag = ((String)vdf.getEntries()[
        30].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsMaintLinkFlag = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[31].getDataValue().getObject() != null )
    {
      InCsfClientServerCommunicationsFirstpassFlag = ((String)vdf.getEntries()[
        31].getDataValue().getObject());
    }
    else 
    {
      InCsfClientServerCommunicationsFirstpassFlag = " ";
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((SRSLF051_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(SRSLF051_IA orig)
  {
    InStaffNameCsfStringsString30_AS = orig.InStaffNameCsfStringsString30_AS;
    InStaffNameCsfStringsString30 = orig.InStaffNameCsfStringsString30;
    InWsStaffPersno_AS = orig.InWsStaffPersno_AS;
    InWsStaffPersno = orig.InWsStaffPersno;
    InWsStaffMkRcCode_AS = orig.InWsStaffMkRcCode_AS;
    InWsStaffMkRcCode = orig.InWsStaffMkRcCode;
    InUserNameCsfStringsString30_AS = orig.InUserNameCsfStringsString30_AS;
    InUserNameCsfStringsString30 = orig.InUserNameCsfStringsString30;
    InUserWsStaffPersno_AS = orig.InUserWsStaffPersno_AS;
    InUserWsStaffPersno = orig.InUserWsStaffPersno;
    InUserWsStaffSurname_AS = orig.InUserWsStaffSurname_AS;
    InUserWsStaffSurname = orig.InUserWsStaffSurname;
    InUserWsStaffInitials_AS = orig.InUserWsStaffInitials_AS;
    InUserWsStaffInitials = orig.InUserWsStaffInitials;
    InUserWsStaffTitle_AS = orig.InUserWsStaffTitle_AS;
    InUserWsStaffTitle = orig.InUserWsStaffTitle;
    InUserWsStaffEmailAddress_AS = orig.InUserWsStaffEmailAddress_AS;
    InUserWsStaffEmailAddress = orig.InUserWsStaffEmailAddress;
    InUserWsStaffContactTelno_AS = orig.InUserWsStaffContactTelno_AS;
    InUserWsStaffContactTelno = orig.InUserWsStaffContactTelno;
    InSmsLogMkBatchNr_AS = orig.InSmsLogMkBatchNr_AS;
    InSmsLogMkBatchNr = orig.InSmsLogMkBatchNr;
    InSmsLogReferenceNr_AS = orig.InSmsLogReferenceNr_AS;
    InSmsLogReferenceNr = orig.InSmsLogReferenceNr;
    InSmsLogCellNr_AS = orig.InSmsLogCellNr_AS;
    InSmsLogCellNr = orig.InSmsLogCellNr;
    InSmsLogMessage_AS = orig.InSmsLogMessage_AS;
    InSmsLogMessage = orig.InSmsLogMessage;
    InSmsLogSentOn_AS = orig.InSmsLogSentOn_AS;
    InSmsLogSentOn = orig.InSmsLogSentOn;
    InSmsLogDeliveredOn_AS = orig.InSmsLogDeliveredOn_AS;
    InSmsLogDeliveredOn = orig.InSmsLogDeliveredOn;
    InSmsLogMessageStatus_AS = orig.InSmsLogMessageStatus_AS;
    InSmsLogMessageStatus = orig.InSmsLogMessageStatus;
    InSmsLogMkPersNr_AS = orig.InSmsLogMkPersNr_AS;
    InSmsLogMkPersNr = orig.InSmsLogMkPersNr;
    InSmsLogSequenceNr_AS = orig.InSmsLogSequenceNr_AS;
    InSmsLogSequenceNr = orig.InSmsLogSequenceNr;
    InCsfClientServerCommunicationsClientVersionNumber_AS = 
      orig.InCsfClientServerCommunicationsClientVersionNumber_AS;
    InCsfClientServerCommunicationsClientVersionNumber = 
      orig.InCsfClientServerCommunicationsClientVersionNumber;
    InCsfClientServerCommunicationsClientRevisionNumber_AS = 
      orig.InCsfClientServerCommunicationsClientRevisionNumber_AS;
    InCsfClientServerCommunicationsClientRevisionNumber = 
      orig.InCsfClientServerCommunicationsClientRevisionNumber;
    InCsfClientServerCommunicationsClientDevelopmentPhase_AS = 
      orig.InCsfClientServerCommunicationsClientDevelopmentPhase_AS;
    InCsfClientServerCommunicationsClientDevelopmentPhase = 
      orig.InCsfClientServerCommunicationsClientDevelopmentPhase;
    InCsfClientServerCommunicationsAction_AS = 
      orig.InCsfClientServerCommunicationsAction_AS;
    InCsfClientServerCommunicationsAction = 
      orig.InCsfClientServerCommunicationsAction;
    InCsfClientServerCommunicationsClientIsGuiFlag_AS = 
      orig.InCsfClientServerCommunicationsClientIsGuiFlag_AS;
    InCsfClientServerCommunicationsClientIsGuiFlag = 
      orig.InCsfClientServerCommunicationsClientIsGuiFlag;
    InCsfClientServerCommunicationsClientDate_AS = 
      orig.InCsfClientServerCommunicationsClientDate_AS;
    InCsfClientServerCommunicationsClientDate = 
      orig.InCsfClientServerCommunicationsClientDate;
    InCsfClientServerCommunicationsClientTime_AS = 
      orig.InCsfClientServerCommunicationsClientTime_AS;
    InCsfClientServerCommunicationsClientTime = 
      orig.InCsfClientServerCommunicationsClientTime;
    InCsfClientServerCommunicationsClientTimestamp_AS = 
      orig.InCsfClientServerCommunicationsClientTimestamp_AS;
    InCsfClientServerCommunicationsClientTimestamp = 
      orig.InCsfClientServerCommunicationsClientTimestamp;
    InCsfClientServerCommunicationsClientTransactionCode_AS = 
      orig.InCsfClientServerCommunicationsClientTransactionCode_AS;
    InCsfClientServerCommunicationsClientTransactionCode = 
      orig.InCsfClientServerCommunicationsClientTransactionCode;
    InCsfClientServerCommunicationsClientUserId_AS = 
      orig.InCsfClientServerCommunicationsClientUserId_AS;
    InCsfClientServerCommunicationsClientUserId = 
      orig.InCsfClientServerCommunicationsClientUserId;
    InCsfClientServerCommunicationsListLinkFlag_AS = 
      orig.InCsfClientServerCommunicationsListLinkFlag_AS;
    InCsfClientServerCommunicationsListLinkFlag = 
      orig.InCsfClientServerCommunicationsListLinkFlag;
    InCsfClientServerCommunicationsMaintLinkFlag_AS = 
      orig.InCsfClientServerCommunicationsMaintLinkFlag_AS;
    InCsfClientServerCommunicationsMaintLinkFlag = 
      orig.InCsfClientServerCommunicationsMaintLinkFlag;
    InCsfClientServerCommunicationsFirstpassFlag_AS = 
      orig.InCsfClientServerCommunicationsFirstpassFlag_AS;
    InCsfClientServerCommunicationsFirstpassFlag = 
      orig.InCsfClientServerCommunicationsFirstpassFlag;
  }
}
